import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { CLAUDE_HOME_CONFLICT_EXIT_CODE, assertRealClaudeExecutable, claudeLauncherFileName, detectClaudeHomeConflict, findRealClaudeExecutable, plannedClaudeLaunchers, profileForLauncherName, removeClaudeLauncherShims, runClaudeProfile, runNativeClaude, syncClaudeLauncherShims } from "../src/claude-launchers";
import type { RunClaudeProfileOptions } from "../src/claude-launchers";
import type { ClaudeProfileRecord, FrogConfig } from "../src/types";

const originalEnv = { ...process.env };

/** Portable Claude executable fixture name: bare `claude` on POSIX, PATHEXT-suffixed on Windows. */
const CLAUDE_EXE = process.platform === "win32" ? "claude.exe" : "claude";

beforeEach(() => {
  // Managed-launch tests must not inherit the Claude Code home of the test runner itself. Conflict
  // behavior is covered explicitly below with injected `env` values.
  delete process.env.CLAUDE_CONFIG_DIR;
  delete process.env.CLAUDE_HOME;
});

afterEach(() => {
  for (const key of ["FROGPROGSY_HOME", "PATH", "FROGP_REAL_CLAUDE", "CLAUDE_CONFIG_DIR", "CLAUDE_HOME"] as const) {
    const value = originalEnv[key];
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

function config(): FrogConfig {
  return {
    port: 10100,
    defaultProvider: "anthropic",
    providers: {
      anthropic: { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "forward", defaultModel: "claude-sonnet-4-6" },
    },
    claudeProfiles: {
      schemaVersion: 1,
      defaultProfileId: "cp_default",
      profiles: [
        { id: "cp_default", name: "Default Claude Code", claudeHome: "/tmp/.claude" },
        { id: "cp_work", name: "anthropic-work", claudeHome: "/tmp/.claude-work" },
        { id: "cp_personal", name: "Personal", claudeHome: "/tmp/.claude-personal" },
      ],
    },
  };
}

function executable(path: string, content = "#!/bin/sh\nexit 0\n") {
  writeFileSync(path, content, "utf8");
  chmodSync(path, 0o755);
}

describe("Claude launchers", () => {
  test("plans exactly one account shortcut per profile and never plain claude", () => {
    const plan = plannedClaudeLaunchers(config());
    expect(plan.launchers.map(entry => entry.name).sort()).toEqual([
      "claude-anthropic-work",
      "claude-personal",
    ]);
    expect(plan.launchers.map(entry => entry.name)).not.toContain("claude");
  });

  test("writes managed shims with a pinned frogp command and the real Claude binary", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-launchers-"));
    const realBin = join(home, "real-bin");
    const cmuxBin = join(home, "cmux-cli-shims");
    const fakeFrogp = join(home, process.platform === "win32" ? "fake-frogp.cmd" : "fake-frogp");
    const frogpOut = join(home, "frogp-args.txt");
    mkdirSync(realBin);
    mkdirSync(cmuxBin);
    executable(join(realBin, CLAUDE_EXE));
    executable(join(cmuxBin, CLAUDE_EXE));
    executable(
      fakeFrogp,
      process.platform === "win32"
        ? '@echo off\r\n> "%FROGP_OUT%" echo %FROGP_REAL_CLAUDE%\r\n:args\r\nif "%~1"=="" goto done\r\n>> "%FROGP_OUT%" echo %~1\r\nshift\r\ngoto args\r\n:done\r\n'
        : "#!/bin/sh\nprintf '%s\\n' \"$FROGP_REAL_CLAUDE\" > \"$FROGP_OUT\"\nfor arg in \"$@\"; do printf '%s\\n' \"$arg\" >> \"$FROGP_OUT\"; done\n",
    );
    process.env.FROGPROGSY_HOME = join(home, "frog");
    process.env.PATH = `${cmuxBin}${delimiter}${realBin}`;
    delete process.env.FROGP_REAL_CLAUDE;
    const realClaude = realpathSync.native(join(realBin, CLAUDE_EXE));
    const legacyPersonal = join(process.env.FROGPROGSY_HOME, "bin", "claude-personal");
    if (process.platform === "win32") {
      mkdirSync(join(process.env.FROGPROGSY_HOME, "bin"), { recursive: true });
      writeFileSync(legacyPersonal, "# Generated by frogprogsy\n", "utf8");
    }

    const result = syncClaudeLauncherShims(config(), { frogpCommand: [fakeFrogp] });

    expect(result.realClaude).toBe(realClaude);
    expect(result.frogpCommand).toEqual([fakeFrogp]);
    expect(result.launchers.some(entry => entry.name === "claude-personal" && entry.profileId === "cp_personal")).toBe(true);
    const personal = join(result.binDir, claudeLauncherFileName("claude-personal"));
    expect(existsSync(personal)).toBe(true);
    if (process.platform === "win32") expect(existsSync(legacyPersonal)).toBe(false);
    const script = readFileSync(personal, "utf8");
    expect(script).toContain("Generated by frogprogsy");
    if (process.platform === "win32") {
      expect(script).toContain(`set "FROGP_REAL_CLAUDE=${realClaude}"`);
      expect(script).toContain(`"${fakeFrogp}" "claude" "run" "cp_personal" "--" %*`);
      expect(script).not.toContain("#!/bin/sh");
    } else {
      expect(script).toContain(`FROGP_REAL_CLAUDE='${realClaude}'`);
      expect(script).toContain(`exec '${fakeFrogp}' 'claude' 'run' 'cp_personal' '--' "$@"`);
      expect(script).not.toContain("exec frogp ");
    }
    const executed = process.platform === "win32"
      ? spawnSync(`"${personal}" --version`, {
          shell: true,
          env: { ...process.env, FROGP_OUT: frogpOut },
          encoding: "utf8",
        })
      : spawnSync(personal, ["--version"], {
          env: { ...process.env, FROGP_OUT: frogpOut, PATH: "/usr/bin:/bin" },
          encoding: "utf8",
        });
    expect(executed.status).toBe(0);
    expect(readFileSync(frogpOut, "utf8").trim().split(/\r?\n/)).toEqual([
      realClaude,
      "claude",
      "run",
      "cp_personal",
      "--",
      "--version",
    ]);

    const removed = removeClaudeLauncherShims();
    expect(removed.removed).toContain("claude-personal");
    expect(existsSync(personal)).toBe(false);
    rmSync(home, { recursive: true, force: true });
  });

  test("removes marked plain and stale alias launchers without a manifest but preserves user files", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-orphan-launchers-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    const plainTarget = join(binDir, claudeLauncherFileName("claude"));
    const staleAliasTarget = join(binDir, claudeLauncherFileName("claude-anthropic-work-old"));
    const userTarget = join(binDir, claudeLauncherFileName("claude-user-owned"));
    writeFileSync(plainTarget, "# Generated by frogprogsy\n", "utf8");
    writeFileSync(staleAliasTarget, "# Generated by frogprogsy\n", "utf8");
    writeFileSync(userTarget, "#!/bin/sh\n# user-owned, no managed marker\n", "utf8");

    const result = syncClaudeLauncherShims(config(), {
      realClaude,
      frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
    });

    expect(result.removed).toContain("claude");
    expect(result.removed).toContain("claude-anthropic-work-old");
    expect(existsSync(plainTarget)).toBe(false);
    expect(existsSync(staleAliasTarget)).toBe(false);
    expect(existsSync(userTarget)).toBe(true);

    rmSync(home, { recursive: true, force: true });
  });

  test("removes stale launchers even when no original Claude executable resolves", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-unresolved-launchers-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    mkdirSync(binDir, { recursive: true });
    process.env.FROGPROGSY_HOME = frogHome;
    process.env.PATH = join(home, "empty-bin");
    delete process.env.FROGP_REAL_CLAUDE;

    const staleTarget = join(binDir, claudeLauncherFileName("claude-anthropic-work-old"));
    const userTarget = join(binDir, claudeLauncherFileName("claude-user-owned"));
    writeFileSync(staleTarget, "# Generated by frogprogsy\n", "utf8");
    writeFileSync(userTarget, "#!/bin/sh\n# user-owned, no managed marker\n", "utf8");

    const result = syncClaudeLauncherShims(config());

    expect(result.realClaudeResolved).toBe(false);
    expect(result.removed).toContain("claude-anthropic-work-old");
    expect(existsSync(staleTarget)).toBe(false);
    expect(existsSync(userTarget)).toBe(true);
    // No shortcut is generated without a validated executable.
    expect(existsSync(join(binDir, claudeLauncherFileName("claude-personal")))).toBe(false);

    rmSync(home, { recursive: true, force: true });
  });

  test("removes a same-name launcher that belongs to a replaced profile when no original Claude executable resolves", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-replaced-launcher-"));
    const frogHome = join(home, "frog");
    const realClaude = join(home, CLAUDE_EXE);
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    const initial = syncClaudeLauncherShims(config(), { realClaude });
    const staleTarget = join(initial.binDir, claudeLauncherFileName("claude-personal"));
    expect(existsSync(staleTarget)).toBe(true);

    const replacement = config();
    replacement.claudeProfiles!.profiles = replacement.claudeProfiles!.profiles.map(profile =>
      profile.id === "cp_personal"
        ? { ...profile, id: "cp_replacement", claudeHome: "/tmp/.claude-personal-replacement" }
        : profile);
    process.env.PATH = join(home, "empty-bin");
    delete process.env.FROGP_REAL_CLAUDE;

    const result = syncClaudeLauncherShims(replacement);

    expect(result.realClaudeResolved).toBe(false);
    expect(result.removed).toContain("claude-personal");
    expect(existsSync(staleTarget)).toBe(false);
    expect(result.launchers.map(entry => entry.profileId)).not.toContain("cp_personal");

    rmSync(home, { recursive: true, force: true });
  });

  test("does not report a user replacement as a managed launcher when no original Claude executable resolves", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-user-replaced-launcher-"));
    const frogHome = join(home, "frog");
    const realClaude = join(home, CLAUDE_EXE);
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    const initial = syncClaudeLauncherShims(config(), { realClaude });
    const replacedTarget = join(initial.binDir, claudeLauncherFileName("claude-personal"));
    const userContent = process.platform === "win32" ? "@echo off\r\necho user-owned\r\n" : "#!/bin/sh\necho user-owned\n";
    writeFileSync(replacedTarget, userContent, "utf8");
    process.env.PATH = join(home, "empty-bin");
    delete process.env.FROGP_REAL_CLAUDE;

    const result = syncClaudeLauncherShims(config());
    const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
      launchers: Array<{ profileId: string }>;
    };

    expect(readFileSync(replacedTarget, "utf8")).toBe(userContent);
    expect(result.launchers.map(entry => entry.profileId)).not.toContain("cp_personal");
    expect(manifest.launchers.map(entry => entry.profileId)).not.toContain("cp_personal");

    rmSync(home, { recursive: true, force: true });
  });

  test("removes a same-name stale managed launcher without a manifest when no original Claude executable resolves", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-unmanifested-stale-launcher-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    mkdirSync(binDir, { recursive: true });
    process.env.FROGPROGSY_HOME = frogHome;
    process.env.PATH = join(home, "empty-bin");
    delete process.env.FROGP_REAL_CLAUDE;

    const replacement = config();
    replacement.claudeProfiles!.profiles = replacement.claudeProfiles!.profiles.map(profile =>
      profile.id === "cp_personal"
        ? { ...profile, id: "cp_replacement", claudeHome: "/tmp/.claude-personal-replacement" }
        : profile);
    const staleTarget = join(binDir, claudeLauncherFileName("claude-personal"));
    const staleScript = process.platform === "win32"
      ? [
          "@echo off",
          "rem Generated by frogprogsy. Do not edit by hand.",
          '"frogp" "claude" "run" "cp_personal" "--" %*',
          "",
        ].join("\r\n")
      : [
          "#!/bin/sh",
          "# Generated by frogprogsy. Do not edit by hand.",
          "exec 'frogp' 'claude' 'run' 'cp_personal' '--' \"$@\"",
          "",
        ].join("\n");
    writeFileSync(staleTarget, staleScript, "utf8");

    const result = syncClaudeLauncherShims(replacement);

    expect(result.realClaudeResolved).toBe(false);
    expect(result.removed).toContain("claude-personal");
    expect(existsSync(staleTarget)).toBe(false);

    rmSync(home, { recursive: true, force: true });
  });

  test("rebuilds a missing manifest from matching managed launchers when no original Claude executable resolves", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-rebuild-launcher-manifest-"));
    const frogHome = join(home, "frog");
    const realClaude = join(home, CLAUDE_EXE);
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    const initial = syncClaudeLauncherShims(config(), { realClaude });
    const manifestPath = join(frogHome, "claude-launchers.json");
    rmSync(manifestPath);
    process.env.PATH = join(home, "empty-bin");
    delete process.env.FROGP_REAL_CLAUDE;

    const result = syncClaudeLauncherShims(config());
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
      launchers: Array<{ profileId: string }>;
    };

    expect(result.realClaudeResolved).toBe(false);
    expect(result.launchers.map(entry => entry.profileId)).toContain("cp_personal");
    expect(manifest.launchers.map(entry => entry.profileId)).toContain("cp_personal");
    expect(existsSync(join(initial.binDir, claudeLauncherFileName("claude-personal")))).toBe(true);

    rmSync(home, { recursive: true, force: true });
  });

  test("findRealClaudeExecutable skips a source-form launcher from another worktree and returns the next real claude", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-realclaude-"));
    // A sibling worktree's source launcher: no generated marker, but delegates to runClaudeLauncherProcess.
    const worktreeSrc = join(root, "other-worktree", "src");
    const realDir = join(root, "realbin");
    mkdirSync(worktreeSrc, { recursive: true });
    mkdirSync(realDir, { recursive: true });
    executable(
      join(worktreeSrc, CLAUDE_EXE),
      '#!/usr/bin/env bun\nimport { runClaudeLauncherProcess } from "./claude-launchers";\nrunClaudeLauncherProcess(process.argv.slice(2), "claude");\n',
    );
    executable(join(realDir, CLAUDE_EXE));
    const realClaude = realpathSync.native(join(realDir, CLAUDE_EXE));

    process.env.FROGPROGSY_HOME = join(root, "frog");
    process.env.PATH = `${worktreeSrc}${delimiter}${realDir}`;
    delete process.env.FROGP_REAL_CLAUDE;

    // The source launcher sorts first on PATH; the resolver must skip it and return the genuine binary.
    expect(findRealClaudeExecutable()).toBe(realClaude);
    rmSync(root, { recursive: true, force: true });
  });
});
const SENTINEL_TOKEN = "local-frogprogsy";

const gatewayHome = mkdtempSync(join(tmpdir(), "frog-launcher-profile-home-"));
const gatewayProfile: ClaudeProfileRecord = { id: "cp_work", name: "anthropic-work", claudeHome: gatewayHome };

function refreshFake(order: string[], failWith?: string): NonNullable<RunClaudeProfileOptions["refreshCatalog"]> {
  return (async () => {
    order.push("refresh");
    if (failWith) throw new Error(failWith);
    return { added: 0, path: "/catalog", catalogExists: false, cacheSynced: false, gatewayCache: { status: "skipped" as const }, warnings: [] };
  }) as unknown as NonNullable<RunClaudeProfileOptions["refreshCatalog"]>;
}

function spawnFake(order: string[], capture: { env?: NodeJS.ProcessEnv }): NonNullable<RunClaudeProfileOptions["spawn"]> {
  return ((_cmd: string, _args: readonly string[], opts: { env?: NodeJS.ProcessEnv }) => {
    order.push("spawn");
    capture.env = opts.env;
    return { status: 0, signal: null } as unknown as ReturnType<typeof spawnSync>;
  }) as unknown as NonNullable<RunClaudeProfileOptions["spawn"]>;
}

function exitFake(capture: { code?: number }): NonNullable<RunClaudeProfileOptions["exit"]> {
  return ((code: number) => { capture.code = code; }) as unknown as NonNullable<RunClaudeProfileOptions["exit"]>;
}

describe("managed launch account-home conflict", () => {
  test("allows an unset caller home and canonically identical CLAUDE_CONFIG_DIR/CLAUDE_HOME values", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-home-conflict-"));
    const home = join(root, "home");
    const link = join(root, "home-link");
    mkdirSync(home);
    symlinkSync(home, link, "dir");

    expect(detectClaudeHomeConflict(home, {})).toBeNull();
    expect(detectClaudeHomeConflict(home, { CLAUDE_CONFIG_DIR: home })).toBeNull();
    expect(detectClaudeHomeConflict(home, { CLAUDE_HOME: link })).toBeNull();
    expect(detectClaudeHomeConflict(home, { CLAUDE_CONFIG_DIR: home, CLAUDE_HOME: link })).toBeNull();

    rmSync(root, { recursive: true, force: true });
  });

  test("refuses different, mutually inconsistent, missing, and non-directory caller homes", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-home-conflict-"));
    const registered = join(root, "registered");
    const other = join(root, "other");
    const file = join(root, "file");
    mkdirSync(registered);
    mkdirSync(other);
    writeFileSync(file, "not a directory", "utf8");

    expect(detectClaudeHomeConflict(registered, { CLAUDE_CONFIG_DIR: other })).toEqual({
      source: "CLAUDE_CONFIG_DIR",
      reason: "different-home",
    });
    expect(detectClaudeHomeConflict(registered, { CLAUDE_CONFIG_DIR: registered, CLAUDE_HOME: other })).toEqual({
      source: "CLAUDE_HOME",
      reason: "different-home",
    });
    expect(detectClaudeHomeConflict(registered, { CLAUDE_CONFIG_DIR: join(root, "missing") })).toEqual({
      source: "CLAUDE_CONFIG_DIR",
      reason: "unreadable",
    });
    expect(detectClaudeHomeConflict(registered, { CLAUDE_HOME: file })).toEqual({
      source: "CLAUDE_HOME",
      reason: "unreadable",
    });

    rmSync(root, { recursive: true, force: true });
  });

  test("refuses before cache refresh, executable validation, or spawn and uses a fixed exit code", async () => {
    const root = mkdtempSync(join(tmpdir(), "frog-home-conflict-"));
    const registered = join(root, "registered");
    const other = join(root, "other");
    mkdirSync(registered);
    mkdirSync(other);
    const profile: ClaudeProfileRecord = { ...gatewayProfile, claudeHome: registered };
    const order: string[] = [];
    const exit: { code?: number } = {};
    const errors = captureConsoleError();
    try {
      await runClaudeProfile(profile, config(), [], {
        env: { CLAUDE_CONFIG_DIR: other },
        validateExecutable: candidate => { order.push(`validate:${candidate}`); return candidate!; },
        refreshCatalog: refreshFake(order),
        spawn: spawnFake(order, {}),
        exit: exitFake(exit),
      });
    } finally {
      errors.restore();
    }

    expect(exit.code).toBe(CLAUDE_HOME_CONFLICT_EXIT_CODE);
    expect(order).toEqual([]);
    expect(errors.messages.join("\n")).not.toContain(registered);
    expect(errors.messages.join("\n")).not.toContain(other);
    expect(errors.messages.join("\n")).toContain("claude-anthropic-work");

    rmSync(root, { recursive: true, force: true });
  });
});

describe("managed launch real-Claude validation", () => {
  test("validates an explicit real-Claude value before refresh or spawn", async () => {
    const order: string[] = [];
    const exit: { code?: number } = {};
    await runClaudeProfile(gatewayProfile, config(), [], {
      env: {},
      gateway: true,
      realClaude: "/real/claude",
      validateExecutable: candidate => {
        order.push(`validate:${candidate}`);
        return "/verified/claude";
      },
      refreshCatalog: refreshFake(order),
      spawn: ((command: string) => {
        order.push(`spawn:${command}`);
        return { status: 0, signal: null, error: undefined } as ReturnType<typeof spawnSync>;
      }) as typeof spawnSync,
      exit: exitFake(exit),
    });

    expect(order).toEqual(["validate:/real/claude", "refresh", "spawn:/verified/claude"]);
    expect(exit.code).toBe(0);
  });

  test("refuses a bare executable instead of falling back through PATH", () => {
    expect(() => assertRealClaudeExecutable("claude")).toThrow(/non-absolute/);
  });
});

describe("runClaudeProfile carrier + pre-launch cache", () => {
  afterEach(() => {
    const value = originalEnv.ANTHROPIC_AUTH_TOKEN;
    if (value === undefined) delete process.env.ANTHROPIC_AUTH_TOKEN;
    else process.env.ANTHROPIC_AUTH_TOKEN = value;
  });

  test("gateway launch defaults to the token-free carrier and strips any inherited sentinel token", async () => {
    process.env.ANTHROPIC_AUTH_TOKEN = SENTINEL_TOKEN;
    const order: string[] = [];
    const captured: { env?: NodeJS.ProcessEnv } = {};
    const exit: { code?: number } = {};
    await runClaudeProfile(gatewayProfile, config(), ["--version"], {
      gateway: true,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, captured),
      exit: exitFake(exit),
    });
    expect(captured.env?.ANTHROPIC_BASE_URL).toMatch(/^http:\/\/localhost:/);
    expect(captured.env?.CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY).toBe("1");
    expect(captured.env?.ANTHROPIC_AUTH_TOKEN).toBeUndefined();
    expect(exit.code).toBe(0);
  });

  test("gateway launch injects the sentinel token only on explicit rollback", async () => {
    const cfg: FrogConfig = { ...config(), gatewayAuthCarrier: "sentinel" };
    const captured: { env?: NodeJS.ProcessEnv } = {};
    await runClaudeProfile(gatewayProfile, cfg, [], {
      gateway: true,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake([]),
      spawn: spawnFake([], captured),
      exit: exitFake({}),
    });
    expect(captured.env?.ANTHROPIC_AUTH_TOKEN).toBe(SENTINEL_TOKEN);
  });

  test("refreshes the profile picker cache before spawning the gateway Claude", async () => {
    const order: string[] = [];
    await runClaudeProfile(gatewayProfile, config(), [], {
      gateway: true,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, {}),
      exit: exitFake({}),
    });
    expect(order).toEqual(["refresh", "spawn"]);
  });

  test("a transient refresh failure warns without leaking secrets and still launches", async () => {
    const order: string[] = [];
    const exit: { code?: number } = {};
    const warnings: string[] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => { warnings.push(args.map(String).join(" ")); };
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: true,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        refreshCatalog: refreshFake(order, "boom /Users/secret/.claude token=sk-leaked"),
        spawn: spawnFake(order, {}),
        exit: exitFake(exit),
      });
    } finally {
      console.warn = originalWarn;
    }
    expect(order).toEqual(["refresh", "spawn"]);
    expect(exit.code).toBe(0);
    expect(warnings.length).toBe(1);
    expect(warnings[0]).toContain("cp_work");
    expect(warnings[0]).not.toContain("sk-leaked");
    expect(warnings[0]).not.toContain("/Users/secret/.claude");
  });

  test("a returned cache failure warns without exposing provider detail and still launches", async () => {
    const order: string[] = [];
    const warnings: string[] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => { warnings.push(args.map(String).join(" ")); };
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: true,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        refreshCatalog: (async () => {
          order.push("refresh");
          return {
            added: 0,
            path: "/private/catalog",
            catalogExists: false,
            cacheSynced: false,
            gatewayCache: { status: "failed" as const, warning: "credential sk-secret failed" },
            warnings: ["credential sk-secret failed"],
          };
        }) as NonNullable<RunClaudeProfileOptions["refreshCatalog"]>,
        spawn: spawnFake(order, {}),
        exit: exitFake({}),
      });
    } finally {
      console.warn = originalWarn;
    }
    expect(order).toEqual(["refresh", "spawn"]);
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain("cp_work");
    expect(warnings[0]).toContain("when available");
    expect(warnings[0]).not.toContain("sk-secret");
    expect(warnings[0]).not.toContain("/private/catalog");
  });

  test("native (non-gateway) launch never refreshes the catalog and drops gateway env", async () => {
    const order: string[] = [];
    const captured: { env?: NodeJS.ProcessEnv } = {};
    await runClaudeProfile(gatewayProfile, config(), [], {
      gateway: false,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, captured),
      exit: exitFake({}),
    });
    expect(order).toEqual(["spawn"]);
    expect(captured.env?.ANTHROPIC_BASE_URL).toBeUndefined();
    expect(captured.env?.CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY).toBeUndefined();
    expect(captured.env?.CLAUDE_CONFIG_DIR).toBe(gatewayHome);
  });
});
const LAUNCHER_FAILURE_MESSAGE = "frogprogsy: failed to launch the Claude executable.";

function spawnReturning(result: Partial<ReturnType<typeof spawnSync>>): NonNullable<RunClaudeProfileOptions["spawn"]> {
  return (() => result as unknown as ReturnType<typeof spawnSync>) as unknown as NonNullable<RunClaudeProfileOptions["spawn"]>;
}

function captureConsoleError(): { messages: string[]; restore: () => void } {
  const messages: string[] = [];
  const original = console.error;
  console.error = (...args: unknown[]) => { messages.push(args.map(String).join(" ")); };
  return { messages, restore: () => { console.error = original; } };
}

function spawnError(code: string, path: string): NodeJS.ErrnoException {
  return Object.assign(new Error(`spawn ${path} ${code}`), { code, path, syscall: `spawn ${path}` });
}

describe("launcher spawn failure exit codes", () => {
  test("runClaudeProfile maps an ENOENT spawn failure to 127 with a fixed, redacted diagnostic", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), ["--version"], {
        gateway: false,
        realClaude: "/opt/homebrew/bin/claude",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("ENOENT", "/opt/homebrew/bin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(127);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/opt/homebrew/bin/claude");
    expect(err.messages[0]).not.toContain("ENOENT");
  });

  test("runClaudeProfile maps an EACCES spawn failure to 1 without leaking the path", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/tmp/blocked/claude",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("EACCES", "/tmp/blocked/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/tmp/blocked/claude");
  });

  test("runClaudeProfile: a signal kill without a status never surfaces as exit 0", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: null, signal: "SIGKILL" }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toHaveLength(0);
  });

  test("runClaudeProfile: an ordinary non-zero status propagates unchanged", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: 3, signal: null }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(3);
    expect(err.messages).toHaveLength(0);
  });

  test("runNativeClaude maps an ENOENT spawn failure to 127 with a redacted diagnostic", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude(["--help"], {
        realClaude: "/usr/local/bin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("ENOENT", "/usr/local/bin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(127);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/usr/local/bin/claude");
  });

  test("runNativeClaude maps an EACCES spawn failure to 1", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude([], {
        realClaude: "/sbin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("EACCES", "/sbin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
  });

  test("runNativeClaude: an ordinary status propagates unchanged (including 0)", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude([], {
        realClaude: "/usr/bin/true",
        spawn: spawnReturning({ status: 0, signal: null }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(0);
    expect(err.messages).toHaveLength(0);
  });
});

describe("launcher alias routing", () => {
  test("an exact planned shortcut name routes to its exact profileId", () => {
    expect(profileForLauncherName(config(), "claude-anthropic-work").id).toBe("cp_work");
    expect(profileForLauncherName(config(), "claude-personal").id).toBe("cp_personal");
    expect(() => profileForLauncherName(config(), "claude-default")).toThrow(/Unknown Claude Code home/);
  });

  test("plain claude never routes to a frogprogsy profile", () => {
    expect(() => profileForLauncherName(config(), "claude")).toThrow(/Unknown Claude Code home/);
  });

  test("an unknown or stale alias throws Unknown Claude Code home instead of silently using the default profile", () => {
    expect(() => profileForLauncherName(config(), "claude-ghost")).toThrow(/Unknown Claude Code home/);
    expect(() => profileForLauncherName(config(), "claude-cp_removed")).toThrow(/Unknown Claude Code home/);
    let routed: string | undefined;
    try {
      routed = profileForLauncherName(config(), "claude-ghost").id;
    } catch {
      routed = undefined;
    }
    expect(routed).toBeUndefined();
  });
});
