import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { appendFileSync, chmodSync, existsSync, linkSync, lstatSync, mkdtempSync, mkdirSync, readFileSync, readSync, readdirSync, readlinkSync, realpathSync, renameSync, rmSync, statSync, symlinkSync, writeFileSync, writeSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { CLAUDE_HOME_CONFLICT_EXIT_CODE, assertRealClaudeExecutable, claudeLauncherFileName, detectClaudeHomeConflict, findRealClaudeExecutable, isManagedClaudeProfileLauncher, plannedClaudeLaunchers, profileForLauncherName, removeClaudeLauncherShims, runClaudeProfile, runNativeClaude, syncClaudeLauncherShims } from "../src/claude-launchers";
import type { RunClaudeProfileOptions } from "../src/claude-launchers";
import type { ClaudeProfileRecord, FrogConfig } from "../src/types";

const originalEnv = { ...process.env };

/** Portable Claude executable fixture name: bare `claude` on POSIX, PATHEXT-suffixed on Windows. */
const CLAUDE_EXE = process.platform === "win32" ? "claude.exe" : "claude";
const testPathReplacementRace = process.platform === "win32" ? test.skip : test;

beforeEach(() => {
  // Managed-launch tests must not inherit the Claude Code home of the test runner itself. Conflict
  // behavior is covered explicitly below with injected `env` values.
  delete process.env.CLAUDE_CONFIG_DIR;
  delete process.env.CLAUDE_HOME;
});

afterEach(() => {
  for (const key of ["FROGPROGSY_HOME", "PATH", "FROGP_REAL_CLAUDE", "CLAUDE_CONFIG_DIR", "CLAUDE_HOME"] as const) {
    const value = originalEnv[key];
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

function config(): FrogConfig {
  return {
    port: 10100,
    defaultProvider: "anthropic",
    providers: {
      anthropic: { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "forward", defaultModel: "claude-sonnet-4-6" },
    },
    claudeProfiles: {
      schemaVersion: 1,
      defaultProfileId: "cp_default",
      profiles: [
        { id: "cp_default", name: "Default Claude Code", claudeHome: "/tmp/.claude" },
        { id: "cp_work", name: "anthropic-work", claudeHome: "/tmp/.claude-work" },
        { id: "cp_personal", name: "Personal", claudeHome: "/tmp/.claude-personal" },
      ],
    },
  };
}

function executable(path: string, content = "#!/bin/sh\nexit 0\n") {
  writeFileSync(path, content, "utf8");
  chmodSync(path, 0o755);
}

function managedLauncherBytes(profileId = "cp_old"): string {
  return process.platform === "win32"
    ? `@echo off\r\nrem Generated by frogprogsy. Do not edit by hand.\r\n"frogp" "claude" "run" "${profileId}" "--" %*\r\n`
    : `#!/bin/sh\n# Generated by frogprogsy. Do not edit by hand.\nexec 'frogp' 'claude' 'run' '${profileId}' '--' "$@"\n`;
}

describe("Claude launchers", () => {
  test("plans exactly one account shortcut per profile and never plain claude", () => {
    const plan = plannedClaudeLaunchers(config());
    expect(plan.launchers.map(entry => entry.name).sort()).toEqual([
      "claude-anthropic-work",
      "claude-personal",
    ]);
    expect(plan.launchers.map(entry => entry.name)).not.toContain("claude");
  });

  test("writes managed shims with a pinned frogp command and the real Claude binary", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-launchers-"));
    const realBin = join(home, "real-bin");
    const cmuxBin = join(home, "cmux-cli-shims");
    const fakeFrogp = join(home, process.platform === "win32" ? "fake-frogp.cmd" : "fake-frogp");
    const frogpOut = join(home, "frogp-args.txt");
    mkdirSync(realBin);
    mkdirSync(cmuxBin);
    executable(join(realBin, CLAUDE_EXE));
    executable(join(cmuxBin, CLAUDE_EXE));
    executable(
      fakeFrogp,
      process.platform === "win32"
        ? '@echo off\r\n> "%FROGP_OUT%" echo %FROGP_REAL_CLAUDE%\r\n:args\r\nif "%~1"=="" goto done\r\n>> "%FROGP_OUT%" echo %~1\r\nshift\r\ngoto args\r\n:done\r\n'
        : "#!/bin/sh\nprintf '%s\\n' \"$FROGP_REAL_CLAUDE\" > \"$FROGP_OUT\"\nfor arg in \"$@\"; do printf '%s\\n' \"$arg\" >> \"$FROGP_OUT\"; done\n",
    );
    process.env.FROGPROGSY_HOME = join(home, "frog");
    process.env.PATH = `${cmuxBin}${delimiter}${realBin}`;
    delete process.env.FROGP_REAL_CLAUDE;
    const realClaude = realpathSync.native(join(realBin, CLAUDE_EXE));
    const legacyPersonal = join(process.env.FROGPROGSY_HOME, "bin", "claude-personal");
    if (process.platform === "win32") {
      mkdirSync(join(process.env.FROGPROGSY_HOME, "bin"), { recursive: true });
      writeFileSync(legacyPersonal, "# Generated by frogprogsy\n", "utf8");
    }

    const result = syncClaudeLauncherShims(config(), { frogpCommand: [fakeFrogp] });

    expect(result.realClaude).toBe(realClaude);
    expect(result.frogpCommand).toEqual([fakeFrogp]);
    expect(result.launchers.some(entry => entry.name === "claude-personal" && entry.profileId === "cp_personal")).toBe(true);
    const personal = join(result.binDir, claudeLauncherFileName("claude-personal"));
    expect(existsSync(personal)).toBe(true);
    if (process.platform === "win32") expect(existsSync(legacyPersonal)).toBe(false);
    const script = readFileSync(personal, "utf8");
    expect(script).toContain("Generated by frogprogsy");
    if (process.platform === "win32") {
      expect(script).toContain(`set "FROGP_REAL_CLAUDE=${realClaude}"`);
      expect(script).toContain(`"${fakeFrogp}" "claude" "run" "cp_personal" "--" %*`);
      expect(script).not.toContain("#!/bin/sh");
    } else {
      expect(script).toContain(`FROGP_REAL_CLAUDE='${realClaude}'`);
      expect(script).toContain(`exec '${fakeFrogp}' 'claude' 'run' 'cp_personal' '--' "$@"`);
      expect(script).not.toContain("exec frogp ");
    }
    const executed = process.platform === "win32"
      ? spawnSync(`"${personal}" --version`, {
          shell: true,
          env: { ...process.env, FROGP_OUT: frogpOut },
          encoding: "utf8",
        })
      : spawnSync(personal, ["--version"], {
          env: { ...process.env, FROGP_OUT: frogpOut, PATH: "/usr/bin:/bin" },
          encoding: "utf8",
        });
    expect(executed.status).toBe(0);
    expect(readFileSync(frogpOut, "utf8").trim().split(/\r?\n/)).toEqual([
      realClaude,
      "claude",
      "run",
      "cp_personal",
      "--",
      "--version",
    ]);

    expect(isManagedClaudeProfileLauncher(personal, "cp_personal")).toBe(true);
    expect(isManagedClaudeProfileLauncher(personal, "cp_work")).toBe(false);

    const removed = removeClaudeLauncherShims();
    expect(removed.removed).toContain("claude-personal");
    expect(existsSync(personal)).toBe(false);
    rmSync(home, { recursive: true, force: true });
  });

  test("rejects marked symlinks and multiply hardlinked files as managed profile launchers", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-launcher-status-ownership-"));
    const symlinkTarget = join(home, "managed-symlink-target");
    const symlink = join(home, "managed-symlink");
    const hardlinkTarget = join(home, "managed-hardlink-target");
    const hardlink = join(home, "managed-hardlink");
    writeFileSync(symlinkTarget, managedLauncherBytes("cp_personal"), "utf8");
    symlinkSync(symlinkTarget, symlink, "file");
    writeFileSync(hardlinkTarget, managedLauncherBytes("cp_personal"), "utf8");
    linkSync(hardlinkTarget, hardlink);

    try {
      expect(isManagedClaudeProfileLauncher(symlink, "cp_personal")).toBe(false);
      expect(isManagedClaudeProfileLauncher(hardlinkTarget, "cp_personal")).toBe(false);
      expect(isManagedClaudeProfileLauncher(hardlink, "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("removes marked plain and stale alias launchers without a manifest but preserves user files", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-orphan-launchers-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    const plainTarget = join(binDir, claudeLauncherFileName("claude"));
    const staleAliasTarget = join(binDir, claudeLauncherFileName("claude-anthropic-work-old"));
    const userTarget = join(binDir, claudeLauncherFileName("claude-user-owned"));
    writeFileSync(plainTarget, "# Generated by frogprogsy\n", "utf8");
    writeFileSync(staleAliasTarget, "# Generated by frogprogsy\n", "utf8");
    writeFileSync(userTarget, "#!/bin/sh\n# user-owned, no managed marker\n", "utf8");

    const result = syncClaudeLauncherShims(config(), {
      realClaude,
      frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
    });

    expect(result.removed).toContain("claude");
    expect(result.removed).toContain("claude-anthropic-work-old");
    expect(existsSync(plainTarget)).toBe(false);
    expect(existsSync(staleAliasTarget)).toBe(false);
    expect(existsSync(userTarget)).toBe(true);

    rmSync(home, { recursive: true, force: true });
  });

  test("cleans legacy plain launchers when native Claude is missing and reports only exact-owned survivors", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-unresolved-launcher-cleanup-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const plan = plannedClaudeLaunchers(config()).launchers;
    const workEntry = plan.find(entry => entry.profileId === "cp_work")!;
    const personalEntry = plan.find(entry => entry.profileId === "cp_personal")!;
    const plainEntry = { ...workEntry, name: "claude" };
    const workTarget = join(binDir, claudeLauncherFileName(workEntry.name));
    const personalTarget = join(binDir, claudeLauncherFileName(personalEntry.name));
    const plainTarget = join(binDir, claudeLauncherFileName("claude"));
    const userBytes = "#!/bin/sh\n# user-owned\n";
    mkdirSync(binDir, { recursive: true });
    process.env.FROGPROGSY_HOME = frogHome;
    process.env.PATH = "";
    delete process.env.FROGP_REAL_CLAUDE;
    writeFileSync(
      workTarget,
      process.platform === "win32"
        ? `@echo off\r\nrem Generated by frogprogsy. Do not edit by hand.\r\n"frogp" "claude" "run" "${workEntry.profileId}" "--" %*\r\n`
        : `#!/bin/sh\n# Generated by frogprogsy. Do not edit by hand.\nexec 'frogp' 'claude' 'run' '${workEntry.profileId}' '--' "$@"\n`,
      "utf8",
    );
    writeFileSync(personalTarget, userBytes, "utf8");
    writeFileSync(plainTarget, "# Generated by frogprogsy\n", "utf8");
    writeFileSync(join(frogHome, "claude-launchers.json"), JSON.stringify({
      schemaVersion: 1,
      generatedAt: new Date(0).toISOString(),
      binDir,
      realClaude: "/missing/claude",
      launchers: [workEntry, personalEntry, plainEntry],
    }), "utf8");

    try {
      const result = syncClaudeLauncherShims(config(), {
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(result.realClaudeResolved).toBe(false);
      expect(result.removed).toContain("claude");
      expect(result.launchers).toEqual([workEntry]);
      expect(result.warnings).toContainEqual(expect.stringContaining("install Claude Code"));
      expect(manifest.launchers).toEqual([workEntry]);
      expect(existsSync(plainTarget)).toBe(false);
      expect(readFileSync(workTarget, "utf8")).toContain(workEntry.profileId);
      expect(readFileSync(personalTarget, "utf8")).toBe(userBytes);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("refuses a symlink launcher directory without changing its external target", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-launcher-bin-symlink-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const externalDir = join(home, "external-bin");
    const sentinel = join(externalDir, "user-file");
    const realClaude = join(home, CLAUDE_EXE);
    const userBytes = "user-owned external directory\n";
    mkdirSync(frogHome);
    mkdirSync(externalDir, { mode: 0o750 });
    chmodSync(externalDir, 0o750);
    writeFileSync(sentinel, userBytes, "utf8");
    symlinkSync(externalDir, binDir, "dir");
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      expect(() => syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      })).toThrow(/launcher directory/);
      expect(readFileSync(sentinel, "utf8")).toBe(userBytes);
      if (process.platform !== "win32") expect(statSync(externalDir).mode & 0o777).toBe(0o750);
      expect(existsSync(join(externalDir, claudeLauncherFileName("claude-personal")))).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test.skipIf(process.platform !== "win32")("prepares a real launcher directory without requiring a Windows directory handle flush", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-launcher-windows-directory-"));
    const frogHome = join(home, "frog");
    const realClaude = join(home, CLAUDE_EXE);
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(result.launchers.map(entry => entry.profileId).sort()).toEqual(["cp_personal", "cp_work"]);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves user-owned planned targets and excludes them from the result and manifest", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-owned-launcher-conflict-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const userBytes = "#!/bin/sh\n# user-owned\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    const workTarget = join(binDir, claudeLauncherFileName("claude-anthropic-work"));
    const personalTarget = join(binDir, claudeLauncherFileName("claude-personal"));
    mkdirSync(workTarget);
    writeFileSync(personalTarget, userBytes, "utf8");

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(existsSync(workTarget)).toBe(true);
      expect(readFileSync(personalTarget, "utf8")).toBe(userBytes);
      expect(result.launchers).toEqual([]);
      expect(result.warnings).toEqual(expect.arrayContaining([
        expect.stringContaining("claude-anthropic-work"),
        expect.stringContaining("claude-personal"),
      ]));
      expect(manifest.launchers).toEqual([]);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("replaces a stale managed same-name launcher with the current profile", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-stale-managed-launcher-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    writeFileSync(
      target,
      process.platform === "win32"
        ? '@echo off\r\nrem Generated by frogprogsy. Do not edit by hand.\r\n"frogp" "claude" "run" "cp_old" "--" %*\r\n'
        : "#!/bin/sh\n# Generated by frogprogsy. Do not edit by hand.\nexec 'frogp' 'claude' 'run' 'cp_old' '--' \"$@\"\n",
      "utf8",
    );

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(isManagedClaudeProfileLauncher(target, "cp_personal")).toBe(true);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(true);
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(true);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  for (const firstWriteBytes of [0, 1] as const) {
    const failureKind = firstWriteBytes === 0 ? "a zero-byte write" : "a partial write";
    test(`keeps an existing managed launcher recoverable after ${failureKind} fails`, () => {
      const home = mkdtempSync(join(tmpdir(), "frog-managed-write-failure-"));
      const frogHome = join(home, "frog");
      const binDir = join(frogHome, "bin");
      const realClaude = join(home, CLAUDE_EXE);
      const target = join(binDir, claudeLauncherFileName("claude-personal"));
      const originalBytes = managedLauncherBytes();
      mkdirSync(binDir, { recursive: true });
      executable(realClaude);
      process.env.FROGPROGSY_HOME = frogHome;
      writeFileSync(target, originalBytes, "utf8");

      try {
        let writeCalls = 0;
        const failed = syncClaudeLauncherShims(config(), {
          realClaude,
          frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
          writeManagedLauncherChunk(fd: number, buffer: Uint8Array, offset: number, length: number, position: number) {
            if (writeCalls++ > 0) throw new Error("simulated managed launcher write failure");
            if (firstWriteBytes === 0) return 0;
            return writeSync(fd, buffer, offset, Math.min(firstWriteBytes, length), position);
          },
        });

        expect(failed.launchers).not.toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
        expect(failed.warnings).toContain(
          "launcher claude-personal skipped for Personal; target changed or could not be published safely",
        );
        expect(readFileSync(target, "utf8")).toContain("Generated by frogprogsy");

        const repaired = syncClaudeLauncherShims(config(), {
          realClaude,
          frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        });

        expect(isManagedClaudeProfileLauncher(target, "cp_personal")).toBe(true);
        expect(repaired.launchers).toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      } finally {
        rmSync(home, { recursive: true, force: true });
      }
    });
  }

  test("keeps a legacy marker-only launcher classifiable when a partial rewrite stops before the new marker completes", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-legacy-managed-write-failure-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const legacyPrefix = process.platform === "win32"
      ? "rem Generated by frogprogsy\r\nrem "
      : "# Generated by frogprogsy\n# ";
    const legacyBytes = legacyPrefix + "x".repeat((64 * 1024) - Buffer.byteLength(legacyPrefix, "utf8"));
    const partialBytes = process.platform === "win32"
      ? Buffer.byteLength("@echo off\r\nrem Generated by frogprogs", "utf8")
      : Buffer.byteLength("#!/bin/sh\n# Generated by frogprogs", "utf8");
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, legacyBytes, "utf8");

    try {
      let writeCalls = 0;
      const failed = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        writeManagedLauncherChunk(fd: number, buffer: Uint8Array, offset: number, length: number, position: number) {
          if (writeCalls++ > 0) throw new Error("simulated legacy launcher write failure");
          return writeSync(fd, buffer, offset, Math.min(partialBytes, length), position);
        },
      });

      expect(failed.launchers).not.toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      expect(failed.warnings).toContain(
        "launcher claude-personal skipped for Personal; target changed or could not be published safely",
      );
      expect(readFileSync(target, "utf8")).toContain("Generated by frogprogsy");

      const repaired = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(isManagedClaudeProfileLauncher(target, "cp_personal")).toBe(true);
      expect(repaired.launchers).toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("repairs an exact-boundary legacy launcher without appending a second recovery suffix", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-legacy-max-recovery-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const recoverySuffix = process.platform === "win32"
      ? "\r\nrem frogprogsy durable recovery ---------------------------------------------------------------- Generated by frogprogsy\r\n"
      : "\n# frogprogsy durable recovery ---------------------------------------------------------------- Generated by frogprogsy\n";
    const maxManagedBytes = 1024 * 1024;
    const legacyPrefix = process.platform === "win32"
      ? "rem Generated by frogprogsy\r\nrem "
      : "# Generated by frogprogsy\n# ";
    const initialSize = maxManagedBytes - Buffer.byteLength(recoverySuffix, "utf8");
    const legacyBytes = legacyPrefix + "x".repeat(initialSize - Buffer.byteLength(legacyPrefix, "utf8"));
    const partialBytes = process.platform === "win32"
      ? Buffer.byteLength("@echo off\r\nrem Generated by frogprogs", "utf8")
      : Buffer.byteLength("#!/bin/sh\n# Generated by frogprogs", "utf8");
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, legacyBytes, "utf8");

    try {
      let writeCalls = 0;
      const failed = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        writeManagedLauncherChunk(fd: number, buffer: Uint8Array, offset: number, length: number, position: number) {
          if (writeCalls++ > 0) throw new Error("simulated exact-boundary launcher write failure");
          return writeSync(fd, buffer, offset, Math.min(partialBytes, length), position);
        },
      });

      expect(failed.launchers).not.toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      expect(statSync(target).size).toBe(maxManagedBytes);
      expect(readFileSync(target, "utf8").endsWith(recoverySuffix)).toBe(true);

      const failedAgain = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        writeManagedLauncherChunk() {
          return 0;
        },
      });

      expect(failedAgain.launchers).not.toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      expect(statSync(target).size).toBe(maxManagedBytes);
      expect(readFileSync(target, "utf8").endsWith(recoverySuffix)).toBe(true);

      const repaired = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(isManagedClaudeProfileLauncher(target, "cp_personal")).toBe(true);
      expect(repaired.launchers).toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      expect(statSync(target).size).toBeLessThan(maxManagedBytes);
      expect(readFileSync(target, "utf8").endsWith(recoverySuffix)).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("fully reads managed launcher content when the injected reader returns short chunks", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-managed-short-read-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const originalBytes = managedLauncherBytes()
      + (process.platform === "win32" ? "rem " : "# ")
      + "x".repeat(256);
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, originalBytes, "utf8");

    try {
      let readCalls = 0;
      const repaired = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        readManagedLauncherChunk(fd: number, buffer: Uint8Array, offset: number, length: number, position: number) {
          readCalls += 1;
          return readSync(fd, buffer, offset, Math.min(7, length), position);
        },
      });

      expect(readCalls).toBeGreaterThan(1);
      expect(isManagedClaudeProfileLauncher(target, "cp_personal")).toBe(true);
      expect(repaired.launchers).toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves an appended tail when a managed launcher changes beyond the sniff prefix before rewrite", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-managed-tail-cas-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const baseBytes = managedLauncherBytes();
    const paddingPrefix = process.platform === "win32" ? "rem " : "# ";
    const originalBytes = baseBytes
      + paddingPrefix
      + "x".repeat((64 * 1024) - Buffer.byteLength(baseBytes + paddingPrefix, "utf8"));
    const appendedBytes = process.platform === "win32"
      ? "\r\nrem user-owned concurrent tail\r\n"
      : "\n# user-owned concurrent tail\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, originalBytes, "utf8");

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(changingTarget) {
          appendFileSync(changingTarget, appendedBytes, "utf8");
        },
      });

      expect(result.launchers).not.toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      expect(result.warnings).toContain(
        "launcher claude-personal skipped for Personal; target changed or could not be published safely",
      );
      expect(readFileSync(target, "utf8")).toBe(originalBytes + appendedBytes);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("skips an oversized marked launcher with a specific safe-size warning", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-oversized-managed-launcher-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const prefix = managedLauncherBytes();
    const oversizedBytes = prefix + "x".repeat((1024 * 1024) + 1 - Buffer.byteLength(prefix, "utf8"));
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, oversizedBytes, "utf8");

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(result.launchers).not.toContainEqual(expect.objectContaining({ profileId: "cp_personal" }));
      expect(result.warnings).toContain(
        "launcher claude-personal skipped for Personal; managed target exceeds the safe update size",
      );
      expect(readFileSync(target, "utf8")).toBe(oversizedBytes);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("publishes and records an existing managed launcher for a Unicode profile", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-unicode-launcher-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const unicodeConfig = config();
    unicodeConfig.claudeProfiles!.profiles = [
      unicodeConfig.claudeProfiles!.profiles[0]!,
      { id: "cp_업무", name: "업무", claudeHome: join(home, ".claude-업무") },
    ];
    const target = join(binDir, claudeLauncherFileName("claude-profile"));
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, managedLauncherBytes(), "utf8");

    try {
      const result = syncClaudeLauncherShims(unicodeConfig, {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string; profileName: string }>;
      };

      expect(isManagedClaudeProfileLauncher(target, "cp_업무")).toBe(true);
      expect(result.launchers).toContainEqual(expect.objectContaining({ profileId: "cp_업무", profileName: "업무" }));
      expect(manifest.launchers).toContainEqual(expect.objectContaining({ profileId: "cp_업무", profileName: "업무" }));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("removes a stale same-name launcher with the wrong profile when native Claude is missing", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-stale-owner-unresolved-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    mkdirSync(binDir, { recursive: true });
    process.env.FROGPROGSY_HOME = frogHome;
    process.env.PATH = "";
    delete process.env.FROGP_REAL_CLAUDE;
    writeFileSync(target, managedLauncherBytes(), "utf8");

    try {
      const result = syncClaudeLauncherShims(config(), {
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(result.realClaudeResolved).toBe(false);
      expect(existsSync(target)).toBe(false);
      expect(result.removed).toContain("claude-personal");
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  testPathReplacementRace("preserves an unmarked regular file atomically replacing a managed target before publish", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-regular-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const replacement = join(binDir, ".claude-personal-user-replacement");
    const userBytes = "#!/bin/sh\n# user-owned replacement\n";
    const userMode = 0o640;
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, managedLauncherBytes(), "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(publishTarget: string) {
          if (publishTarget !== target) return;
          writeFileSync(replacement, userBytes, { encoding: "utf8", mode: userMode });
          chmodSync(replacement, userMode);
          renameSync(replacement, target);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      if (process.platform !== "win32") expect(statSync(target).mode & 0o777).toBe(userMode);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  testPathReplacementRace("preserves a symlink atomically replacing a managed target before publish", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-symlink-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const userTarget = join(home, "user-launcher");
    const replacement = join(binDir, ".claude-personal-user-link");
    const userBytes = "#!/bin/sh\n# user-owned symlink target\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(userTarget, userBytes, "utf8");
    writeFileSync(target, managedLauncherBytes(), "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(publishTarget: string) {
          if (publishTarget !== target) return;
          symlinkSync(userTarget, replacement, "file");
          renameSync(replacement, target);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(lstatSync(target).isSymbolicLink()).toBe(true);
      expect(readlinkSync(target)).toBe(userTarget);
      expect(readFileSync(userTarget, "utf8")).toBe(userBytes);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves a user target created after an absent target was classified and before publish", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-create-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const userBytes = "#!/bin/sh\n# user-created during publish\n";
    const userMode = 0o640;
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(publishTarget: string) {
          if (publishTarget !== target) return;
          writeFileSync(target, userBytes, { encoding: "utf8", mode: userMode });
          chmodSync(target, userMode);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      if (process.platform !== "win32") expect(statSync(target).mode & 0o777).toBe(userMode);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("excludes a newly linked launcher when its directory entry cannot be durably published", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-fsync-failure-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        fsyncDirectory: () => false,
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(result.launchers).toEqual([]);
      expect(manifest.launchers).toEqual([]);
      expect(result.warnings).toEqual(expect.arrayContaining([
        expect.stringContaining("claude-anthropic-work"),
        expect.stringContaining("claude-personal"),
      ]));
      expect(existsSync(join(binDir, claudeLauncherFileName("claude-anthropic-work")))).toBe(false);
      expect(existsSync(join(binDir, claudeLauncherFileName("claude-personal")))).toBe(false);
      expect(readdirSync(binDir).filter(name => name.endsWith(".tmp"))).toEqual([]);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("does not rewrite a managed target whose inode is hardlinked outside the launcher directory", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-hardlink-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const external = join(home, "external-managed-bytes");
    const originalBytes = managedLauncherBytes();
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(external, originalBytes, "utf8");
    linkSync(external, target);

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(readFileSync(target, "utf8")).toBe(originalBytes);
      expect(readFileSync(external, "utf8")).toBe(originalBytes);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("does not rewrite a managed inode hardlinked after ownership classification", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-hardlink-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const external = join(home, "external-managed-bytes");
    const originalBytes = managedLauncherBytes();
    const originalMode = 0o640;
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, originalBytes, { encoding: "utf8", mode: originalMode });
    chmodSync(target, originalMode);

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(publishTarget: string) {
          if (publishTarget === target) linkSync(target, external);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(readFileSync(target, "utf8")).toBe(originalBytes);
      expect(readFileSync(external, "utf8")).toBe(originalBytes);
      if (process.platform !== "win32") {
        expect(statSync(target).mode & 0o777).toBe(originalMode);
        expect(statSync(external).mode & 0o777).toBe(originalMode);
      }
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves an in-place user edit made after managed ownership classification", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-in-place-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-personal"));
    const userBytes = "#!/bin/sh\n# user edited this inode in place\n";
    const userMode = 0o640;
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, managedLauncherBytes(), "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(publishTarget: string) {
          if (publishTarget !== target) return;
          writeFileSync(target, userBytes, "utf8");
          chmodSync(target, userMode);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      if (process.platform !== "win32") expect(statSync(target).mode & 0o777).toBe(userMode);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  testPathReplacementRace("does not publish into a launcher directory atomically replaced after classification", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-publish-bin-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const movedBin = join(home, "managed-bin");
    const realClaude = join(home, CLAUDE_EXE);
    const personalTarget = join(binDir, claudeLauncherFileName("claude-personal"));
    const sentinel = join(binDir, "user-file");
    const userBytes = "user-owned replacement directory\n";
    const userMode = 0o750;
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforePublish(publishTarget: string) {
          if (publishTarget !== personalTarget) return;
          renameSync(binDir, movedBin);
          mkdirSync(binDir, { mode: userMode });
          chmodSync(binDir, userMode);
          writeFileSync(sentinel, userBytes, "utf8");
          const temporaryName = readdirSync(movedBin).find(name => name.endsWith(".tmp"))!;
          linkSync(join(movedBin, temporaryName), join(binDir, temporaryName));
        },
      };
      const result = syncClaudeLauncherShims(config(), options);
      const manifest = JSON.parse(readFileSync(join(frogHome, "claude-launchers.json"), "utf8")) as {
        launchers: Array<{ profileId: string }>;
      };

      expect(readFileSync(sentinel, "utf8")).toBe(userBytes);
      if (process.platform !== "win32") expect(statSync(binDir).mode & 0o777).toBe(userMode);
      expect(existsSync(personalTarget)).toBe(false);
      expect(result.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-personal"));
      expect(manifest.launchers.some(entry => entry.profileId === "cp_personal")).toBe(false);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves an unmarked regular file atomically replacing a managed orphan before cleanup", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-regular-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const replacement = join(binDir, ".claude-stale-user-replacement");
    const userBytes = "#!/bin/sh\n# user-owned replacement\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          writeFileSync(replacement, userBytes, "utf8");
          renameSync(replacement, target);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("restores a marker-preserving same-inode edit captured after managed cleanup classification", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-in-place-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const originalBytes = "# Generated by frogprogsy\n";
    const userTail = "# user-owned in-place tail\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, originalBytes, "utf8");

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget === target) appendFileSync(removeTarget, userTail, "utf8");
        },
      });

      expect(readFileSync(target, "utf8")).toBe(originalBytes + userTail);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContain(
        `launcher ${claudeLauncherFileName("claude-stale")} cleanup deferred; the changed target was restored; manual recovery/cleanup is required before removing the preserved capture`,
      );
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("does not capture from a launcher directory atomically replaced before cleanup", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-bin-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const movedBin = join(home, "managed-bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const sentinel = join(binDir, "user-file");
    const userBytes = "#!/bin/sh\n# user-owned replacement directory target\n";
    const sentinelBytes = "user-owned replacement directory\n";
    const userMode = 0o750;
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          const recoveryRootName = ".frogprogsy-launcher-recovery";
          const oldRecoveryRoot = join(binDir, recoveryRootName);
          const operationName = readdirSync(oldRecoveryRoot).find(name => name !== "owner")!;
          renameSync(binDir, movedBin);
          mkdirSync(binDir, { mode: userMode });
          chmodSync(binDir, userMode);
          writeFileSync(sentinel, sentinelBytes, "utf8");
          writeFileSync(target, userBytes, "utf8");
          mkdirSync(join(binDir, recoveryRootName), { mode: 0o700 });
          mkdirSync(join(binDir, recoveryRootName, operationName), { mode: 0o700 });
        },
      };
      expect(() => syncClaudeLauncherShims(config(), options)).toThrow(/launcher directory changed/);

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      expect(readFileSync(sentinel, "utf8")).toBe(sentinelBytes);
      if (process.platform !== "win32") expect(statSync(binDir).mode & 0o777).toBe(userMode);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("does not overwrite a user target when capture durability fails", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-fsync-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const userBytes = "#!/bin/sh\n# user-created while capture durability failed\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemoveDurability(removeTarget: string) {
          if (removeTarget === target) writeFileSync(target, userBytes, "utf8");
        },
        fsyncDirectory: () => false,
      };
      const result = syncClaudeLauncherShims(config(), options);

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves a symlink atomically replacing a managed orphan before cleanup", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-symlink-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const userTarget = join(home, "user-launcher");
    const replacement = join(binDir, ".claude-stale-user-link");
    const userBytes = "#!/bin/sh\n# user-owned symlink target\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(userTarget, userBytes, "utf8");
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          symlinkSync(userTarget, replacement, "file");
          renameSync(replacement, target);
        },
      };
      const result = syncClaudeLauncherShims(config(), options);

      expect(lstatSync(target).isSymbolicLink()).toBe(true);
      expect(readlinkSync(target)).toBe(userTarget);
      expect(readFileSync(userTarget, "utf8")).toBe(userBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("silently cleans a capture-pending journal when no target was captured", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-before-capture-crash-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const targetName = claudeLauncherFileName("claude-personal");
    const target = join(binDir, targetName);
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      const options = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      };
      syncClaudeLauncherShims(config(), options);
      const originalBytes = readFileSync(target, "utf8");

      const recoveryRoot = join(binDir, ".frogprogsy-launcher-recovery");
      const operationDir = join(recoveryRoot, "interrupted-before-capture");
      mkdirSync(operationDir, { recursive: true, mode: 0o700 });
      chmodSync(recoveryRoot, 0o700);
      writeFileSync(join(recoveryRoot, "owner"), "Generated by frogprogsy launcher recovery\n", "utf8");
      writeFileSync(join(operationDir, "manifest.json"), JSON.stringify({
        schemaVersion: 1,
        phase: "capture-pending",
        targetName,
      }) + "\n", "utf8");

      const result = syncClaudeLauncherShims(config(), options);

      expect(readFileSync(target, "utf8")).toBe(originalBytes);
      expect(readdirSync(recoveryRoot)).toEqual(["owner"]);
      expect(result.removed).not.toContain("claude-personal");
      expect(result.warnings).not.toContainEqual(expect.stringContaining(targetName));
      expect(result.warnings).not.toContainEqual(expect.stringContaining("restored"));
      expect(result.warnings).not.toContainEqual(expect.stringContaining("manual recovery"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("recovers a captured unmarked regular file after cleanup is interrupted", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-regular-recovery-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const replacement = join(binDir, ".claude-stale-user-replacement");
    const userBytes = "#!/bin/sh\n# captured user replacement\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const crash = new Error("simulated cleanup interruption");
      const crashingOptions = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          writeFileSync(replacement, userBytes, "utf8");
          renameSync(replacement, target);
        },
        afterManagedRemoveCapture(removeTarget: string) {
          if (removeTarget === target) throw crash;
        },
      };

      expect(() => syncClaudeLauncherShims(config(), crashingOptions)).toThrow(crash);
      expect(existsSync(target)).toBe(false);

      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(readFileSync(target, "utf8")).toBe(userBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("keeps captured user bytes on a different inode when the restored regular target is rewritten in place", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-restore-race-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const capturedReplacement = join(binDir, ".claude-stale-captured-user");
    const capturedUserBytes = "#!/bin/sh\n# captured user replacement\n";
    const postRestoreUserBytes = "#!/bin/sh\n# in-place post-restore user rewrite\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const crash = new Error("simulated cleanup interruption");
      expect(() => syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          writeFileSync(capturedReplacement, capturedUserBytes, "utf8");
          renameSync(capturedReplacement, target);
        },
        afterManagedRemoveCapture(removeTarget: string) {
          if (removeTarget === target) throw crash;
        },
      })).toThrow(crash);

      let capture = "";
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        afterForeignRestore(restoreTarget: string, recoveryCapture: string) {
          if (restoreTarget !== target) return;
          capture = recoveryCapture;
          writeFileSync(restoreTarget, postRestoreUserBytes, "utf8");
        },
      });

      expect(readFileSync(target, "utf8")).toBe(postRestoreUserBytes);
      expect(readFileSync(capture, "utf8")).toBe(capturedUserBytes);
      expect(statSync(target).ino).not.toBe(statSync(capture).ino);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContain(
        `launcher ${claudeLauncherFileName("claude-stale")} cleanup deferred; the changed target was restored; manual recovery/cleanup is required before removing the preserved capture`,
      );
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("preserves the capture when a restored regular target cannot be durably recorded", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-restore-fsync-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const capturedReplacement = join(binDir, ".claude-stale-captured-user");
    const capturedUserBytes = "#!/bin/sh\n# captured user replacement\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const crash = new Error("simulated cleanup interruption");
      expect(() => syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          writeFileSync(capturedReplacement, capturedUserBytes, "utf8");
          renameSync(capturedReplacement, target);
        },
        afterManagedRemoveCapture(removeTarget: string) {
          if (removeTarget === target) throw crash;
        },
      })).toThrow(crash);

      let capture = "";
      let restored = false;
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        afterForeignRestore(restoreTarget: string, recoveryCapture: string) {
          if (restoreTarget !== target) return;
          capture = recoveryCapture;
          restored = true;
        },
        fsyncDirectory: path => !(restored && path === binDir),
      });

      expect(readFileSync(target, "utf8")).toBe(capturedUserBytes);
      expect(readFileSync(capture, "utf8")).toBe(capturedUserBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContain(`launcher ${claudeLauncherFileName("claude-stale")} cleanup deferred; preserved recovery requires attention`);
      expect(result.warnings).not.toContain(
        `launcher ${claudeLauncherFileName("claude-stale")} cleanup deferred; the changed target was restored; manual recovery/cleanup is required before removing the preserved capture`,
      );
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("recovers a captured symlink after cleanup is interrupted", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-symlink-recovery-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const userTarget = join(home, "user-launcher");
    const replacement = join(binDir, ".claude-stale-user-link");
    const userBytes = "#!/bin/sh\n# captured user symlink target\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(userTarget, userBytes, "utf8");
    writeFileSync(target, "# Generated by frogprogsy\n", "utf8");

    try {
      const crash = new Error("simulated cleanup interruption");
      const crashingOptions = {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
        beforeManagedRemove(removeTarget: string) {
          if (removeTarget !== target) return;
          symlinkSync(userTarget, replacement, "file");
          renameSync(replacement, target);
        },
        afterManagedRemoveCapture(removeTarget: string) {
          if (removeTarget === target) throw crash;
        },
      };

      expect(() => syncClaudeLauncherShims(config(), crashingOptions)).toThrow(crash);
      expect(existsSync(target)).toBe(false);

      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(lstatSync(target).isSymbolicLink()).toBe(true);
      expect(readlinkSync(target)).toBe(userTarget);
      expect(readFileSync(userTarget, "utf8")).toBe(userBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("does not remove a managed orphan whose inode is hardlinked outside the launcher directory", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-remove-hardlink-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const realClaude = join(home, CLAUDE_EXE);
    const target = join(binDir, claudeLauncherFileName("claude-stale"));
    const external = join(home, "external-managed-bytes");
    const originalBytes = "# Generated by frogprogsy\n";
    mkdirSync(binDir, { recursive: true });
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;
    writeFileSync(external, originalBytes, "utf8");
    linkSync(external, target);

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(readFileSync(target, "utf8")).toBe(originalBytes);
      expect(readFileSync(external, "utf8")).toBe(originalBytes);
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("refuses a foreign recovery-root symlink without changing its external target", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-recovery-root-symlink-"));
    const frogHome = join(home, "frog");
    const binDir = join(frogHome, "bin");
    const recoveryRoot = join(binDir, ".frogprogsy-launcher-recovery");
    const externalDir = join(home, "external-recovery");
    const sentinel = join(externalDir, "user-file");
    const realClaude = join(home, CLAUDE_EXE);
    const staleTarget = join(binDir, claudeLauncherFileName("claude-stale"));
    const userBytes = "user-owned recovery directory\n";
    mkdirSync(binDir, { recursive: true });
    mkdirSync(externalDir, { mode: 0o750 });
    chmodSync(externalDir, 0o750);
    writeFileSync(sentinel, userBytes, "utf8");
    symlinkSync(externalDir, recoveryRoot, "dir");
    writeFileSync(staleTarget, "# Generated by frogprogsy\n", "utf8");
    executable(realClaude);
    process.env.FROGPROGSY_HOME = frogHome;

    try {
      const result = syncClaudeLauncherShims(config(), {
        realClaude,
        frogpCommand: [process.execPath, join(process.cwd(), "src", "cli.ts")],
      });

      expect(readFileSync(staleTarget, "utf8")).toContain("Generated by frogprogsy");
      expect(result.removed).not.toContain("claude-stale");
      expect(result.warnings).toContainEqual(expect.stringContaining("claude-stale"));
      expect(readFileSync(sentinel, "utf8")).toBe(userBytes);
      if (process.platform !== "win32") expect(statSync(externalDir).mode & 0o777).toBe(0o750);
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("findRealClaudeExecutable skips a source-form launcher from another worktree and returns the next real claude", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-realclaude-"));
    // A sibling worktree's source launcher: no generated marker, but delegates to runClaudeLauncherProcess.
    const worktreeSrc = join(root, "other-worktree", "src");
    const realDir = join(root, "realbin");
    mkdirSync(worktreeSrc, { recursive: true });
    mkdirSync(realDir, { recursive: true });
    executable(
      join(worktreeSrc, CLAUDE_EXE),
      '#!/usr/bin/env bun\nimport { runClaudeLauncherProcess } from "./claude-launchers";\nrunClaudeLauncherProcess(process.argv.slice(2), "claude");\n',
    );
    executable(join(realDir, CLAUDE_EXE));
    const realClaude = realpathSync.native(join(realDir, CLAUDE_EXE));

    process.env.FROGPROGSY_HOME = join(root, "frog");
    process.env.PATH = `${worktreeSrc}${delimiter}${realDir}`;
    delete process.env.FROGP_REAL_CLAUDE;

    // The source launcher sorts first on PATH; the resolver must skip it and return the genuine binary.
    expect(findRealClaudeExecutable()).toBe(realClaude);
    rmSync(root, { recursive: true, force: true });
  });
});
const SENTINEL_TOKEN = "local-frogprogsy";

const gatewayHome = mkdtempSync(join(tmpdir(), "frog-launcher-profile-home-"));
const gatewayProfile: ClaudeProfileRecord = { id: "cp_work", name: "anthropic-work", claudeHome: gatewayHome };

function refreshFake(order: string[], failWith?: string): NonNullable<RunClaudeProfileOptions["refreshCatalog"]> {
  return (async () => {
    order.push("refresh");
    if (failWith) throw new Error(failWith);
    return { added: 0, path: "/catalog", catalogExists: false, cacheSynced: false, gatewayCache: { status: "skipped" as const }, warnings: [] };
  }) as unknown as NonNullable<RunClaudeProfileOptions["refreshCatalog"]>;
}

function spawnFake(order: string[], capture: { env?: NodeJS.ProcessEnv }): NonNullable<RunClaudeProfileOptions["spawn"]> {
  return ((_cmd: string, _args: readonly string[], opts: { env?: NodeJS.ProcessEnv }) => {
    order.push("spawn");
    capture.env = opts.env;
    return { status: 0, signal: null } as unknown as ReturnType<typeof spawnSync>;
  }) as unknown as NonNullable<RunClaudeProfileOptions["spawn"]>;
}

function exitFake(capture: { code?: number }): NonNullable<RunClaudeProfileOptions["exit"]> {
  return ((code: number) => { capture.code = code; }) as unknown as NonNullable<RunClaudeProfileOptions["exit"]>;
}

describe("managed launch account-home conflict", () => {
  test("allows an unset caller home and canonically identical CLAUDE_CONFIG_DIR/CLAUDE_HOME values", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-home-conflict-"));
    const home = join(root, "home");
    const link = join(root, "home-link");
    mkdirSync(home);
    symlinkSync(home, link, "dir");

    expect(detectClaudeHomeConflict(home, {})).toBeNull();
    expect(detectClaudeHomeConflict(home, { CLAUDE_CONFIG_DIR: home })).toBeNull();
    expect(detectClaudeHomeConflict(home, { CLAUDE_HOME: link })).toBeNull();
    expect(detectClaudeHomeConflict(home, { CLAUDE_CONFIG_DIR: home, CLAUDE_HOME: link })).toBeNull();

    rmSync(root, { recursive: true, force: true });
  });

  test("refuses different, mutually inconsistent, missing, and non-directory caller homes", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-home-conflict-"));
    const registered = join(root, "registered");
    const other = join(root, "other");
    const file = join(root, "file");
    mkdirSync(registered);
    mkdirSync(other);
    writeFileSync(file, "not a directory", "utf8");

    expect(detectClaudeHomeConflict(registered, { CLAUDE_CONFIG_DIR: other })).toEqual({
      source: "CLAUDE_CONFIG_DIR",
      reason: "different-home",
    });
    expect(detectClaudeHomeConflict(registered, { CLAUDE_CONFIG_DIR: registered, CLAUDE_HOME: other })).toEqual({
      source: "CLAUDE_HOME",
      reason: "different-home",
    });
    expect(detectClaudeHomeConflict(registered, { CLAUDE_CONFIG_DIR: join(root, "missing") })).toEqual({
      source: "CLAUDE_CONFIG_DIR",
      reason: "unreadable",
    });
    expect(detectClaudeHomeConflict(registered, { CLAUDE_HOME: file })).toEqual({
      source: "CLAUDE_HOME",
      reason: "unreadable",
    });

    rmSync(root, { recursive: true, force: true });
  });

  test("refuses before cache refresh, executable validation, or spawn and uses a fixed exit code", async () => {
    const root = mkdtempSync(join(tmpdir(), "frog-home-conflict-"));
    const registered = join(root, "registered");
    const other = join(root, "other");
    mkdirSync(registered);
    mkdirSync(other);
    const profile: ClaudeProfileRecord = { ...gatewayProfile, claudeHome: registered };
    const order: string[] = [];
    const exit: { code?: number } = {};
    const errors = captureConsoleError();
    try {
      await runClaudeProfile(profile, config(), [], {
        env: { CLAUDE_CONFIG_DIR: other },
        validateExecutable: candidate => { order.push(`validate:${candidate}`); return candidate!; },
        refreshCatalog: refreshFake(order),
        spawn: spawnFake(order, {}),
        exit: exitFake(exit),
      });
    } finally {
      errors.restore();
    }

    expect(exit.code).toBe(CLAUDE_HOME_CONFLICT_EXIT_CODE);
    expect(order).toEqual([]);
    expect(errors.messages.join("\n")).not.toContain(registered);
    expect(errors.messages.join("\n")).not.toContain(other);
    expect(errors.messages.join("\n")).toContain("claude-anthropic-work");

    rmSync(root, { recursive: true, force: true });
  });
});

describe("managed launch real-Claude validation", () => {
  test("validates an explicit real-Claude value before refresh or spawn", async () => {
    const order: string[] = [];
    const exit: { code?: number } = {};
    await runClaudeProfile(gatewayProfile, config(), [], {
      env: {},
      gateway: true,
      realClaude: "/real/claude",
      validateExecutable: candidate => {
        order.push(`validate:${candidate}`);
        return "/verified/claude";
      },
      refreshCatalog: refreshFake(order),
      spawn: ((command: string) => {
        order.push(`spawn:${command}`);
        return { status: 0, signal: null, error: undefined } as ReturnType<typeof spawnSync>;
      }) as typeof spawnSync,
      exit: exitFake(exit),
    });

    expect(order).toEqual(["validate:/real/claude", "refresh", "spawn:/verified/claude"]);
    expect(exit.code).toBe(0);
  });

  test("refuses a bare executable instead of falling back through PATH", () => {
    expect(() => assertRealClaudeExecutable("claude")).toThrow(/non-absolute/);
  });
});

describe("runClaudeProfile carrier + pre-launch cache", () => {
  afterEach(() => {
    const value = originalEnv.ANTHROPIC_AUTH_TOKEN;
    if (value === undefined) delete process.env.ANTHROPIC_AUTH_TOKEN;
    else process.env.ANTHROPIC_AUTH_TOKEN = value;
  });

  test("gateway launch defaults to the token-free carrier and strips any inherited sentinel token", async () => {
    process.env.ANTHROPIC_AUTH_TOKEN = SENTINEL_TOKEN;
    const order: string[] = [];
    const captured: { env?: NodeJS.ProcessEnv } = {};
    const exit: { code?: number } = {};
    await runClaudeProfile(gatewayProfile, config(), ["--version"], {
      gateway: true,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, captured),
      exit: exitFake(exit),
    });
    expect(captured.env?.ANTHROPIC_BASE_URL).toMatch(/^http:\/\/localhost:/);
    expect(captured.env?.CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY).toBe("1");
    expect(captured.env?.ANTHROPIC_AUTH_TOKEN).toBeUndefined();
    expect(exit.code).toBe(0);
  });

  test("gateway launch injects the sentinel token only on explicit rollback", async () => {
    const cfg: FrogConfig = { ...config(), gatewayAuthCarrier: "sentinel" };
    const captured: { env?: NodeJS.ProcessEnv } = {};
    await runClaudeProfile(gatewayProfile, cfg, [], {
      gateway: true,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake([]),
      spawn: spawnFake([], captured),
      exit: exitFake({}),
    });
    expect(captured.env?.ANTHROPIC_AUTH_TOKEN).toBe(SENTINEL_TOKEN);
  });

  test("refreshes the profile picker cache before spawning the gateway Claude", async () => {
    const order: string[] = [];
    await runClaudeProfile(gatewayProfile, config(), [], {
      gateway: true,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, {}),
      exit: exitFake({}),
    });
    expect(order).toEqual(["refresh", "spawn"]);
  });

  test("a transient refresh failure warns without leaking secrets and still launches", async () => {
    const order: string[] = [];
    const exit: { code?: number } = {};
    const warnings: string[] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => { warnings.push(args.map(String).join(" ")); };
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: true,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        refreshCatalog: refreshFake(order, "boom /Users/secret/.claude token=sk-leaked"),
        spawn: spawnFake(order, {}),
        exit: exitFake(exit),
      });
    } finally {
      console.warn = originalWarn;
    }
    expect(order).toEqual(["refresh", "spawn"]);
    expect(exit.code).toBe(0);
    expect(warnings.length).toBe(1);
    expect(warnings[0]).toContain("cp_work");
    expect(warnings[0]).not.toContain("sk-leaked");
    expect(warnings[0]).not.toContain("/Users/secret/.claude");
  });

  test("a returned cache failure warns without exposing provider detail and still launches", async () => {
    const order: string[] = [];
    const warnings: string[] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => { warnings.push(args.map(String).join(" ")); };
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: true,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        refreshCatalog: (async () => {
          order.push("refresh");
          return {
            added: 0,
            path: "/private/catalog",
            catalogExists: false,
            cacheSynced: false,
            gatewayCache: { status: "failed" as const, warning: "credential sk-secret failed" },
            warnings: ["credential sk-secret failed"],
          };
        }) as NonNullable<RunClaudeProfileOptions["refreshCatalog"]>,
        spawn: spawnFake(order, {}),
        exit: exitFake({}),
      });
    } finally {
      console.warn = originalWarn;
    }
    expect(order).toEqual(["refresh", "spawn"]);
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain("cp_work");
    expect(warnings[0]).toContain("when available");
    expect(warnings[0]).not.toContain("sk-secret");
    expect(warnings[0]).not.toContain("/private/catalog");
  });

  test("native (non-gateway) launch never refreshes the catalog and drops gateway env", async () => {
    const order: string[] = [];
    const captured: { env?: NodeJS.ProcessEnv } = {};
    await runClaudeProfile(gatewayProfile, config(), [], {
      gateway: false,
      realClaude: "/usr/bin/true",
      validateExecutable: candidate => candidate!,
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, captured),
      exit: exitFake({}),
    });
    expect(order).toEqual(["spawn"]);
    expect(captured.env?.ANTHROPIC_BASE_URL).toBeUndefined();
    expect(captured.env?.CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY).toBeUndefined();
    expect(captured.env?.CLAUDE_CONFIG_DIR).toBe(gatewayHome);
  });
});
const LAUNCHER_FAILURE_MESSAGE = "frogprogsy: failed to launch the Claude executable.";

function spawnReturning(result: Partial<ReturnType<typeof spawnSync>>): NonNullable<RunClaudeProfileOptions["spawn"]> {
  return (() => result as unknown as ReturnType<typeof spawnSync>) as unknown as NonNullable<RunClaudeProfileOptions["spawn"]>;
}

function captureConsoleError(): { messages: string[]; restore: () => void } {
  const messages: string[] = [];
  const original = console.error;
  console.error = (...args: unknown[]) => { messages.push(args.map(String).join(" ")); };
  return { messages, restore: () => { console.error = original; } };
}

function spawnError(code: string, path: string): NodeJS.ErrnoException {
  return Object.assign(new Error(`spawn ${path} ${code}`), { code, path, syscall: `spawn ${path}` });
}

describe("launcher spawn failure exit codes", () => {
  test("runClaudeProfile maps an ENOENT spawn failure to 127 with a fixed, redacted diagnostic", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), ["--version"], {
        gateway: false,
        realClaude: "/opt/homebrew/bin/claude",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("ENOENT", "/opt/homebrew/bin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(127);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/opt/homebrew/bin/claude");
    expect(err.messages[0]).not.toContain("ENOENT");
  });

  test("runClaudeProfile maps an EACCES spawn failure to 1 without leaking the path", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/tmp/blocked/claude",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("EACCES", "/tmp/blocked/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/tmp/blocked/claude");
  });

  test("runClaudeProfile: a signal kill without a status never surfaces as exit 0", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: null, signal: "SIGKILL" }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toHaveLength(0);
  });

  test("runClaudeProfile: an ordinary non-zero status propagates unchanged", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/usr/bin/true",
        validateExecutable: candidate => candidate!,
        spawn: spawnReturning({ status: 3, signal: null }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(3);
    expect(err.messages).toHaveLength(0);
  });

  test("runNativeClaude maps an ENOENT spawn failure to 127 with a redacted diagnostic", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude(["--help"], {
        realClaude: "/usr/local/bin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("ENOENT", "/usr/local/bin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(127);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/usr/local/bin/claude");
  });

  test("runNativeClaude maps an EACCES spawn failure to 1", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude([], {
        realClaude: "/sbin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("EACCES", "/sbin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
  });

  test("runNativeClaude: an ordinary status propagates unchanged (including 0)", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude([], {
        realClaude: "/usr/bin/true",
        spawn: spawnReturning({ status: 0, signal: null }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(0);
    expect(err.messages).toHaveLength(0);
  });
});

describe("launcher alias routing", () => {
  test("an exact planned shortcut name routes to its exact profileId", () => {
    expect(profileForLauncherName(config(), "claude-anthropic-work").id).toBe("cp_work");
    expect(profileForLauncherName(config(), "claude-personal").id).toBe("cp_personal");
    expect(() => profileForLauncherName(config(), "claude-default")).toThrow(/Unknown Claude Code home/);
  });

  test("plain claude never routes to a frogprogsy profile", () => {
    expect(() => profileForLauncherName(config(), "claude")).toThrow(/Unknown Claude Code home/);
  });

  test("an unknown or stale alias throws Unknown Claude Code home instead of silently using the default profile", () => {
    expect(() => profileForLauncherName(config(), "claude-ghost")).toThrow(/Unknown Claude Code home/);
    expect(() => profileForLauncherName(config(), "claude-cp_removed")).toThrow(/Unknown Claude Code home/);
    let routed: string | undefined;
    try {
      routed = profileForLauncherName(config(), "claude-ghost").id;
    } catch {
      routed = undefined;
    }
    expect(routed).toBeUndefined();
  });
});
