import { spawnSync } from "node:child_process";
import { accessSync, chmodSync, closeSync, constants, existsSync, mkdirSync, openSync, readFileSync, readdirSync, readSync, realpathSync, rmSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { delimiter, dirname, isAbsolute, join, resolve, sep } from "node:path";
import { DEFAULT_PORT, atomicWriteFile, ensureConfigDirForWrite, getConfigDir, readActivePort, readPid } from "./config";
import { buildClaudeProfileNativeEnv, buildClaudeProfileRunEnv, managedClaudeProfiles, resolveClaudeProfile } from "./claude-profiles";
import type { ClaudeProfileRecord, FrogConfig } from "./types";

export interface ClaudeLauncherEntry {
  name: string;
  profileId: string;
  profileName: string;
  claudeHome: string;
}

export interface ClaudeLauncherSyncResult {
  binDir: string;
  realClaude: string;
  /** False when no safe original Claude executable exists, so no shortcut could be generated. */
  realClaudeResolved: boolean;
  launchers: ClaudeLauncherEntry[];
  removed: string[];
  warnings: string[];
  frogpCommand: string[];
}

interface ClaudeLauncherManifest {
  schemaVersion: 1;
  generatedAt: string;
  binDir: string;
  realClaude: string;
  launchers: ClaudeLauncherEntry[];
  frogpCommand?: string[];
}

const MANIFEST_NAME = "claude-launchers.json";
const MANAGED_MARKER = "Generated by frogprogsy";
/**
 * Substring emitted by a source-form frogprogsy launcher: any `.ts` entrypoint that delegates to
 * `runClaudeLauncherProcess` is a legacy launcher even without the generated marker (for example, an
 * older installed package's removed plain-Claude entrypoint). Kept for stale-install detection.
 */
const LAUNCHER_SOURCE_MARKER = "runClaudeLauncherProcess";
/**
 * Bytes sniffed from a candidate's head. Bounded so a multi-hundred-MB native Claude binary is never
 * read in full, while still large enough to capture any launcher's shebang, generated marker, or
 * delegation call which always appear at the very top of the file.
 */
const LAUNCHER_SNIFF_BYTES = 64 * 1024;

/**
 * Windows executable suffixes supported when resolving a bare command like `claude` from PATH.
 * The deterministic order covers the forms Claude installations actually ship as: `.exe` for a
 * native binary and `.cmd`/`.bat`/`.com` for npm/npx-style shims. It intentionally does not depend
 * on machine-specific PATHEXT ordering and is consulted only on win32, leaving POSIX unchanged.
 */
export const WINDOWS_EXECUTABLE_SUFFIXES = [".exe", ".cmd", ".bat", ".com"] as const;

/**
 * On-disk file names to probe, in PATH-order preference, for a base command such as `claude`.
 * POSIX: exactly the bare name (exact behavior preserved). Windows: the PATHEXT-like suffixed forms,
 * unless `base` already carries a recognized suffix (then it is used verbatim).
 */
export function claudeExecutableCandidates(base = "claude"): string[] {
  if (process.platform !== "win32") return [base];
  const lower = base.toLowerCase();
  if (WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => lower.endsWith(suffix))) return [base];
  return WINDOWS_EXECUTABLE_SUFFIXES.map(suffix => `${base}${suffix}`);
}
/** Platform-native filename for a generated managed launcher alias. */
export function claudeLauncherFileName(name: string): string {
  return process.platform === "win32" ? `${name}.cmd` : name;
}

/** True when `path` ends with a Windows executable suffix (PATHEXT-like). Case-insensitive. */
export function hasWindowsExecutableSuffix(path: string): boolean {
  const lower = path.toLowerCase();
  return WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => lower.endsWith(suffix));
}

/**
 * True when `path`'s basename is the bare `claude` command in a platform-native executable form:
 * `claude` on any platform, plus the Windows suffixed forms (`claude.exe`/`.cmd`/`.bat`/`.com`).
 * Splits on both `/` and `\` so it matches POSIX fixtures and real Windows paths alike.
 */
export function isClaudeExecutableBasename(path: string): boolean {
  const cut = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  const base = (cut >= 0 ? path.slice(cut + 1) : path).toLowerCase();
  return base === "claude" || WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => base === `claude${suffix}`);
}

export function claudeLauncherBinDir(): string {
  return join(getConfigDir(), "bin");
}

function manifestPath(): string {
  return join(getConfigDir(), MANIFEST_NAME);
}

function realpathMaybe(path: string): string {
  try { return realpathSync.native(path); } catch { return resolve(path); }
}

function isExecutableFile(path: string): boolean {
  if (!existsSync(path)) return false;
  try {
    const real = realpathMaybe(path);
    return existsSync(real);
  } catch {
    return false;
  }
}

/**
 * Shared source of truth: is `path` a frogprogsy Claude launcher of ANY form — a generated shim
 * (carries {@link MANAGED_MARKER}) or a source entrypoint that delegates to `runClaudeLauncherProcess`
 * ({@link LAUNCHER_SOURCE_MARKER}) — regardless of its worktree location or symlink chain? Only a
 * bounded head prefix is read, so a real native Claude binary is never slurped whole. Fails closed:
 * any unexpected read/I/O error is treated as "is a launcher" so a suspect candidate is skipped or
 * rejected rather than trusted. Callers pass the canonical (already realpath-resolved) path.
 */
export function isFrogprogsyClaudeLauncher(path: string): boolean {
  let fd: number | undefined;
  try {
    fd = openSync(path, "r");
    const buffer = Buffer.alloc(LAUNCHER_SNIFF_BYTES);
    const bytesRead = readSync(fd, buffer, 0, LAUNCHER_SNIFF_BYTES, 0);
    const head = buffer.toString("utf8", 0, bytesRead);
    return head.includes(MANAGED_MARKER) || head.includes(LAUNCHER_SOURCE_MARKER);
  } catch {
    return true;
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function currentPackageSrcDir(): string {
  return realpathMaybe(dirname(process.argv[1] ?? "."));
}

function isInside(parent: string, child: string): boolean {
  const p = realpathMaybe(parent);
  const c = realpathMaybe(child);
  return c === p || c.startsWith(`${p}${sep}`);
}

export function findRealClaudeExecutable(extraSkipDirs: string[] = []): string {
  const explicit = process.env.FROGP_REAL_CLAUDE?.trim();
  if (explicit && isExecutableFile(explicit)) return realpathMaybe(explicit);

  const skipDirs = [claudeLauncherBinDir(), currentPackageSrcDir(), ...extraSkipDirs].map(realpathMaybe);
  const candidates = claudeExecutableCandidates();
  const pathEntries = (process.env.PATH ?? "").split(delimiter).filter(Boolean);
  for (const dir of pathEntries) {
    const resolvedDir = realpathMaybe(dir);
    if (resolvedDir.includes("cmux-cli-shims")) continue;
    if (skipDirs.some(skip => resolvedDir === skip || resolvedDir.startsWith(`${skip}${sep}`))) continue;
    // Honor PATHEXT-like suffixes on Windows: probe each candidate name in preference order within
    // this dir before moving on. POSIX has a single candidate (`claude`), so behavior is unchanged.
    for (const name of candidates) {
      const candidate = join(dir, name);
      if (!isExecutableFile(candidate)) continue;
      const real = realpathMaybe(candidate);
      if (real.includes("cmux-cli-shims")) continue;
      if (skipDirs.some(skip => real === skip || real.startsWith(`${skip}${sep}`))) continue;
      if (isFrogprogsyClaudeLauncher(real)) continue;
      return real;
    }
  }
  throw new Error("No safe Claude executable was found outside frogprogsy-managed paths");
}

/**
 * Best-effort variant for diagnostics and shortcut generation: null instead of a throw when no safe
 * original Claude executable exists. Spawn paths must keep using {@link findRealClaudeExecutable} so a
 * missing executable can never degrade into running a bare `claude` a managed shim might intercept.
 */
export function findRealClaudeExecutableOrNull(extraSkipDirs: string[] = []): string | null {
  try {
    return findRealClaudeExecutable(extraSkipDirs);
  } catch {
    return null;
  }
}

/**
 * Validate that `candidate` is a REAL Claude executable safe to spawn. Rejects:
 *  - empty / non-absolute values (e.g. bare `claude`, which a frogprogsy shim on PATH can intercept),
 *  - non-existent paths, directories, and any non-file target,
 *  - zero-byte or non-executable Claude update artifacts (verified with `accessSync(real, X_OK)`),
 *  - anything inside the frogprogsy launcher bin dir or the frogprogsy source dir,
 *  - any frogprogsy launcher — generated shim OR source entrypoint delegating to
 *    `runClaudeLauncherProcess`, in any worktree — detected from a bounded head prefix, including via symlink.
 * Symlinks are resolved to their canonical real target before every check, and that canonical path is
 * returned. Error messages carry only a fixed reason — never the candidate path, a token, or a credential.
 *
 * Lives here rather than in `claude-grants.ts` because every check it performs depends on this module
 * (launcher bin dir, launcher detection, source dir); grants imports it, so the reverse direction would cycle.
 */
export function assertRealClaudeExecutable(candidate: string | undefined): string {
  const raw = (candidate ?? "").trim();
  if (!raw) {
    throw new Error("a real Claude executable is required, got an empty value");
  }
  if (!isAbsolute(raw)) {
    throw new Error('a non-absolute executable is refused; bare "claude" can be intercepted by a frogprogsy shim');
  }
  if (!existsSync(raw)) {
    throw new Error("the Claude executable does not exist");
  }
  // Resolve symlinks up front so every check below runs on the canonical real target: a symlink that
  // points at a managed launcher, the launcher bin dir, or the source dir is rejected by its real path.
  const real = realpathMaybe(raw);
  let stat;
  try {
    stat = statSync(real);
  } catch {
    throw new Error("the Claude executable is not accessible");
  }
  if (!stat.isFile()) {
    throw new Error("the Claude executable is not a file");
  }
  if (stat.size === 0) {
    // A cleared / partially-written Claude self-update artifact reads as a zero-byte file.
    throw new Error("the Claude executable is not executable");
  }

  if (isInside(claudeLauncherBinDir(), real)) {
    throw new Error("the frogprogsy launcher directory is refused as a Claude executable");
  }
  if (isInside(currentPackageSrcDir(), real)) {
    throw new Error("the frogprogsy source directory is refused as a Claude executable");
  }
  // Reject any frogprogsy launcher — a generated shim or a source entrypoint that delegates to
  // `runClaudeLauncherProcess` — via the shared bounded-head detector. Only a prefix is read, so a real
  // native Claude binary is never slurped whole, and it fails closed on unexpected read/I/O errors.
  if (isFrogprogsyClaudeLauncher(real)) {
    throw new Error("a managed frogprogsy launcher is refused as a Claude executable");
  }
  // Windows has no POSIX exec bit, so `accessSync(X_OK)` accepts any readable file — including an
  // extensionless, non-runnable one. The real "is executable" contract there is the PATHEXT-like
  // suffix, so require a recognized executable extension (.exe/.cmd/.bat/.com). POSIX is untouched and
  // keeps exact X_OK semantics. This runs after the launcher/dir/source gates so those keep their
  // specific rejection messages.
  if (process.platform === "win32" && !hasWindowsExecutableSuffix(real)) {
    throw new Error("the Claude executable is not executable");
  }
  // Final gate: the canonical target must actually be executable by this process on this platform.
  try {
    accessSync(real, constants.X_OK);
  } catch {
    throw new Error("the Claude executable is not executable");
  }
  return real;
}

function slugify(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

/**
 * Command-name shape frogprogsy is allowed to own: `claude-<something>`, never bare `claude`.
 *
 * The trailing group is mandatory. frogprogsy never owns the plain `claude` command — that name always
 * belongs to the user's own Claude Code installation.
 */
const SHORTCUT_NAME_PATTERN = /^claude-[a-z0-9][a-z0-9-]*$/;

/**
 * The one stable command name for a profile.
 *
 * Derived from the profile name, which the user chooses and can change with `frogp claude rename`. The
 * home path is deliberately not used: it is a credential address (the Keychain service name hashes it),
 * so it must not move, which makes it a poor source for a renameable command.
 *
 * Falls back to the profile id when the name yields nothing usable. Non-ASCII names slugify to an empty
 * string — `slugify("업무")` is `""` — and an empty suffix would produce bare `claude`, so the fallback
 * is what keeps such profiles nameable at all.
 */
export function claudeProfileShortcutName(profile: ClaudeProfileRecord): string {
  const fromName = slugify(profile.name);
  const candidate = fromName.startsWith("claude-") ? fromName : `claude-${fromName}`;
  if (SHORTCUT_NAME_PATTERN.test(candidate)) return candidate;

  const fromId = slugify(profile.id.replace(/^cp_/, ""));
  const fallback = `claude-${fromId}`;
  return SHORTCUT_NAME_PATTERN.test(fallback) ? fallback : `claude-profile`;
}

function profileLauncherNames(profile: ClaudeProfileRecord, isDefault: boolean): string[] {
  // The default profile uses the user's native `claude` command directly. frogprogsy creates shortcuts
  // only for additional accounts, so there is no redundant `claude-default` command to learn or maintain.
  if (isDefault) return [];

  // Exactly one shortcut per additional profile. Generating a home-basename alias alongside a name alias
  // produced several commands for one account and left the stale one behind after a rename.
  //
  // The filter is the enforcement point, not the proposal sites. `slugify` strips non-ASCII to `-` and
  // then trims it, so a home like `.claude-업무` collapses to exactly `claude` — plain-name ownership
  // could reappear from ordinary user input, no matter how many individual proposals were removed.
  return [claudeProfileShortcutName(profile)].filter(name => SHORTCUT_NAME_PATTERN.test(name));
}

export function plannedClaudeLaunchers(config: FrogConfig): { launchers: ClaudeLauncherEntry[]; warnings: string[] } {
  const profiles = managedClaudeProfiles(config);
  const defaultId = config.claudeProfiles?.defaultProfileId ?? profiles[0]?.id;
  const seen = new Map<string, string>();
  const launchers: ClaudeLauncherEntry[] = [];
  const warnings: string[] = [];

  for (const profile of profiles) {
    for (const name of profileLauncherNames(profile, profile.id === defaultId)) {
      const existing = seen.get(name);
      if (existing && existing !== profile.id) {
        warnings.push(`launcher ${name} skipped for ${profile.name}; already assigned to ${existing}`);
        continue;
      }
      if (existing) continue;
      seen.set(name, profile.id);
      launchers.push({ name, profileId: profile.id, profileName: profile.name, claudeHome: profile.claudeHome });
    }
  }
  launchers.sort((a, b) => a.name.localeCompare(b.name));
  return { launchers, warnings };
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
function cmdQuote(value: string): string {
  return `"${value.replace(/%/g, "%%")}"`;
}

function currentFrogpCommand(): string[] {
  const main = process.argv[1];
  if (main && existsSync(main)) return [process.execPath, realpathMaybe(main)];
  return ["frogp"];
}

function launcherExecLine(frogpCommand: string[], entry: ClaudeLauncherEntry): string {
  const command = [...frogpCommand, "claude", "run", entry.profileId, "--"].map(shQuote).join(" ");
  return `exec ${command} "$@"`;
}

function launcherScript(entry: ClaudeLauncherEntry, realClaude: string, frogpCommand: string[]): string {
  if (process.platform === "win32") {
    const command = [...frogpCommand, "claude", "run", entry.profileId, "--"].map(cmdQuote).join(" ");
    return [
      "@echo off",
      `rem ${MANAGED_MARKER}. Do not edit by hand.`,
      `set "FROGP_REAL_CLAUDE=${realClaude.replace(/%/g, "%%")}"`,
      `${command} %*`,
      "",
    ].join("\r\n");
  }
  return [
    "#!/bin/sh",
    `# ${MANAGED_MARKER}. Do not edit by hand.`,
    `FROGP_REAL_CLAUDE=${shQuote(realClaude)}`,
    "export FROGP_REAL_CLAUDE",
    launcherExecLine(frogpCommand, entry),
    "",
  ].join("\n");
}

function readManifest(): ClaudeLauncherManifest | null {
  try {
    const parsed = JSON.parse(readFileSync(manifestPath(), "utf8"));
    if (parsed?.schemaVersion === 1 && Array.isArray(parsed.launchers)) return parsed as ClaudeLauncherManifest;
  } catch { /* rebuild */ }
  return null;
}
function launcherTargetPaths(binDir: string, name: string): string[] {
  const nativeTarget = join(binDir, claudeLauncherFileName(name));
  if (process.platform !== "win32") return [nativeTarget];
  return [nativeTarget, join(binDir, name)];
}

function managedLauncherMatchesProfile(target: string, profileId: string): boolean {
  try {
    const content = readFileSync(target, "utf8");
    if (!content.includes(MANAGED_MARKER)) return false;
    const invocation = ["claude", "run", profileId, "--"]
      .map(process.platform === "win32" ? cmdQuote : shQuote)
      .join(" ");
    return content.includes(invocation);
  } catch {
    return false;
  }
}

function removeManagedLauncherFile(binDir: string, target: string): boolean {
  if (!isInside(binDir, target) || !existsSync(target)) return false;
  try {
    if (!readFileSync(target, "utf8").includes(MANAGED_MARKER)) return false;
    rmSync(target);
    return true;
  } catch {
    return false;
  }
}

/**
 * Remove marked launchers that do not match the current plan, even when the manifest is missing or
 * corrupt. The file's managed marker — not the manifest — is the deletion authority, so an unmarked
 * user file with the same name is preserved. A same-name managed launcher is retained only when its
 * embedded profile id matches the current owner. This also removes legacy non-plain aliases after the
 * one-shortcut-per-profile migration and the platform's old extensionless Windows form.
 */
function removeOrphanManagedLaunchers(binDir: string, nextLaunchersByName: ReadonlyMap<string, ClaudeLauncherEntry>): string[] {
  let entries: string[];
  try {
    entries = readdirSync(binDir);
  } catch {
    return [];
  }

  const removed = new Set<string>();
  for (const fileName of entries) {
    const logicalName = process.platform === "win32" && fileName.endsWith(".cmd")
      ? fileName.slice(0, -4)
      : fileName;
    if (!(logicalName === "claude" || /^claude-[a-z0-9][a-z0-9-]*$/.test(logicalName))) continue;
    const next = nextLaunchersByName.get(logicalName);
    const nativeFileName = claudeLauncherFileName(logicalName);
    if (next && fileName === nativeFileName && managedLauncherMatchesProfile(join(binDir, fileName), next.profileId)) continue;
    if (removeManagedLauncherFile(binDir, join(binDir, fileName))) removed.add(logicalName);
  }
  return [...removed];
}

export function syncClaudeLauncherShims(config: FrogConfig, options: { realClaude?: string; frogpCommand?: string[] } = {}): ClaudeLauncherSyncResult {
  const configDir = ensureConfigDirForWrite("sync Claude launcher shims");
  const binDir = join(configDir, "bin");
  mkdirSync(binDir, { recursive: true, mode: 0o700 });
  try { chmodSync(binDir, 0o700); } catch { /* best effort */ }

  const realClaude = options.realClaude ?? findRealClaudeExecutableOrNull([binDir]);
  const frogpCommand = options.frogpCommand ?? currentFrogpCommand();
  const { launchers, warnings } = plannedClaudeLaunchers(config);

  const previous = readManifest();
  const nextLaunchersByName = new Map(launchers.map(entry => [entry.name, entry]));
  const removed: string[] = [];

  for (const old of previous?.launchers ?? []) {
    if (nextLaunchersByName.get(old.name)?.profileId === old.profileId) {
      if (process.platform === "win32") removeManagedLauncherFile(binDir, join(binDir, old.name));
      continue;
    }
    let didRemove = false;
    for (const target of launcherTargetPaths(binDir, old.name)) {
      didRemove = removeManagedLauncherFile(binDir, target) || didRemove;
    }
    if (didRemove) removed.push(old.name);
  }

  // The manifest may be absent or corrupt. Scan the owned directory as a second source and remove only
  // marked files that do not belong to the current name/profile pair; unmarked user files are never touched.
  for (const orphan of removeOrphanManagedLaunchers(binDir, nextLaunchersByName)) {
    if (!removed.includes(orphan)) removed.push(orphan);
  }

  // A shortcut can only be generated around a validated original Claude executable. When none exists
  // this is reported instead of thrown: the caller has usually already registered an account, and
  // failing the whole operation would strand it. Removal already ran above — it never needs the
  // executable — so deleted and renamed accounts still lose their stale shortcuts, and the manifest is
  // rewritten with the launchers that survived on disk.
  if (!realClaude) {
    const surviving = launchers.filter(entry =>
      managedLauncherMatchesProfile(join(binDir, claudeLauncherFileName(entry.name)), entry.profileId));
    const manifest: ClaudeLauncherManifest = {
      schemaVersion: 1,
      generatedAt: new Date().toISOString(),
      binDir,
      realClaude: previous?.realClaude ?? "claude",
      frogpCommand: previous?.frogpCommand ?? frogpCommand,
      launchers: surviving,
    };
    atomicWriteFile(manifestPath(), JSON.stringify(manifest, null, 2) + "\n");
    return {
      binDir,
      realClaude: "claude",
      realClaudeResolved: false,
      frogpCommand,
      launchers: surviving,
      removed,
      warnings: [...warnings, REAL_CLAUDE_UNRESOLVED_WARNING],
    };
  }

  for (const entry of launchers) {
    const target = join(binDir, claudeLauncherFileName(entry.name));
    atomicWriteFile(target, launcherScript(entry, realClaude, frogpCommand));
    if (process.platform !== "win32") chmodSync(target, 0o755);
    if (process.platform === "win32") removeManagedLauncherFile(binDir, join(binDir, entry.name));
  }

  const manifest: ClaudeLauncherManifest = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    binDir,
    realClaude,
    frogpCommand,
    launchers,
  };
  atomicWriteFile(manifestPath(), JSON.stringify(manifest, null, 2) + "\n");
  return { binDir, realClaude, realClaudeResolved: true, frogpCommand, launchers, removed, warnings };
}

/**
 * Best-effort sync outcome reported by the management API. `shortcutProfileIds` lists the profiles that
 * actually own a generated shortcut, so a caller never has to infer that from `success` alone.
 */
export interface ClaudeLauncherSyncSummary {
  success: boolean;
  error?: string;
  realClaudeResolved?: boolean;
  warnings?: string[];
  shortcutProfileIds?: string[];
}

export const REAL_CLAUDE_UNRESOLVED_WARNING =
  "the original Claude Code executable was not found, so no account shortcut was generated; install Claude Code and run frogp refresh";

export function removeClaudeLauncherShims(): { binDir: string; removed: string[] } {
  const binDir = claudeLauncherBinDir();
  const previous = readManifest();
  const removed: string[] = [];
  for (const old of previous?.launchers ?? []) {
    let didRemove = false;
    for (const target of launcherTargetPaths(binDir, old.name)) {
      didRemove = removeManagedLauncherFile(binDir, target) || didRemove;
    }
    if (didRemove) removed.push(old.name);
  }
  const manifest = manifestPath();
  if (existsSync(manifest)) {
    try { rmSync(manifest); } catch { /* best effort */ }
  }
  return { binDir, removed };
}

function gatewayProcessActive(): boolean {
  return readPid() !== null && readActivePort() !== null;
}

type RefreshManagedCatalog = typeof import("./claude-refresh").refreshClaudeCodeModelCatalog;

/**
 * Pre-warm a managed profile's Claude Code picker cache inside that profile's own home BEFORE the
 * managed gateway Claude launches, so the picker reads a fresh catalog. Best-effort: a transient
 * refresh error never blocks the launch. The last-known-good cache policy lives entirely in the
 * refresh module; the warning here is intentionally free of tokens, paths, or other sensitive detail.
 */
async function refreshManagedProfileCatalog(
  config: FrogConfig,
  profile: ClaudeProfileRecord,
  refreshCatalog?: RefreshManagedCatalog,
): Promise<void> {
  try {
    const refresh = refreshCatalog ?? (await import("./claude-refresh")).refreshClaudeCodeModelCatalog;
    const result = await refresh(config, undefined, { claudeHome: profile.claudeHome, profileId: profile.id });
    if (result.gatewayCache.status === "failed" || result.warnings.length > 0) {
      console.warn(`frogprogsy: Claude model picker cache refresh reported a warning for profile ${profile.id}; continuing with the last known-good catalog when available.`);
    }
  } catch {
    console.warn(`frogprogsy: Claude model picker cache refresh failed for profile ${profile.id}; continuing with the last known-good catalog when available.`);
  }
}

const LAUNCHER_SPAWN_FAILURE_MESSAGE = "frogprogsy: failed to launch the Claude executable.";

/**
 * Map a spawnSync result to a launcher exit code, failing closed. A spawn that never started
 * (`result.error`, e.g. ENOENT/EACCES) or was terminated by a signal without a concrete status
 * MUST NOT surface as exit 0; a concrete numeric status (including 0) is preserved verbatim.
 * A missing executable (ENOENT) maps to the shell "command not found" code 127; any other spawn
 * error maps to 1. The failure diagnostic is fixed and redacted — it carries no path, argv, or
 * raw error body.
 */
function launcherResultExitCode(result: Pick<ReturnType<typeof spawnSync>, "status" | "signal" | "error">): number {
  if (result.error) {
    console.error(LAUNCHER_SPAWN_FAILURE_MESSAGE);
    return (result.error as NodeJS.ErrnoException).code === "ENOENT" ? 127 : 1;
  }
  if (typeof result.status === "number") return result.status;
  return 1;
}

export interface RunClaudeProfileOptions {
  realClaude?: string;
  gateway?: boolean;
  refreshCatalog?: RefreshManagedCatalog;
  spawn?: typeof spawnSync;
  exit?: (code: number) => never;
  /** Environment consulted for a conflicting account home. Injectable for tests; defaults to `process.env`. */
  env?: NodeJS.ProcessEnv;
  /** Real-executable validator seam for spawn error tests; production always uses the strict validator. */
  validateExecutable?: (candidate: string | undefined) => string;
}

/** Fixed exit code for a refused launch whose caller environment names a different account home. */
export const CLAUDE_HOME_CONFLICT_EXIT_CODE = 78;

export interface ClaudeHomeConflict {
  /** Which environment variable disagreed, or `both` when the two disagree with each other. */
  source: "CLAUDE_CONFIG_DIR" | "CLAUDE_HOME" | "both";
  reason: "different-home" | "unreadable" | "registered-unreadable";
}

/**
 * Compare the caller-supplied account home against the profile's registered home.
 *
 * Returns `null` when the launch may proceed: nothing set, or every set value canonically names the
 * same directory. Otherwise returns the conflict to refuse on.
 *
 * Refusing rather than warning is deliberate. A warning still lets Claude Code write credentials into
 * the wrong scoped store — the Keychain service name derives from the home path — which is exactly the
 * Probe-B damage recorded in `structure/09_claude-dual-auth.md`. Recovery required a human re-login.
 *
 * Missing paths, non-directories, and unreadable paths are fail-closed: an unresolvable value cannot be
 * proven equal to the registered home, so it is treated as a conflict rather than ignored.
 */
export function detectClaudeHomeConflict(
  registeredHome: string,
  env: NodeJS.ProcessEnv = process.env,
): ClaudeHomeConflict | null {
  const configDir = env.CLAUDE_CONFIG_DIR?.trim();
  const claudeHome = env.CLAUDE_HOME?.trim();

  // The registered home is the source of truth. It is never rewritten by this comparison: the spawn
  // below uses `profile.claudeHome` verbatim, because that exact string is the credential address.
  const registered = canonicalDirIdentity(registeredHome);
  if (registered === null) {
    return { source: configDir ? "CLAUDE_CONFIG_DIR" : claudeHome ? "CLAUDE_HOME" : "both", reason: "registered-unreadable" };
  }
  if (!configDir && !claudeHome) return null;

  const entries: Array<{ source: "CLAUDE_CONFIG_DIR" | "CLAUDE_HOME"; raw: string }> = [];
  if (configDir) entries.push({ source: "CLAUDE_CONFIG_DIR", raw: configDir });
  if (claudeHome) entries.push({ source: "CLAUDE_HOME", raw: claudeHome });

  const identities: string[] = [];
  for (const entry of entries) {
    const identity = canonicalDirIdentity(entry.raw);
    if (identity === null) return { source: entry.source, reason: "unreadable" };
    if (registered !== null && identity !== registered) {
      return { source: entry.source, reason: "different-home" };
    }
    identities.push(identity);
  }

  // Both set but pointing at different directories: refuse even if neither matched the registered home
  // path textually (e.g. the registered home itself could not be resolved).
  if (identities.length === 2 && identities[0] !== identities[1]) {
    return { source: "both", reason: "different-home" };
  }
  return null;
}

/** Canonical identity of an existing directory, or `null` when it is missing, not a directory, or unreadable. */
function canonicalDirIdentity(path: string): string | null {
  try {
    const resolved = resolve(expandTildePath(path));
    const stat = statSync(resolved);
    if (!stat.isDirectory()) return null;
    return realpathSync.native(resolved);
  } catch {
    return null;
  }
}

function expandTildePath(path: string): string {
  if (path === "~") return homedir();
  if (path.startsWith(`~${sep}`) || path.startsWith("~/")) return join(homedir(), path.slice(2));
  return path;
}

/**
 * User-facing refusal text. Names the shortcut and the fixing command; never prints a full home path.
 * Privacy-safe paths belong to `frogp doctor claude`, not to this default message.
 */
export function claudeHomeConflictMessage(conflict: ClaudeHomeConflict, shortcutName: string): string {
  if (conflict.reason === "registered-unreadable") {
    return [
      `Refusing to start: the registered Claude account home for ${shortcutName} is missing or cannot be read.`,
      "Running anyway could write credentials to an unintended location.",
      `Fix: restore that account home or remove and add the ${shortcutName} account again.`,
    ].join("\n");
  }
  const varLabel = conflict.source === "both" ? "CLAUDE_CONFIG_DIR and CLAUDE_HOME" : conflict.source;
  const cause = conflict.reason === "unreadable"
    ? `${varLabel} names a directory that cannot be read.`
    : `${varLabel} names a different Claude account than ${shortcutName} uses.`;
  return [
    `Refusing to start: ${cause}`,
    "Running anyway could sign this account into the wrong Claude home.",
    `Fix: unset that variable and run ${shortcutName} again, or run your own claude command directly.`,
  ].join("\n");
}

export async function runClaudeProfile(
  profile: ClaudeProfileRecord,
  config: FrogConfig,
  claudeArgs: string[],
  options: RunClaudeProfileOptions = {},
): Promise<never> {
  const exit = options.exit ?? ((code: number) => process.exit(code));

  // Single convergence point for every managed launch: a generated shortcut runs
  // `frogp claude run <id> --`, and `frogp claude run` is invoked directly. Both land here. The check
  // runs before catalog prewrite, environment assembly, and spawn, so a refusal writes nothing.
  const conflict = detectClaudeHomeConflict(profile.claudeHome, options.env ?? process.env);
  if (conflict) {
    const command = profile.id === config.claudeProfiles?.defaultProfileId ? "claude" : claudeProfileShortcutName(profile);
    console.error(claudeHomeConflictMessage(conflict, command));
    return exit(CLAUDE_HOME_CONFLICT_EXIT_CODE);
  }

  // Validate whichever executable we are about to spawn — the explicit `FROGP_REAL_CLAUDE` a generated
  // shortcut passes through the CLI, or the resolver's pick. Validating only inside the resolver would
  // skip the shortcut path entirely, since an explicit value short-circuits it.
  const validateExecutable = options.validateExecutable ?? assertRealClaudeExecutable;
  const realClaude = validateExecutable(options.realClaude ?? findRealClaudeExecutable());
  const useGateway = options.gateway ?? gatewayProcessActive();
  const spawn = options.spawn ?? spawnSync;
  let env: NodeJS.ProcessEnv;
  if (useGateway) {
    // Sync this profile's picker cache before the real Claude process starts, then launch.
    await refreshManagedProfileCatalog(config, profile, options.refreshCatalog);
    const carrier = config.gatewayAuthCarrier ?? "token-free";
    env = buildClaudeProfileRunEnv(profile, readActivePort() ?? config.port ?? DEFAULT_PORT, carrier);
  } else {
    env = buildClaudeProfileNativeEnv(profile);
  }
  const result = spawn(realClaude, claudeArgs, { stdio: "inherit", env });
  return exit(launcherResultExitCode(result));
}

export function runNativeClaude(
  claudeArgs: string[],
  options: { realClaude?: string; spawn?: typeof spawnSync; exit?: (code: number) => never } = {},
): never {
  const realClaude = options.realClaude ?? findRealClaudeExecutable();
  const spawn = options.spawn ?? spawnSync;
  const exit = options.exit ?? ((code: number) => process.exit(code));
  const result = spawn(realClaude, claudeArgs, { stdio: "inherit", env: process.env });
  return exit(launcherResultExitCode(result));
}

export function profileForLauncherName(config: FrogConfig, launcherName: string): ClaudeProfileRecord {
  const { launchers } = plannedClaudeLaunchers(config);
  const matched = launchers.find(entry => entry.name === launcherName);
  return resolveClaudeProfile(config, matched?.profileId ?? launcherName.replace(/^claude-/, ""));
}

