import { createHash, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { accessSync, chmodSync, closeSync, constants, existsSync, fchmodSync, fstatSync, fsyncSync, ftruncateSync, linkSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync, readlinkSync, readSync, realpathSync, renameSync, rmSync, rmdirSync, statSync, symlinkSync, unlinkSync, writeFileSync, writeSync } from "node:fs";
import { homedir } from "node:os";
import { basename, delimiter, dirname, isAbsolute, join, resolve, sep } from "node:path";
import { DEFAULT_PORT, atomicWriteFile, ensureConfigDirForWrite, getConfigDir, getConfigPath, loadConfig, readActivePort, readLocalAccessToken, readPid } from "./config";
import { buildClaudeProfileNativeEnv, buildClaudeProfileRunEnv, ensureClaudeProfiles, managedClaudeProfiles, resolveClaudeProfile } from "./claude-profiles";
import type { ClaudeProfileRecord, FrogConfig } from "./types";

export interface ClaudeLauncherEntry {
  name: string;
  profileId: string;
  profileName: string;
  claudeHome: string;
}

export interface ClaudeLauncherSyncResult {
  binDir: string;
  realClaude: string;
  /** False when no safe original Claude executable exists, so shortcut generation was skipped. */
  realClaudeResolved: boolean;
  launchers: ClaudeLauncherEntry[];
  removed: string[];
  warnings: string[];
  frogpCommand: string[];
}

interface ClaudeLauncherManifest {
  schemaVersion: 1;
  generatedAt: string;
  binDir: string;
  realClaude: string;
  launchers: ClaudeLauncherEntry[];
  frogpCommand?: string[];
}

const MANIFEST_NAME = "claude-launchers.json";
const MANAGED_MARKER = "Generated by frogprogsy";
/**
 * Substring emitted by a source-form frogprogsy launcher: any `.ts` entrypoint that delegates to
 * `runClaudeLauncherProcess` is a legacy launcher even without the generated marker (for example, an
 * older installed package's removed plain-Claude entrypoint). Kept for stale-install detection.
 */
const LAUNCHER_SOURCE_MARKER = "runClaudeLauncherProcess";
/**
 * Bytes sniffed from a candidate's head. Bounded so a multi-hundred-MB native Claude binary is never
 * read in full, while still large enough to capture any launcher's shebang, generated marker, or
 * delegation call which always appear at the very top of the file.
 */
const LAUNCHER_SNIFF_BYTES = 64 * 1024;

/**
 * Windows executable suffixes supported when resolving a bare command like `claude` from PATH.
 * The deterministic order covers the forms Claude installations actually ship as: `.exe` for a
 * native binary and `.cmd`/`.bat`/`.com` for npm/npx-style shims. It intentionally does not depend
 * on machine-specific PATHEXT ordering and is consulted only on win32, leaving POSIX unchanged.
 */
export const WINDOWS_EXECUTABLE_SUFFIXES = [".exe", ".cmd", ".bat", ".com"] as const;

/**
 * On-disk file names to probe, in PATH-order preference, for a base command such as `claude`.
 * POSIX: exactly the bare name (exact behavior preserved). Windows: the PATHEXT-like suffixed forms,
 * unless `base` already carries a recognized suffix (then it is used verbatim).
 */
export function claudeExecutableCandidates(base = "claude"): string[] {
  if (process.platform !== "win32") return [base];
  const lower = base.toLowerCase();
  if (WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => lower.endsWith(suffix))) return [base];
  return WINDOWS_EXECUTABLE_SUFFIXES.map(suffix => `${base}${suffix}`);
}
/** Platform-native filename for a generated managed launcher alias. */
export function claudeLauncherFileName(name: string): string {
  return process.platform === "win32" ? `${name}.cmd` : name;
}

/** True when `path` ends with a Windows executable suffix (PATHEXT-like). Case-insensitive. */
export function hasWindowsExecutableSuffix(path: string): boolean {
  const lower = path.toLowerCase();
  return WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => lower.endsWith(suffix));
}

/**
 * True when `path`'s basename is the bare `claude` command in a platform-native executable form:
 * `claude` on any platform, plus the Windows suffixed forms (`claude.exe`/`.cmd`/`.bat`/`.com`).
 * Splits on both `/` and `\` so it matches POSIX fixtures and real Windows paths alike.
 */
export function isClaudeExecutableBasename(path: string): boolean {
  const cut = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  const base = (cut >= 0 ? path.slice(cut + 1) : path).toLowerCase();
  return base === "claude" || WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => base === `claude${suffix}`);
}

export function claudeLauncherBinDir(): string {
  return join(getConfigDir(), "bin");
}

function manifestPath(): string {
  return join(getConfigDir(), MANIFEST_NAME);
}

function realpathMaybe(path: string): string {
  try { return realpathSync.native(path); } catch { return resolve(path); }
}

function isExecutableFile(path: string): boolean {
  if (!existsSync(path)) return false;
  try {
    const real = realpathMaybe(path);
    return existsSync(real);
  } catch {
    return false;
  }
}

/**
 * Shared source of truth: is `path` a frogprogsy Claude launcher of ANY form — a generated shim
 * (carries {@link MANAGED_MARKER}) or a source entrypoint that delegates to `runClaudeLauncherProcess`
 * ({@link LAUNCHER_SOURCE_MARKER}) — regardless of its worktree location or symlink chain? Only a
 * bounded head prefix is read, so a real native Claude binary is never slurped whole. Fails closed:
 * any unexpected read/I/O error is treated as "is a launcher" so a suspect candidate is skipped or
 * rejected rather than trusted. Callers pass the canonical (already realpath-resolved) path.
 */
export function isFrogprogsyClaudeLauncher(path: string): boolean {
  let fd: number | undefined;
  try {
    fd = openSync(path, "r");
    const buffer = Buffer.alloc(LAUNCHER_SNIFF_BYTES);
    const bytesRead = readSync(fd, buffer, 0, LAUNCHER_SNIFF_BYTES, 0);
    const head = buffer.toString("utf8", 0, bytesRead);
    return head.includes(MANAGED_MARKER) || head.includes(LAUNCHER_SOURCE_MARKER);
  } catch {
    return true;
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function currentPackageSrcDir(): string {
  return realpathMaybe(dirname(process.argv[1] ?? "."));
}

function isInside(parent: string, child: string): boolean {
  const p = realpathMaybe(parent);
  const c = realpathMaybe(child);
  return c === p || c.startsWith(`${p}${sep}`);
}

export function findRealClaudeExecutable(extraSkipDirs: string[] = []): string {
  const explicit = process.env.FROGP_REAL_CLAUDE?.trim();
  if (explicit && isExecutableFile(explicit)) return realpathMaybe(explicit);

  const skipDirs = [claudeLauncherBinDir(), currentPackageSrcDir(), ...extraSkipDirs].map(realpathMaybe);
  const candidates = claudeExecutableCandidates();
  const pathEntries = (process.env.PATH ?? "").split(delimiter).filter(Boolean);
  for (const dir of pathEntries) {
    const resolvedDir = realpathMaybe(dir);
    if (resolvedDir.includes("cmux-cli-shims")) continue;
    if (skipDirs.some(skip => resolvedDir === skip || resolvedDir.startsWith(`${skip}${sep}`))) continue;
    // Honor PATHEXT-like suffixes on Windows: probe each candidate name in preference order within
    // this dir before moving on. POSIX has a single candidate (`claude`), so behavior is unchanged.
    for (const name of candidates) {
      const candidate = join(dir, name);
      if (!isExecutableFile(candidate)) continue;
      const real = realpathMaybe(candidate);
      if (real.includes("cmux-cli-shims")) continue;
      if (skipDirs.some(skip => real === skip || real.startsWith(`${skip}${sep}`))) continue;
      if (isFrogprogsyClaudeLauncher(real)) continue;
      return real;
    }
  }
  throw new Error("No safe Claude executable was found outside frogprogsy-managed paths");
}

/**
 * Best-effort variant for cleanup and shortcut generation. Spawn paths keep using the throwing
 * resolver so a missing executable can never degrade into an interceptable bare `claude`.
 */
export function findRealClaudeExecutableOrNull(extraSkipDirs: string[] = []): string | null {
  try {
    return findRealClaudeExecutable(extraSkipDirs);
  } catch {
    return null;
  }
}

/**
 * Validate that `candidate` is a REAL Claude executable safe to spawn. Rejects:
 *  - empty / non-absolute values (e.g. bare `claude`, which a frogprogsy shim on PATH can intercept),
 *  - non-existent paths, directories, and any non-file target,
 *  - zero-byte or non-executable Claude update artifacts (verified with `accessSync(real, X_OK)`),
 *  - anything inside the frogprogsy launcher bin dir or the frogprogsy source dir,
 *  - any frogprogsy launcher — generated shim OR source entrypoint delegating to
 *    `runClaudeLauncherProcess`, in any worktree — detected from a bounded head prefix, including via symlink.
 * Symlinks are resolved to their canonical real target before every check, and that canonical path is
 * returned. Error messages carry only a fixed reason — never the candidate path, a token, or a credential.
 *
 * Lives here rather than in `claude-grants.ts` because every check it performs depends on this module
 * (launcher bin dir, launcher detection, source dir); grants imports it, so the reverse direction would cycle.
 */
export function assertRealClaudeExecutable(candidate: string | undefined): string {
  const raw = (candidate ?? "").trim();
  if (!raw) {
    throw new Error("a real Claude executable is required, got an empty value");
  }
  if (!isAbsolute(raw)) {
    throw new Error('a non-absolute executable is refused; bare "claude" can be intercepted by a frogprogsy shim');
  }
  if (!existsSync(raw)) {
    throw new Error("the Claude executable does not exist");
  }
  // Resolve symlinks up front so every check below runs on the canonical real target: a symlink that
  // points at a managed launcher, the launcher bin dir, or the source dir is rejected by its real path.
  const real = realpathMaybe(raw);
  let stat;
  try {
    stat = statSync(real);
  } catch {
    throw new Error("the Claude executable is not accessible");
  }
  if (!stat.isFile()) {
    throw new Error("the Claude executable is not a file");
  }
  if (stat.size === 0) {
    // A cleared / partially-written Claude self-update artifact reads as a zero-byte file.
    throw new Error("the Claude executable is not executable");
  }

  if (isInside(claudeLauncherBinDir(), real)) {
    throw new Error("the frogprogsy launcher directory is refused as a Claude executable");
  }
  if (isInside(currentPackageSrcDir(), real)) {
    throw new Error("the frogprogsy source directory is refused as a Claude executable");
  }
  // Reject any frogprogsy launcher — a generated shim or a source entrypoint that delegates to
  // `runClaudeLauncherProcess` — via the shared bounded-head detector. Only a prefix is read, so a real
  // native Claude binary is never slurped whole, and it fails closed on unexpected read/I/O errors.
  if (isFrogprogsyClaudeLauncher(real)) {
    throw new Error("a managed frogprogsy launcher is refused as a Claude executable");
  }
  // Windows has no POSIX exec bit, so `accessSync(X_OK)` accepts any readable file — including an
  // extensionless, non-runnable one. The real "is executable" contract there is the PATHEXT-like
  // suffix, so require a recognized executable extension (.exe/.cmd/.bat/.com). POSIX is untouched and
  // keeps exact X_OK semantics. This runs after the launcher/dir/source gates so those keep their
  // specific rejection messages.
  if (process.platform === "win32" && !hasWindowsExecutableSuffix(real)) {
    throw new Error("the Claude executable is not executable");
  }
  // Final gate: the canonical target must actually be executable by this process on this platform.
  try {
    accessSync(real, constants.X_OK);
  } catch {
    throw new Error("the Claude executable is not executable");
  }
  return real;
}

function slugify(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

/**
 * Command-name shape frogprogsy is allowed to own: `claude-<something>`, never bare `claude`.
 *
 * The trailing group is mandatory. frogprogsy never owns the plain `claude` command — that name always
 * belongs to the user's own Claude Code installation.
 */
const SHORTCUT_NAME_PATTERN = /^claude-[a-z0-9][a-z0-9-]*$/;

/**
 * The one stable command name for a profile.
 *
 * Derived from the profile name, which the user chooses and can change with `frogp claude rename`. The
 * home path is deliberately not used: it is a credential address (the Keychain service name hashes it),
 * so it must not move, which makes it a poor source for a renameable command.
 *
 * Falls back to the profile id when the name yields nothing usable. Non-ASCII names slugify to an empty
 * string — `slugify("업무")` is `""` — and an empty suffix would produce bare `claude`, so the fallback
 * is what keeps such profiles nameable at all.
 */
export function claudeProfileShortcutName(profile: ClaudeProfileRecord): string {
  const fromName = slugify(profile.name);
  const candidate = fromName.startsWith("claude-") ? fromName : `claude-${fromName}`;
  if (SHORTCUT_NAME_PATTERN.test(candidate)) return candidate;

  const fromId = slugify(profile.id.replace(/^cp_/, ""));
  const fallback = `claude-${fromId}`;
  return SHORTCUT_NAME_PATTERN.test(fallback) ? fallback : `claude-profile`;
}

function profileLauncherNames(profile: ClaudeProfileRecord, isDefault: boolean): string[] {
  // The default profile uses the user's native `claude` command directly. frogprogsy creates shortcuts
  // only for additional accounts, so there is no redundant `claude-default` command to learn or maintain.
  if (isDefault) return [];

  // Exactly one shortcut per additional profile. Generating a home-basename alias alongside a name alias
  // produced several commands for one account and left the stale one behind after a rename.
  //
  // The filter is the enforcement point, not the proposal sites. `slugify` strips non-ASCII to `-` and
  // then trims it, so a home like `.claude-업무` collapses to exactly `claude` — plain-name ownership
  // could reappear from ordinary user input, no matter how many individual proposals were removed.
  return [claudeProfileShortcutName(profile)].filter(name => SHORTCUT_NAME_PATTERN.test(name));
}

export function plannedClaudeLaunchers(config: FrogConfig): { launchers: ClaudeLauncherEntry[]; warnings: string[] } {
  const profiles = managedClaudeProfiles(config);
  const defaultId = config.claudeProfiles?.defaultProfileId ?? profiles[0]?.id;
  const seen = new Map<string, string>();
  const launchers: ClaudeLauncherEntry[] = [];
  const warnings: string[] = [];

  for (const profile of profiles) {
    for (const name of profileLauncherNames(profile, profile.id === defaultId)) {
      const existing = seen.get(name);
      if (existing && existing !== profile.id) {
        warnings.push(`launcher ${name} skipped for ${profile.name}; already assigned to ${existing}`);
        continue;
      }
      if (existing) continue;
      seen.set(name, profile.id);
      launchers.push({ name, profileId: profile.id, profileName: profile.name, claudeHome: profile.claudeHome });
    }
  }
  launchers.sort((a, b) => a.name.localeCompare(b.name));
  return { launchers, warnings };
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
function cmdQuote(value: string): string {
  return `"${value.replace(/%/g, "%%")}"`;
}

function currentFrogpCommand(): string[] {
  const main = process.argv[1];
  if (main && existsSync(main)) return [process.execPath, realpathMaybe(main)];
  return ["frogp"];
}

function launcherExecLine(frogpCommand: string[], entry: ClaudeLauncherEntry): string {
  const command = [...frogpCommand, "claude", "run", entry.profileId, "--"].map(shQuote).join(" ");
  return `exec ${command} "$@"`;
}

function launcherScript(entry: ClaudeLauncherEntry, realClaude: string, frogpCommand: string[]): string {
  if (process.platform === "win32") {
    const command = [...frogpCommand, "claude", "run", entry.profileId, "--"].map(cmdQuote).join(" ");
    return [
      "@echo off",
      `rem ${MANAGED_MARKER}. Do not edit by hand.`,
      `set "FROGP_REAL_CLAUDE=${realClaude.replace(/%/g, "%%")}"`,
      `${command} %*`,
      "",
    ].join("\r\n");
  }
  return [
    "#!/bin/sh",
    `# ${MANAGED_MARKER}. Do not edit by hand.`,
    `FROGP_REAL_CLAUDE=${shQuote(realClaude)}`,
    "export FROGP_REAL_CLAUDE",
    launcherExecLine(frogpCommand, entry),
    "",
  ].join("\n");
}


type LauncherWriteChunk = (
  fd: number,
  buffer: Uint8Array,
  offset: number,
  length: number,
  position: number,
) => number;

type LauncherReadChunk = LauncherWriteChunk;

interface ClaudeLauncherSyncOptions {
  realClaude?: string;
  frogpCommand?: string[];
  /** Test seam after ownership classification and immediately before publishing a launcher. */
  beforePublish?: (target: string, entry: ClaudeLauncherEntry) => void;
  /** Low-level managed-target read seam for deterministic short-read tests. */
  readManagedLauncherChunk?: LauncherReadChunk;
  /** Low-level existing-managed-target write seam for deterministic partial-write failure tests. */
  writeManagedLauncherChunk?: LauncherWriteChunk;
  /** Test seam after a durable removal journal exists and immediately before its target is captured. */
  beforeManagedRemove?: (target: string) => void;
  /** Test seam after capture, used to exercise start-of-sync crash recovery. */
  afterManagedRemoveCapture?: (target: string) => void;
  /** Test seam after a foreign capture is restored and before recovery cleanup. */
  afterForeignRestore?: (target: string, capture: string) => void;
  /** Test seam after capture but before directory durability is checked. */
  beforeManagedRemoveDurability?: (target: string) => void;
  /** Directory-fsync dependency seam for failure-path regression tests. */
  fsyncDirectory?: (path: string) => boolean;
}

interface ManagedTargetIdentity {
  kind: "managed";
  dev: number;
  ino: number;
  content: string;
  size: number;
  sha256: string;
  recoverySuffixPresent: boolean;
}

type LauncherTargetOwnership =
  | { kind: "absent" }
  | ManagedTargetIdentity
  | { kind: "unsafe-managed" }
  | { kind: "unsafe-managed-size" }
  | { kind: "foreign" };

interface LauncherRemovalManifest {
  schemaVersion: 1 | 2;
  phase: "capture-pending";
  targetName: string;
  expected?: {
    dev: number;
    ino: number;
    size: number;
    sha256: string;
  };
}

const LAUNCHER_RECOVERY_DIR = ".frogprogsy-launcher-recovery";
const LAUNCHER_RECOVERY_MANIFEST = "manifest.json";
const LAUNCHER_RECOVERY_CAPTURE = "captured";
const LAUNCHER_RECOVERY_OWNER = "owner";
const LAUNCHER_RECOVERY_OWNER_BYTES = "Generated by frogprogsy launcher recovery\n";
const LAUNCHER_RECOVERY_COPY_BUFFER_BYTES = 64 * 1024;
const MAX_MANAGED_LAUNCHER_BYTES = 1024 * 1024;
const MANAGED_WRITE_RECOVERY_SUFFIX = process.platform === "win32"
  ? `\r\nrem frogprogsy durable recovery ---------------------------------------------------------------- ${MANAGED_MARKER}\r\n`
  : `\n# frogprogsy durable recovery ---------------------------------------------------------------- ${MANAGED_MARKER}\n`;
const MANAGED_WRITE_RECOVERY_BYTES = Buffer.from(MANAGED_WRITE_RECOVERY_SUFFIX, "utf8");

function fsErrorCode(error: unknown): string | undefined {
  if (!error || typeof error !== "object" || !("code" in error)) return undefined;
  return typeof error.code === "string" ? error.code : undefined;
}

function readLauncherFdBuffer(
  fd: number,
  limit = LAUNCHER_SNIFF_BYTES,
  readChunk: LauncherReadChunk = readSync,
): Buffer {
  const size = Math.min(fstatSync(fd).size, limit);
  const buffer = Buffer.alloc(size);
  let offset = 0;
  while (offset < size) {
    const bytesRead = readChunk(fd, buffer, offset, size - offset, offset);
    if (!Number.isInteger(bytesRead) || bytesRead < 0 || bytesRead > size - offset) {
      throw new Error("managed launcher read made invalid progress");
    }
    if (bytesRead === 0) break;
    offset += bytesRead;
  }
  return offset === size ? buffer : buffer.subarray(0, offset);
}

function readLauncherFd(
  fd: number,
  limit = LAUNCHER_SNIFF_BYTES,
  readChunk: LauncherReadChunk = readSync,
): string {
  return readLauncherFdBuffer(fd, limit, readChunk).toString("utf8");
}

function classifyLauncherTarget(
  target: string,
  readChunk: LauncherReadChunk = readSync,
): LauncherTargetOwnership {
  let fd: number | undefined;
  try {
    const pathStat = lstatSync(target);
    if (pathStat.isSymbolicLink() || !pathStat.isFile()) return { kind: "foreign" };
    fd = openSync(target, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
    const opened = fstatSync(fd);
    if (!opened.isFile()
      || opened.dev !== pathStat.dev
      || opened.ino !== pathStat.ino) return { kind: "foreign" };
    const head = readLauncherFd(fd, LAUNCHER_SNIFF_BYTES, readChunk);
    if (opened.size > MAX_MANAGED_LAUNCHER_BYTES) {
      if (!head.includes(MANAGED_MARKER)) return { kind: "foreign" };
      if (opened.nlink !== 1) return { kind: "unsafe-managed" };
      return { kind: "unsafe-managed-size" };
    }
    const contentBytes = readLauncherFdBuffer(fd, opened.size + 1, readChunk);
    if (contentBytes.length !== opened.size) return { kind: "foreign" };
    const content = contentBytes.toString("utf8");
    const recoverySuffixPresent = contentBytes.length >= MANAGED_WRITE_RECOVERY_BYTES.length
      && contentBytes.subarray(-MANAGED_WRITE_RECOVERY_BYTES.length).equals(MANAGED_WRITE_RECOVERY_BYTES);
    if (!head.includes(MANAGED_MARKER) && !recoverySuffixPresent) return { kind: "foreign" };
    if (opened.nlink !== 1) return { kind: "unsafe-managed" };
    const requiredRecoveryBytes = recoverySuffixPresent ? 0 : MANAGED_WRITE_RECOVERY_BYTES.length;
    if (opened.size + requiredRecoveryBytes > MAX_MANAGED_LAUNCHER_BYTES) {
      return { kind: "unsafe-managed-size" };
    }
    return {
      kind: "managed",
      dev: opened.dev,
      ino: opened.ino,
      content,
      size: opened.size,
      sha256: createHash("sha256").update(contentBytes).digest("hex"),
      recoverySuffixPresent,
    };
  } catch (error) {
    return fsErrorCode(error) === "ENOENT" ? { kind: "absent" } : { kind: "foreign" };
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function pathHasIdentity(target: string, expected: ManagedTargetIdentity): boolean {
  try {
    const current = lstatSync(target);
    return current.isFile()
      && !current.isSymbolicLink()
      && current.dev === expected.dev
      && current.ino === expected.ino;
  } catch {
    return false;
  }
}

function managedLauncherFdMatches(
  fd: number,
  expected: ManagedTargetIdentity,
  readChunk: LauncherReadChunk = readSync,
): boolean {
  const current = fstatSync(fd);
  if (!current.isFile()
    || current.nlink !== 1
    || current.dev !== expected.dev
    || current.ino !== expected.ino
    || current.size !== expected.size) return false;
  const content = readLauncherFdBuffer(fd, expected.size + 1, readChunk);
  return content.length === expected.size
    && createHash("sha256").update(content).digest("hex") === expected.sha256;
}

function appendManagedLauncherRecovery(fd: number, position: number): void {
  const bytes = MANAGED_WRITE_RECOVERY_BYTES;
  let offset = 0;
  while (offset < bytes.length) {
    const written = writeSync(fd, bytes, offset, bytes.length - offset, position + offset);
    if (!Number.isInteger(written) || written <= 0 || written > bytes.length - offset) {
      throw new Error("managed launcher recovery append made no valid progress");
    }
    offset += written;
  }
  fsyncSync(fd);
}

function writeLauncherFd(fd: number, content: string, writeChunk: LauncherWriteChunk = writeSync): void {
  const bytes = Buffer.from(content, "utf8");
  let offset = 0;
  while (offset < bytes.length) {
    const written = writeChunk(fd, bytes, offset, bytes.length - offset, offset);
    if (!Number.isInteger(written) || written <= 0 || written > bytes.length - offset) {
      throw new Error("managed launcher write made no valid progress");
    }
    offset += written;
  }
  ftruncateSync(fd, bytes.length);
  if (process.platform !== "win32") fchmodSync(fd, 0o755);
  fsyncSync(fd);
}

function fsyncDirectory(path: string): boolean {
  let fd: number | undefined;
  try {
    fd = openSync(path, constants.O_RDONLY);
    fsyncSync(fd);
    return true;
  } catch {
    return process.platform === "win32";
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function unlinkGeneratedFileIfIdentity(path: string, dev: number, ino: number): void {
  try {
    const current = lstatSync(path);
    if (current.isFile() && !current.isSymbolicLink() && current.dev === dev && current.ino === ino) {
      unlinkSync(path);
    }
  } catch { /* remove only the generated path when its identity is still exact */ }
}

function publishManagedLauncher(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  target: string,
  entry: ClaudeLauncherEntry,
  ownership: LauncherTargetOwnership,
  content: string,
  beforePublish?: ClaudeLauncherSyncOptions["beforePublish"],
  readManagedLauncherChunk?: LauncherReadChunk,
  writeManagedLauncherChunk?: LauncherWriteChunk,
  syncDirectory: NonNullable<ClaudeLauncherSyncOptions["fsyncDirectory"]> = fsyncDirectory,
): boolean {
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return false;
  if (ownership.kind === "managed") {
    let fd: number | undefined;
    try {
      fd = openSync(target, constants.O_RDWR | (constants.O_NOFOLLOW ?? 0));
      if (!managedLauncherFdMatches(fd, ownership, readManagedLauncherChunk)) return false;
      beforePublish?.(target, entry);
      if (!launcherDirectoryHasIdentity(binDir, binIdentity)
        || !pathHasIdentity(target, ownership)
        || !managedLauncherFdMatches(fd, ownership, readManagedLauncherChunk)) return false;
      if (!ownership.recoverySuffixPresent) appendManagedLauncherRecovery(fd, ownership.size);
      writeLauncherFd(fd, content, writeManagedLauncherChunk);
      return launcherDirectoryHasIdentity(binDir, binIdentity)
        && pathHasIdentity(target, ownership)
        && readLauncherFd(fd, Buffer.byteLength(content, "utf8") + 1, readManagedLauncherChunk) === content;
    } catch {
      return false;
    } finally {
      if (fd !== undefined) {
        try { closeSync(fd); } catch { /* best effort */ }
      }
    }
  }
  if (ownership.kind !== "absent") return false;

  const temporary = join(dirname(target), `.frogprogsy-launcher-${randomUUID()}.tmp`);
  let fd: number | undefined;
  let temporaryIdentity: { dev: number; ino: number } | undefined;
  try {
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return false;
    fd = openSync(
      temporary,
      constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | (constants.O_NOFOLLOW ?? 0),
      0o755,
    );
    writeLauncherFd(fd, content);
    const temporaryStat = fstatSync(fd);
    temporaryIdentity = { dev: temporaryStat.dev, ino: temporaryStat.ino };
    beforePublish?.(target, entry);
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return false;
    linkSync(temporary, target);
    if (!syncDirectory(dirname(target))) {
      if (launcherDirectoryHasIdentity(binDir, binIdentity)) {
        unlinkGeneratedFileIfIdentity(target, temporaryStat.dev, temporaryStat.ino);
      }
      return false;
    }
    const published = lstatSync(target);
    return launcherDirectoryHasIdentity(binDir, binIdentity)
      && published.isFile()
      && !published.isSymbolicLink()
      && published.dev === temporaryStat.dev
      && published.ino === temporaryStat.ino;
  } catch {
    return false;
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
    if (temporaryIdentity && launcherDirectoryHasIdentity(binDir, binIdentity)) {
      unlinkGeneratedFileIfIdentity(temporary, temporaryIdentity.dev, temporaryIdentity.ino);
    }
  }
}

function launcherRecoveryRoot(binDir: string): string {
  return join(binDir, LAUNCHER_RECOVERY_DIR);
}

function recoveryRootIsOwned(recoveryRoot: string): boolean {
  let ownerFd: number | undefined;
  try {
    const rootStat = lstatSync(recoveryRoot);
    if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) return false;
    if (process.platform !== "win32" && (rootStat.mode & 0o777) !== 0o700) return false;
    const ownerPath = join(recoveryRoot, LAUNCHER_RECOVERY_OWNER);
    const ownerStat = lstatSync(ownerPath);
    if (!ownerStat.isFile() || ownerStat.isSymbolicLink() || ownerStat.nlink !== 1) return false;
    ownerFd = openSync(ownerPath, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
    return readLauncherFd(ownerFd, LAUNCHER_RECOVERY_OWNER_BYTES.length + 1) === LAUNCHER_RECOVERY_OWNER_BYTES;
  } catch {
    return false;
  } finally {
    if (ownerFd !== undefined) {
      try { closeSync(ownerFd); } catch { /* best effort */ }
    }
  }
}

function ownedRecoveryRoot(binDir: string, create: boolean): string | null {
  const recoveryRoot = launcherRecoveryRoot(binDir);
  try {
    lstatSync(recoveryRoot);
    return recoveryRootIsOwned(recoveryRoot) ? recoveryRoot : null;
  } catch (error) {
    if (!create || fsErrorCode(error) !== "ENOENT") return null;
  }

  let ownerFd: number | undefined;
  try {
    mkdirSync(recoveryRoot, { mode: 0o700 });
    const rootStat = lstatSync(recoveryRoot);
    if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) return null;
    const ownerPath = join(recoveryRoot, LAUNCHER_RECOVERY_OWNER);
    ownerFd = openSync(
      ownerPath,
      constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | (constants.O_NOFOLLOW ?? 0),
      0o600,
    );
    writeFileSync(ownerFd, LAUNCHER_RECOVERY_OWNER_BYTES, "utf8");
    fsyncSync(ownerFd);
    closeSync(ownerFd);
    ownerFd = undefined;
    if (!fsyncDirectory(recoveryRoot) || !fsyncDirectory(binDir)) return null;
    return recoveryRootIsOwned(recoveryRoot) ? recoveryRoot : null;
  } catch {
    return null;
  } finally {
    if (ownerFd !== undefined) {
      try { closeSync(ownerFd); } catch { /* best effort */ }
    }
  }
}

function removeRecoveryOperation(operationDir: string): void {
  try {
    const capture = join(operationDir, LAUNCHER_RECOVERY_CAPTURE);
    try {
      lstatSync(capture);
      return;
    } catch (error) {
      if (fsErrorCode(error) !== "ENOENT") return;
    }
    for (const fileName of [
      LAUNCHER_RECOVERY_MANIFEST,
      "hardlink-preflight",
      "hardlink-preflight-link",
    ]) {
      try { unlinkSync(join(operationDir, fileName)); } catch { /* already absent */ }
    }
    rmdirSync(operationDir);
  } catch { /* generated recovery only */ }
}

function createRemovalRecovery(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  target: string,
  ownership: ManagedTargetIdentity,
): { operationDir: string; capture: string } | null {
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return null;
  const recoveryRoot = ownedRecoveryRoot(binDir, true);
  if (!recoveryRoot || !launcherDirectoryHasIdentity(binDir, binIdentity)) return null;
  const operationDir = join(recoveryRoot, randomUUID());
  try {
    mkdirSync(operationDir, { mode: 0o700 });

    const preflight = join(operationDir, "hardlink-preflight");
    const preflightLink = join(operationDir, "hardlink-preflight-link");
    let preflightFd: number | undefined;
    try {
      preflightFd = openSync(preflight, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL, 0o600);
      writeFileSync(preflightFd, "frogprogsy launcher recovery", "utf8");
      fsyncSync(preflightFd);
    } finally {
      if (preflightFd !== undefined) closeSync(preflightFd);
    }
    linkSync(preflight, preflightLink);
    unlinkSync(preflightLink);
    unlinkSync(preflight);

    const manifest: LauncherRemovalManifest = {
      schemaVersion: 2,
      phase: "capture-pending",
      targetName: basename(target),
      expected: {
        dev: ownership.dev,
        ino: ownership.ino,
        size: ownership.size,
        sha256: ownership.sha256,
      },
    };
    const manifestPath = join(operationDir, LAUNCHER_RECOVERY_MANIFEST);
    let manifestFd: number | undefined;
    try {
      manifestFd = openSync(
        manifestPath,
        constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | (constants.O_NOFOLLOW ?? 0),
        0o600,
      );
      writeFileSync(manifestFd, JSON.stringify(manifest) + "\n", "utf8");
      fsyncSync(manifestFd);
    } finally {
      if (manifestFd !== undefined) closeSync(manifestFd);
    }
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)
      || !recoveryRootIsOwned(recoveryRoot)
      || !fsyncDirectory(operationDir)
      || !fsyncDirectory(recoveryRoot)) {
      if (launcherDirectoryHasIdentity(binDir, binIdentity)) removeRecoveryOperation(operationDir);
      return null;
    }
    return { operationDir, capture: join(operationDir, LAUNCHER_RECOVERY_CAPTURE) };
  } catch {
    if (launcherDirectoryHasIdentity(binDir, binIdentity)) removeRecoveryOperation(operationDir);
    return null;
  }
}

function readRemovalManifest(
  operationDir: string,
  readChunk: LauncherReadChunk = readSync,
): LauncherRemovalManifest | null {
  let fd: number | undefined;
  try {
    const manifestPath = join(operationDir, LAUNCHER_RECOVERY_MANIFEST);
    const manifestStat = lstatSync(manifestPath);
    if (!manifestStat.isFile() || manifestStat.isSymbolicLink() || manifestStat.nlink !== 1) return null;
    fd = openSync(manifestPath, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
    const opened = fstatSync(fd);
    if (!opened.isFile()
      || opened.nlink !== 1
      || opened.dev !== manifestStat.dev
      || opened.ino !== manifestStat.ino) return null;
    const manifest = JSON.parse(readLauncherFd(fd, LAUNCHER_SNIFF_BYTES, readChunk));
    if ((manifest?.schemaVersion !== 1 && manifest?.schemaVersion !== 2)
      || manifest.phase !== "capture-pending") return null;
    if (typeof manifest.targetName !== "string" || basename(manifest.targetName) !== manifest.targetName) return null;
    if (manifest.schemaVersion === 2) {
      const expected = manifest.expected;
      if (!expected
        || !Number.isInteger(expected.dev)
        || !Number.isInteger(expected.ino)
        || !Number.isSafeInteger(expected.size)
        || expected.size < 0
        || typeof expected.sha256 !== "string"
        || !/^[0-9a-f]{64}$/.test(expected.sha256)) return null;
    }
    return manifest as LauncherRemovalManifest;
  } catch {
    return null;
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function restoreCapturedForeign(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  capture: string,
  target: string,
  operationDir: string,
  afterForeignRestore?: (target: string, capture: string) => void,
  syncDirectory: NonNullable<ClaudeLauncherSyncOptions["fsyncDirectory"]> = fsyncDirectory,
): "restored" | "never-captured" | "pending" {
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return "pending";
  let captured;
  try {
    captured = lstatSync(capture);
  } catch (error) {
    if (fsErrorCode(error) !== "ENOENT") return "pending";
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return "pending";
    removeRecoveryOperation(operationDir);
    try {
      lstatSync(operationDir);
      return "pending";
    } catch (cleanupError) {
      return fsErrorCode(cleanupError) === "ENOENT" ? "never-captured" : "pending";
    }
  }
  try {
    lstatSync(target);
    return "pending";
  } catch (error) {
    if (fsErrorCode(error) !== "ENOENT") return "pending";
  }

  const temporary = join(operationDir, `.restore-${randomUUID()}.tmp`);
  let captureFd: number | undefined;
  let temporaryFd: number | undefined;
  let temporaryIdentity: { dev: number; ino: number } | undefined;
  try {
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return "pending";
    if (captured.isFile() && !captured.isSymbolicLink()) {
      captureFd = openSync(capture, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
      const openedCapture = fstatSync(captureFd);
      if (!openedCapture.isFile()
        || openedCapture.dev !== captured.dev
        || openedCapture.ino !== captured.ino) return "pending";

      temporaryFd = openSync(
        temporary,
        constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | (constants.O_NOFOLLOW ?? 0),
        0o600,
      );
      const openedTemporary = fstatSync(temporaryFd);
      temporaryIdentity = { dev: openedTemporary.dev, ino: openedTemporary.ino };
      const buffer = Buffer.allocUnsafe(LAUNCHER_RECOVERY_COPY_BUFFER_BYTES);
      for (;;) {
        const bytesRead = readSync(captureFd, buffer, 0, buffer.length, null);
        if (bytesRead === 0) break;
        let bytesWritten = 0;
        while (bytesWritten < bytesRead) {
          bytesWritten += writeSync(temporaryFd, buffer, bytesWritten, bytesRead - bytesWritten);
        }
      }
      if (process.platform !== "win32") fchmodSync(temporaryFd, openedCapture.mode & 0o7777);
      fsyncSync(temporaryFd);
      if (!syncDirectory(operationDir)
        || !launcherDirectoryHasIdentity(binDir, binIdentity)) return "pending";
      linkSync(temporary, target);
    } else if (captured.isSymbolicLink()) {
      symlinkSync(readlinkSync(capture), target, "file");
    } else {
      return "pending";
    }
    afterForeignRestore?.(target, capture);
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return "pending";
    if (!syncDirectory(dirname(target))) return "pending";
    return "restored";
  } catch {
    return "pending";
  } finally {
    if (captureFd !== undefined) {
      try { closeSync(captureFd); } catch { /* best effort */ }
    }
    if (temporaryFd !== undefined) {
      try { closeSync(temporaryFd); } catch { /* best effort */ }
    }
    if (temporaryIdentity && launcherDirectoryHasIdentity(binDir, binIdentity)) {
      unlinkGeneratedFileIfIdentity(temporary, temporaryIdentity.dev, temporaryIdentity.ino);
    }
  }
}

function finishRemovalRecovery(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  operationDir: string,
  manifest: LauncherRemovalManifest,
  readManagedLauncherChunk?: LauncherReadChunk,
  afterForeignRestore?: (target: string, capture: string) => void,
  syncDirectory: NonNullable<ClaudeLauncherSyncOptions["fsyncDirectory"]> = fsyncDirectory,
): { removed: boolean; warning?: string } {
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
    return { removed: false, warning: `launcher ${manifest.targetName} cleanup deferred; launcher directory changed` };
  }
  const capture = join(operationDir, LAUNCHER_RECOVERY_CAPTURE);
  const target = join(binDir, manifest.targetName);
  const capturedOwnership = classifyLauncherTarget(capture, readManagedLauncherChunk);
  const expected = manifest.expected;
  const capturedMatchesExpected = capturedOwnership.kind === "managed"
    && expected !== undefined
    && capturedOwnership.dev === expected.dev
    && capturedOwnership.ino === expected.ino
    && capturedOwnership.size === expected.size
    && capturedOwnership.sha256 === expected.sha256;
  if (capturedMatchesExpected) {
    try {
      if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
        return { removed: false, warning: `launcher ${manifest.targetName} cleanup deferred; launcher directory changed` };
      }
      unlinkSync(capture);
      if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
        return { removed: false, warning: `launcher ${manifest.targetName} cleanup deferred; launcher directory changed` };
      }
      removeRecoveryOperation(operationDir);
      return { removed: true };
    } catch {
      return { removed: false, warning: `launcher ${manifest.targetName} cleanup deferred; generated recovery is still pending` };
    }
  }
  const foreignRecovery = restoreCapturedForeign(
    binDir,
    binIdentity,
    capture,
    target,
    operationDir,
    afterForeignRestore,
    syncDirectory,
  );
  if (foreignRecovery === "never-captured") return { removed: false };
  if (foreignRecovery === "restored") {
    return {
      removed: false,
      warning: `launcher ${manifest.targetName} cleanup deferred; the changed target was restored; manual recovery/cleanup is required before removing the preserved capture`,
    };
  }
  return { removed: false, warning: `launcher ${manifest.targetName} cleanup deferred; preserved recovery requires attention` };
}

function recoverLauncherRemovals(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  readManagedLauncherChunk?: LauncherReadChunk,
  afterForeignRestore?: (target: string, capture: string) => void,
  syncDirectory: NonNullable<ClaudeLauncherSyncOptions["fsyncDirectory"]> = fsyncDirectory,
): string[] {
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return [];
  const recoveryRoot = ownedRecoveryRoot(binDir, false);
  if (!recoveryRoot || !launcherDirectoryHasIdentity(binDir, binIdentity)) return [];
  let operationNames: string[];
  try {
    operationNames = readdirSync(recoveryRoot);
  } catch {
    return [];
  }
  const warnings: string[] = [];
  for (const operationName of operationNames) {
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
      warnings.push("launcher cleanup deferred; launcher directory changed during recovery");
      break;
    }
    if (operationName === LAUNCHER_RECOVERY_OWNER) continue;
    const operationDir = join(recoveryRoot, operationName);
    try {
      const operationStat = lstatSync(operationDir);
      if (!operationStat.isDirectory() || operationStat.isSymbolicLink()) {
        warnings.push("launcher cleanup deferred; an unsafe recovery entry was preserved");
        continue;
      }
    } catch {
      continue;
    }
    const manifest = readRemovalManifest(operationDir, readManagedLauncherChunk);
    if (!manifest) {
      warnings.push("launcher cleanup deferred; an unreadable recovery record was preserved");
      continue;
    }
    const outcome = finishRemovalRecovery(
      binDir,
      binIdentity,
      operationDir,
      manifest,
      readManagedLauncherChunk,
      afterForeignRestore,
      syncDirectory,
    );
    if (outcome.warning) warnings.push(outcome.warning);
  }
  return warnings;
}

export function isManagedClaudeProfileLauncher(path: string, profileId: string): boolean {
  return isExactManagedClaudeLauncher(path, profileId);
}

function readManifest(): ClaudeLauncherManifest | null {
  try {
    const parsed = JSON.parse(readFileSync(manifestPath(), "utf8"));
    if (parsed?.schemaVersion === 1 && Array.isArray(parsed.launchers)) return parsed as ClaudeLauncherManifest;
  } catch { /* rebuild */ }
  return null;
}
function launcherTargetPaths(binDir: string, name: string): string[] {
  const nativeTarget = join(binDir, claudeLauncherFileName(name));
  if (process.platform !== "win32") return [nativeTarget];
  return [nativeTarget, join(binDir, name)];
}

/** True only for a safely classified frogprogsy-managed launcher that embeds this exact profile id. */
export function isExactManagedClaudeLauncher(target: string, profileId: string): boolean {
  const ownership = classifyLauncherTarget(target);
  return ownership.kind === "managed" && managedContentMatchesProfile(ownership.content, profileId);
}

function removeManagedLauncherFile(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  target: string,
  options: ClaudeLauncherSyncOptions,
  warnings: string[],
): boolean {
  if (resolve(dirname(target)) !== resolve(binDir)
    || !launcherDirectoryHasIdentity(binDir, binIdentity)) return false;
  const ownership = classifyLauncherTarget(target, options.readManagedLauncherChunk);
  if (ownership.kind === "unsafe-managed") {
    warnings.push(`launcher ${basename(target)} cleanup skipped; managed target has multiple hard links`);
    return false;
  }
  if (ownership.kind === "unsafe-managed-size") {
    warnings.push(`launcher ${basename(target)} cleanup skipped; managed target exceeds the safe update size`);
    return false;
  }
  if (ownership.kind !== "managed") return false;

  const recovery = createRemovalRecovery(binDir, binIdentity, target, ownership);
  if (!recovery) {
    warnings.push(`launcher ${basename(target)} cleanup skipped; durable recovery could not be prepared`);
    return false;
  }
  try {
    options.beforeManagedRemove?.(target);
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
      warnings.push(`launcher ${basename(target)} cleanup skipped; launcher directory changed before capture`);
      return false;
    }
    renameSync(target, recovery.capture);
  } catch (error) {
    if (launcherDirectoryHasIdentity(binDir, binIdentity)) removeRecoveryOperation(recovery.operationDir);
    if (options.beforeManagedRemove && fsErrorCode(error) !== undefined) {
      warnings.push(`launcher ${basename(target)} cleanup skipped; target changed before capture`);
    }
    return false;
  }
  options.beforeManagedRemoveDurability?.(target);
  const syncDirectory = options.fsyncDirectory ?? fsyncDirectory;
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)
    || !syncDirectory(binDir)
    || !syncDirectory(recovery.operationDir)) {
    warnings.push(`launcher ${basename(target)} cleanup deferred; captured target could not be durably recorded`);
    return false;
  }
  options.afterManagedRemoveCapture?.(target);
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
    warnings.push(`launcher ${basename(target)} cleanup deferred; launcher directory changed after capture`);
    return false;
  }
  const manifest = readRemovalManifest(recovery.operationDir, options.readManagedLauncherChunk);
  if (!manifest) {
    warnings.push(`launcher ${basename(target)} cleanup deferred; recovery record could not be read`);
    return false;
  }
  const outcome = finishRemovalRecovery(
    binDir,
    binIdentity,
    recovery.operationDir,
    manifest,
    options.readManagedLauncherChunk,
    options.afterForeignRestore,
    options.fsyncDirectory ?? fsyncDirectory,
  );
  if (outcome.warning) warnings.push(outcome.warning);
  return outcome.removed;
}

function hasManagedLauncherFile(binDir: string): boolean {
  let entries: string[];
  try {
    entries = readdirSync(binDir);
  } catch {
    return false;
  }
  return entries.some(fileName => {
    const logicalName = process.platform === "win32" && fileName.endsWith(".cmd")
      ? fileName.slice(0, -4)
      : fileName;
    if (!(logicalName === "claude" || SHORTCUT_NAME_PATTERN.test(logicalName))) return false;
    const ownership = classifyLauncherTarget(join(binDir, fileName));
    return ownership.kind === "managed"
      || ownership.kind === "unsafe-managed"
      || ownership.kind === "unsafe-managed-size";
  });
}

/**
 * Remove marked launchers whose logical names no longer appear in the current plan, even when the
 * manifest is missing or corrupt. The classifier — not the manifest — is the deletion authority, so
 * unmarked user files and unsafe managed inodes are preserved. Same-name launchers are validated
 * against the exact profile separately before they are reported or rewritten.
 */
function removeOrphanManagedLaunchers(
  binDir: string,
  binIdentity: LauncherDirectoryIdentity,
  nextNames: Set<string>,
  options: ClaudeLauncherSyncOptions,
  warnings: string[],
): string[] {
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) return [];
  let entries: string[];
  try {
    entries = readdirSync(binDir);
  } catch {
    return [];
  }

  const removed = new Set<string>();
  for (const fileName of entries) {
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) break;
    const logicalName = process.platform === "win32" && fileName.endsWith(".cmd")
      ? fileName.slice(0, -4)
      : fileName;
    if (!(logicalName === "claude" || /^claude-[a-z0-9][a-z0-9-]*$/.test(logicalName))) continue;
    if (nextNames.has(logicalName)) continue;
    if (removeManagedLauncherFile(binDir, binIdentity, join(binDir, fileName), options, warnings)) {
      removed.add(logicalName);
    }
  }
  return [...removed];
}

interface LauncherDirectoryIdentity {
  dev: number;
  ino: number;
}

function launcherDirectoryHasIdentity(binDir: string, identity: LauncherDirectoryIdentity): boolean {
  try {
    const current = lstatSync(binDir);
    return current.isDirectory()
      && !current.isSymbolicLink()
      && current.dev === identity.dev
      && current.ino === identity.ino;
  } catch {
    return false;
  }
}

function prepareLauncherDirectory(configDir: string): { binDir: string; identity: LauncherDirectoryIdentity } {
  const binDir = join(configDir, "bin");
  try {
    lstatSync(binDir);
  } catch (error) {
    if (fsErrorCode(error) !== "ENOENT") {
      throw new Error("Claude launcher directory could not be inspected");
    }
    try {
      mkdirSync(binDir, { mode: 0o700 });
    } catch (mkdirError) {
      if (fsErrorCode(mkdirError) !== "EEXIST") {
        throw new Error("Claude launcher directory could not be created");
      }
    }
  }

  const pathStat = lstatSync(binDir);
  if (!pathStat.isDirectory() || pathStat.isSymbolicLink()) {
    throw new Error("Claude launcher directory must be a real directory");
  }
  if (process.platform === "win32") {
    const identity = { dev: pathStat.dev, ino: pathStat.ino };
    if (!launcherDirectoryHasIdentity(binDir, identity)) {
      throw new Error("Claude launcher directory changed before use");
    }
    return { binDir, identity };
  }

  let fd: number | undefined;
  try {
    fd = openSync(binDir, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
    const opened = fstatSync(fd);
    if (!opened.isDirectory() || opened.dev !== pathStat.dev || opened.ino !== pathStat.ino) {
      throw new Error("Claude launcher directory changed while it was being opened");
    }
    fchmodSync(fd, 0o700);
    fsyncSync(fd);
    const identity = { dev: opened.dev, ino: opened.ino };
    if (!launcherDirectoryHasIdentity(binDir, identity)) {
      throw new Error("Claude launcher directory changed before use");
    }
    return { binDir, identity };
  } catch (error) {
    if (error instanceof Error && error.message.startsWith("Claude launcher directory")) throw error;
    throw new Error("Claude launcher directory could not be opened safely");
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function managedContentMatchesProfile(content: string, profileId: string): boolean {
  const invocation = process.platform === "win32"
    ? `"claude" "run" "${profileId}" "--"`
    : `'claude' 'run' '${profileId}' '--'`;
  return content.includes(MANAGED_MARKER) && content.includes(invocation);
}

export const REAL_CLAUDE_UNRESOLVED_WARNING =
  "the original Claude Code executable was not found, so no account shortcut was generated; install Claude Code and run frogp refresh";

export function syncClaudeLauncherShims(
  config: FrogConfig,
  options: ClaudeLauncherSyncOptions = {},
): ClaudeLauncherSyncResult {
  const configDir = getConfigDir();
  const binDir = join(configDir, "bin");
  const frogpCommand = options.frogpCommand ?? currentFrogpCommand();
  const plan = plannedClaudeLaunchers(config);
  const previous = readManifest();
  const realClaude = options.realClaude ?? findRealClaudeExecutableOrNull([binDir]);

  // Missing Claude on a fresh installation is an inspection result, not a reason to create config,
  // launcher, or manifest files. Existing managed state still proceeds through durable cleanup.
  if (!realClaude
    && previous === null
    && !hasManagedLauncherFile(binDir)
    && ownedRecoveryRoot(binDir, false) === null) {
    return {
      binDir,
      realClaude: "claude",
      realClaudeResolved: false,
      frogpCommand,
      launchers: [],
      removed: [],
      warnings: [...plan.warnings, REAL_CLAUDE_UNRESOLVED_WARNING],
    };
  }

  ensureConfigDirForWrite("sync Claude launcher shims");
  const { identity: binIdentity } = prepareLauncherDirectory(configDir);
  const warnings = [
    ...plan.warnings,
    ...recoverLauncherRemovals(
      binDir,
      binIdentity,
      options.readManagedLauncherChunk,
      options.afterForeignRestore,
      options.fsyncDirectory ?? fsyncDirectory,
    ),
  ];
  if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
    throw new Error("Claude launcher directory changed before synchronization");
  }

  const candidates: Array<{ entry: ClaudeLauncherEntry; ownership: LauncherTargetOwnership }> = [];
  for (const entry of plan.launchers) {
    const target = join(binDir, claudeLauncherFileName(entry.name));
    const ownership = classifyLauncherTarget(target, options.readManagedLauncherChunk);
    if (ownership.kind === "absent" || ownership.kind === "managed") {
      candidates.push({ entry, ownership });
      continue;
    }
    const reason = ownership.kind === "unsafe-managed"
      ? "managed target has multiple hard links"
      : ownership.kind === "unsafe-managed-size"
        ? "managed target exceeds the safe update size"
        : "target is not owned by frogprogsy. Move or remove it, then run frogp refresh";
    warnings.push(`launcher ${entry.name} skipped for ${entry.profileName}; ${reason}`);
  }
  const nextNames = new Set(plan.launchers.map(entry => entry.name));
  const removed: string[] = [];

  for (const old of previous?.launchers ?? []) {
    if (nextNames.has(old.name)) {
      if (process.platform === "win32") {
        removeManagedLauncherFile(binDir, binIdentity, join(binDir, old.name), options, warnings);
      }
      continue;
    }
    let didRemove = false;
    for (const target of launcherTargetPaths(binDir, old.name)) {
      didRemove = removeManagedLauncherFile(binDir, binIdentity, target, options, warnings) || didRemove;
    }
    if (didRemove) removed.push(old.name);
  }

  // Cleanup does not depend on the native executable. Run it first so deleted or renamed accounts
  // lose stale managed launchers even while Claude Code itself is absent.
  for (const orphan of removeOrphanManagedLaunchers(binDir, binIdentity, nextNames, options, warnings)) {
    if (!removed.includes(orphan)) removed.push(orphan);
  }

  if (!realClaude) {
    // A same-name launcher for another profile is not a valid survivor. Without a native executable
    // it cannot be rewritten, so remove it through the same journaled generated-only cleanup path.
    for (const entry of plan.launchers) {
      const target = join(binDir, claudeLauncherFileName(entry.name));
      const ownership = classifyLauncherTarget(target, options.readManagedLauncherChunk);
      if (ownership.kind !== "managed" || managedContentMatchesProfile(ownership.content, entry.profileId)) continue;
      if (removeManagedLauncherFile(binDir, binIdentity, target, options, warnings) && !removed.includes(entry.name)) {
        removed.push(entry.name);
      }
    }

    const surviving = plan.launchers.filter(entry => {
      const ownership = classifyLauncherTarget(
        join(binDir, claudeLauncherFileName(entry.name)),
        options.readManagedLauncherChunk,
      );
      return ownership.kind === "managed"
        && managedContentMatchesProfile(ownership.content, entry.profileId);
    });
    const manifest: ClaudeLauncherManifest = {
      schemaVersion: 1,
      generatedAt: new Date().toISOString(),
      binDir,
      realClaude: previous?.realClaude ?? "claude",
      frogpCommand: previous?.frogpCommand ?? frogpCommand,
      launchers: surviving,
    };
    atomicWriteFile(manifestPath(), JSON.stringify(manifest, null, 2) + "\n");
    return {
      binDir,
      realClaude: "claude",
      realClaudeResolved: false,
      frogpCommand,
      launchers: surviving,
      removed,
      warnings: [...warnings, REAL_CLAUDE_UNRESOLVED_WARNING],
    };
  }

  const installed: ClaudeLauncherEntry[] = [];
  for (const { entry, ownership } of candidates) {
    if (!launcherDirectoryHasIdentity(binDir, binIdentity)) {
      throw new Error("Claude launcher directory changed during synchronization");
    }
    const target = join(binDir, claudeLauncherFileName(entry.name));
    const content = launcherScript(entry, realClaude, frogpCommand);
    if (publishManagedLauncher(
      binDir,
      binIdentity,
      target,
      entry,
      ownership,
      content,
      options.beforePublish,
      options.readManagedLauncherChunk,
      options.writeManagedLauncherChunk,
      options.fsyncDirectory ?? fsyncDirectory,
    )) {
      installed.push(entry);
    } else {
      warnings.push(`launcher ${entry.name} skipped for ${entry.profileName}; target changed or could not be published safely`);
    }
    if (process.platform === "win32") {
      removeManagedLauncherFile(binDir, binIdentity, join(binDir, entry.name), options, warnings);
    }
  }

  const manifest: ClaudeLauncherManifest = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    binDir,
    realClaude,
    frogpCommand,
    launchers: installed,
  };
  atomicWriteFile(manifestPath(), JSON.stringify(manifest, null, 2) + "\n");
  return { binDir, realClaude, realClaudeResolved: true, frogpCommand, launchers: installed, removed, warnings };
}

/**
 * Best-effort sync outcome reported by the management API. `shortcutProfileIds` lists the profiles that
 * actually own a generated shortcut, so a caller never has to infer that from `success` alone.
 */
export interface ClaudeLauncherSyncSummary {
  success: boolean;
  error?: string;
  realClaudeResolved?: boolean;
  warnings?: string[];
  shortcutProfileIds?: string[];
}


export function removeClaudeLauncherShims(): { binDir: string; removed: string[] } {
  const binDir = claudeLauncherBinDir();
  const previous = readManifest();
  const removed: string[] = [];
  const warnings: string[] = [];
  const options: ClaudeLauncherSyncOptions = {};
  let binIdentity: LauncherDirectoryIdentity | undefined;
  try {
    const binStat = lstatSync(binDir);
    if (binStat.isDirectory() && !binStat.isSymbolicLink()) {
      binIdentity = { dev: binStat.dev, ino: binStat.ino };
    }
  } catch { /* nothing to remove */ }
  if (binIdentity && launcherDirectoryHasIdentity(binDir, binIdentity)) {
    recoverLauncherRemovals(binDir, binIdentity);
    for (const old of previous?.launchers ?? []) {
      let didRemove = false;
      for (const target of launcherTargetPaths(binDir, old.name)) {
        didRemove = removeManagedLauncherFile(binDir, binIdentity, target, options, warnings) || didRemove;
      }
      if (didRemove) removed.push(old.name);
    }
  }
  const manifest = manifestPath();
  if (existsSync(manifest)) {
    try { rmSync(manifest); } catch { /* best effort */ }
  }
  return { binDir, removed };
}

function gatewayProcessActive(): boolean {
  return readPid() !== null && readActivePort() !== null;
}

type RefreshManagedCatalog = typeof import("./claude-refresh").refreshClaudeCodeModelCatalog;

/**
 * Pre-warm a managed profile's Claude Code picker cache inside that profile's own home BEFORE the
 * managed gateway Claude launches, so the picker reads a fresh catalog. Best-effort: a transient
 * refresh error never blocks the launch. The last-known-good cache policy lives entirely in the
 * refresh module; the warning here is intentionally free of tokens, paths, or other sensitive detail.
 */
async function refreshManagedProfileCatalog(
  config: FrogConfig,
  profile: ClaudeProfileRecord,
  refreshCatalog?: RefreshManagedCatalog,
): Promise<void> {
  try {
    const refresh = refreshCatalog ?? (await import("./claude-refresh")).refreshClaudeCodeModelCatalog;
    const result = await refresh(config, undefined, { claudeHome: profile.claudeHome, profileId: profile.id });
    if (result.gatewayCache.status === "failed" || result.warnings.length > 0) {
      console.warn(`frogprogsy: Claude model picker cache refresh reported a warning for profile ${profile.id}; continuing with the last known-good catalog when available.`);
    }
  } catch {
    console.warn(`frogprogsy: Claude model picker cache refresh failed for profile ${profile.id}; continuing with the last known-good catalog when available.`);
  }
}

const LAUNCHER_SPAWN_FAILURE_MESSAGE = "frogprogsy: failed to launch the Claude executable.";

/**
 * Map a spawnSync result to a launcher exit code, failing closed. A spawn that never started
 * (`result.error`, e.g. ENOENT/EACCES) or was terminated by a signal without a concrete status
 * MUST NOT surface as exit 0; a concrete numeric status (including 0) is preserved verbatim.
 * A missing executable (ENOENT) maps to the shell "command not found" code 127; any other spawn
 * error maps to 1. The failure diagnostic is fixed and redacted — it carries no path, argv, or
 * raw error body.
 */
function launcherResultExitCode(result: Pick<ReturnType<typeof spawnSync>, "status" | "signal" | "error">): number {
  if (result.error) {
    console.error(LAUNCHER_SPAWN_FAILURE_MESSAGE);
    return (result.error as NodeJS.ErrnoException).code === "ENOENT" ? 127 : 1;
  }
  if (typeof result.status === "number") return result.status;
  return 1;
}

export interface RunClaudeProfileOptions {
  realClaude?: string;
  gateway?: boolean;
  refreshCatalog?: RefreshManagedCatalog;
  spawn?: typeof spawnSync;
  exit?: (code: number) => never;
  /** Environment consulted for a conflicting account home. Injectable for tests; defaults to `process.env`. */
  env?: NodeJS.ProcessEnv;
  /** Real-executable validator seam for spawn error tests; production always uses the strict validator. */
  validateExecutable?: (candidate: string | undefined) => string;
}

/** Fixed exit code for a refused launch whose caller environment names a different account home. */
export const CLAUDE_HOME_CONFLICT_EXIT_CODE = 78;

export interface ClaudeHomeConflict {
  /** Which environment variable disagreed, or `both` when the two disagree with each other. */
  source: "CLAUDE_CONFIG_DIR" | "CLAUDE_HOME" | "both";
  reason: "different-home" | "unreadable" | "registered-unreadable";
}

/**
 * Compare the caller-supplied account home against the profile's registered home.
 *
 * Returns `null` when the launch may proceed: nothing set, or every set value canonically names the
 * same directory. Otherwise returns the conflict to refuse on.
 *
 * Refusing rather than warning is deliberate. A warning still lets Claude Code write credentials into
 * the wrong scoped store — the Keychain service name derives from the home path — which is exactly the
 * Probe-B damage recorded in `structure/09_claude-dual-auth.md`. Recovery required a human re-login.
 *
 * Missing paths, non-directories, and unreadable paths are fail-closed: an unresolvable value cannot be
 * proven equal to the registered home, so it is treated as a conflict rather than ignored.
 */
export function detectClaudeHomeConflict(
  registeredHome: string,
  env: NodeJS.ProcessEnv = process.env,
): ClaudeHomeConflict | null {
  const configDir = env.CLAUDE_CONFIG_DIR?.trim();
  const claudeHome = env.CLAUDE_HOME?.trim();

  // The registered home is the source of truth. It is never rewritten by this comparison: the spawn
  // below uses `profile.claudeHome` verbatim, because that exact string is the credential address.
  const registered = canonicalDirIdentity(registeredHome);
  if (registered === null) {
    return { source: configDir ? "CLAUDE_CONFIG_DIR" : claudeHome ? "CLAUDE_HOME" : "both", reason: "registered-unreadable" };
  }
  if (!configDir && !claudeHome) return null;

  const entries: Array<{ source: "CLAUDE_CONFIG_DIR" | "CLAUDE_HOME"; raw: string }> = [];
  if (configDir) entries.push({ source: "CLAUDE_CONFIG_DIR", raw: configDir });
  if (claudeHome) entries.push({ source: "CLAUDE_HOME", raw: claudeHome });

  const identities: string[] = [];
  for (const entry of entries) {
    const identity = canonicalDirIdentity(entry.raw);
    if (identity === null) return { source: entry.source, reason: "unreadable" };
    if (registered !== null && identity !== registered) {
      return { source: entry.source, reason: "different-home" };
    }
    identities.push(identity);
  }

  // Both set but pointing at different directories: refuse even if neither matched the registered home
  // path textually (e.g. the registered home itself could not be resolved).
  if (identities.length === 2 && identities[0] !== identities[1]) {
    return { source: "both", reason: "different-home" };
  }
  return null;
}

/** Canonical identity of an existing directory, or `null` when it is missing, not a directory, or unreadable. */
function canonicalDirIdentity(path: string): string | null {
  try {
    const resolved = resolve(expandTildePath(path));
    const stat = statSync(resolved);
    if (!stat.isDirectory()) return null;
    return realpathSync.native(resolved);
  } catch {
    return null;
  }
}

function expandTildePath(path: string): string {
  if (path === "~") return homedir();
  if (path.startsWith(`~${sep}`) || path.startsWith("~/")) return join(homedir(), path.slice(2));
  return path;
}

/**
 * User-facing refusal text. Names the shortcut and the fixing command; never prints a full home path.
 * Privacy-safe paths belong to `frogp doctor claude`, not to this default message.
 */
export function claudeHomeConflictMessage(conflict: ClaudeHomeConflict, shortcutName: string): string {
  if (conflict.reason === "registered-unreadable") {
    return [
      `Refusing to start: the registered Claude account home for ${shortcutName} is missing or cannot be read.`,
      "Running anyway could write credentials to an unintended location.",
      `Fix: restore that account home or remove and add the ${shortcutName} account again.`,
    ].join("\n");
  }
  const varLabel = conflict.source === "both" ? "CLAUDE_CONFIG_DIR and CLAUDE_HOME" : conflict.source;
  const cause = conflict.reason === "unreadable"
    ? `${varLabel} names a directory that cannot be read.`
    : `${varLabel} names a different Claude account than ${shortcutName} uses.`;
  return [
    `Refusing to start: ${cause}`,
    "Running anyway could sign this account into the wrong Claude home.",
    `Fix: unset that variable and run ${shortcutName} again, or run your own claude command directly.`,
  ].join("\n");
}

export async function runClaudeProfile(
  profile: ClaudeProfileRecord,
  config: FrogConfig,
  claudeArgs: string[],
  options: RunClaudeProfileOptions = {},
): Promise<never> {
  const exit = options.exit ?? ((code: number) => process.exit(code));

  // Single convergence point for every managed launch: a generated shortcut runs
  // `frogp claude run <id> --`, and `frogp claude run` is invoked directly. Both land here. The check
  // runs before catalog prewrite, environment assembly, and spawn, so a refusal writes nothing.
  const conflict = detectClaudeHomeConflict(profile.claudeHome, options.env ?? process.env);
  if (conflict) {
    const command = profile.id === config.claudeProfiles?.defaultProfileId ? "claude" : claudeProfileShortcutName(profile);
    console.error(claudeHomeConflictMessage(conflict, command));
    return exit(CLAUDE_HOME_CONFLICT_EXIT_CODE);
  }

  // Validate whichever executable we are about to spawn — the explicit `FROGP_REAL_CLAUDE` a generated
  // shortcut passes through the CLI, or the resolver's pick. Validating only inside the resolver would
  // skip the shortcut path entirely, since an explicit value short-circuits it.
  const validateExecutable = options.validateExecutable ?? assertRealClaudeExecutable;
  const realClaude = validateExecutable(options.realClaude ?? findRealClaudeExecutable());
  const useGateway = options.gateway ?? gatewayProcessActive();
  const spawn = options.spawn ?? spawnSync;
  let env: NodeJS.ProcessEnv;
  if (useGateway) {
    // Sync this profile's picker cache before the real Claude process starts, then launch.
    await refreshManagedProfileCatalog(config, profile, options.refreshCatalog);
    const carrier = config.gatewayAuthCarrier ?? "token-free";
    const runtimeAccessToken = config.localAccess?.enabled === true ? readLocalAccessToken() ?? undefined : undefined;
    env = buildClaudeProfileRunEnv(profile, readActivePort() ?? config.port ?? DEFAULT_PORT, carrier, process.env, runtimeAccessToken);
  } else {
    env = buildClaudeProfileNativeEnv(profile);
  }
  const result = spawn(realClaude, claudeArgs, { stdio: "inherit", env });
  return exit(launcherResultExitCode(result));
}

export function runNativeClaude(
  claudeArgs: string[],
  options: { realClaude?: string; spawn?: typeof spawnSync; exit?: (code: number) => never } = {},
): never {
  const realClaude = options.realClaude ?? findRealClaudeExecutable();
  const spawn = options.spawn ?? spawnSync;
  const exit = options.exit ?? ((code: number) => process.exit(code));
  const result = spawn(realClaude, claudeArgs, { stdio: "inherit", env: process.env });
  return exit(launcherResultExitCode(result));
}

export function profileForLauncherName(config: FrogConfig, launcherName: string): ClaudeProfileRecord {
  const { launchers } = plannedClaudeLaunchers(config);
  const matched = launchers.find(entry => entry.name === launcherName);
  return resolveClaudeProfile(config, matched?.profileId ?? launcherName.replace(/^claude-/, ""));
}
