import { createHash } from "node:crypto";
import { createInterface } from "node:readline/promises";
import {
  closeSync,
  constants,
  existsSync,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, sep } from "node:path";
import { claudeLauncherBinDir, claudeLauncherFileName } from "./claude-launchers";
import { ensureConfigDirForWrite, getConfigDir } from "./config";

const BLOCK_START = "# >>> frogprogsy account shortcuts >>>";
const BLOCK_END = "# <<< frogprogsy account shortcuts <<<";
const MANAGED_MARKER = "Generated by frogprogsy";

export type ShellShortcutSetupState = "configured" | "already_configured" | "refused";

export interface ShellShortcutSetupResult {
  state: ShellShortcutSetupState;
  rcPath: string;
  message: string;
}

function zshRcPath(env: NodeJS.ProcessEnv = process.env): string {
  const zdotdir = env.ZDOTDIR?.trim();
  return join(zdotdir || env.HOME?.trim() || homedir(), ".zshrc");
}

function lineEnding(content: string): "\n" | "\r\n" {
  return content.includes("\r\n") ? "\r\n" : "\n";
}

function hash(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

/**
 * `$HOME`-relative spelling of `binDir` when it lives under the current home directory, otherwise the
 * absolute path. The directory follows `FROGPROGSY_HOME`, so the exported line must be derived from it
 * instead of assuming `~/.frogprogsy/bin`.
 */
function shortcutPathSpelling(binDir: string, home = homedir()): string {
  if (!binDir.startsWith(`${home}${sep}`)) return binDir;
  return `$HOME/${binDir.slice(home.length + 1).split(sep).join("/")}`;
}

function containsShortcutPath(content: string, binDir: string, home: string): boolean {
  const spellings = new Set([shortcutPathSpelling(binDir, home), binDir]);
  return content.split(/\r?\n/).some(line => {
    if (line.trimStart().startsWith("#")) return false;
    const normalized = line.replaceAll("${HOME}", "$HOME");
    // Boundary-checked so a different directory that merely starts with this path (`...\/bin-old`)
    // is not mistaken for the managed one.
    return [...spellings].some(spelling => {
      let from = 0;
      for (;;) {
        const at = normalized.indexOf(spelling, from);
        if (at < 0) return false;
        const after = normalized[at + spelling.length];
        if (after === undefined || after === '"' || after === "'" || after === ":" || after === " ") return true;
        from = at + 1;
      }
    });
  });
}

function ownedBlock(eol: string, binDir: string, home: string): string {
  return [
    BLOCK_START,
    pathExportLine(binDir, home),
    BLOCK_END,
  ].join(eol);
}

function assertNoManagedPlainClaude(binDir: string): void {
  for (const target of [
    join(binDir, claudeLauncherFileName("claude")),
    join(binDir, "claude"),
    join(binDir, "claude.cmd"),
  ]) {
    if (!existsSync(target)) continue;
    try {
      if (readFileSync(target, "utf8").includes(MANAGED_MARKER)) {
        throw new Error("shell setup refused: a frogprogsy-owned plain claude launcher still exists; run frogp refresh first");
      }
    } catch (error) {
      if (error instanceof Error && error.message.startsWith("shell setup refused:")) throw error;
      throw new Error("shell setup refused: the managed launcher directory could not be inspected");
    }
  }
}

/**
 * Append the account-shortcut directory to zsh PATH without touching user-owned shell configuration.
 *
 * Safety boundary:
 * - only one exact marked block is owned;
 * - symlink rc files are refused rather than replaced;
 * - mode and line endings are preserved;
 * - content is re-read immediately before rename and compared by hash (CAS);
 * - the completed file is fsync'd in the same directory before atomic rename;
 * - managed plain `claude` must already be absent, so setup cannot move a hijack to a new PATH entry.
 */
export function configureZshAccountShortcuts(options: {
  env?: NodeJS.ProcessEnv;
  rcPath?: string;
  binDir?: string;
  /** Home directory used to decide whether the exported path can be written `$HOME`-relative. */
  homeDir?: string;
  /** Test seam for a concurrent edit after the temp file is complete but before the final CAS check. */
  beforePublish?: () => void;
} = {}): ShellShortcutSetupResult {
  const env = options.env ?? process.env;
  const rcPath = options.rcPath ?? zshRcPath(env);
  const binDir = options.binDir ?? claudeLauncherBinDir();
  const home = options.homeDir ?? env.HOME?.trim() ?? homedir();
  assertNoManagedPlainClaude(binDir);

  let original = "";
  let mode = 0o600;
  if (existsSync(rcPath)) {
    const linkStat = lstatSync(rcPath);
    if (linkStat.isSymbolicLink()) {
      return { state: "refused", rcPath, message: "zsh setup refused because .zshrc is a symlink; use the printed manual PATH line instead" };
    }
    if (!linkStat.isFile()) {
      return { state: "refused", rcPath, message: "zsh setup refused because .zshrc is not a regular file" };
    }
    mode = linkStat.mode & 0o777;
    original = readFileSync(rcPath, "utf8");
  }

  if (original.includes(BLOCK_START) || original.includes(BLOCK_END)) {
    const exact = original.includes(ownedBlock(lineEnding(original), binDir, home));
    return exact
      ? { state: "already_configured", rcPath, message: "zsh account shortcuts are already configured" }
      : { state: "refused", rcPath, message: "zsh setup refused because the frogprogsy marker block was edited" };
  }
  if (containsShortcutPath(original, binDir, home)) {
    return { state: "already_configured", rcPath, message: "the account-shortcut directory is already present in .zshrc" };
  }

  const eol = lineEnding(original);
  const prefix = original.length === 0 || original.endsWith("\n") ? original : `${original}${eol}`;
  const next = `${prefix}${prefix.length > 0 ? eol : ""}${ownedBlock(eol, binDir, home)}${eol}`;
  const originalHash = hash(original);
  mkdirSync(dirname(rcPath), { recursive: true, mode: 0o700 });

  // Compare immediately before publication. A concurrent editor wins and this operation stops.
  const current = existsSync(rcPath) ? readFileSync(rcPath, "utf8") : "";
  if (hash(current) !== originalHash) {
    return { state: "refused", rcPath, message: "zsh setup stopped because .zshrc changed while it was being prepared" };
  }

  const tmp = `${rcPath}.frogp.${process.pid}.tmp`;
  let fd: number | undefined;
  try {
    writeFileSync(tmp, next, { encoding: "utf8", mode });
    fd = openSync(tmp, constants.O_RDONLY);
    fsyncSync(fd);
    closeSync(fd);
    fd = undefined;
    options.beforePublish?.();
    // Recheck after temp fsync, immediately before the irreversible name swap.
    const latest = existsSync(rcPath) ? readFileSync(rcPath, "utf8") : "";
    if (hash(latest) !== originalHash) {
      rmSync(tmp, { force: true });
      return { state: "refused", rcPath, message: "zsh setup stopped because .zshrc changed before it could be replaced" };
    }
    renameSync(tmp, rcPath);
  } catch (error) {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
    try { rmSync(tmp, { force: true }); } catch { /* best effort */ }
    throw error;
  }

  // Verify publication kept the requested mode. chmod is unnecessary because rename publishes the temp inode.
  if ((statSync(rcPath).mode & 0o777) !== mode) {
    throw new Error("zsh setup wrote the file but could not preserve its mode");
  }
  return { state: "configured", rcPath, message: "zsh account shortcuts configured; open a new terminal to use them" };
}

export function removeZshAccountShortcuts(options: { env?: NodeJS.ProcessEnv; rcPath?: string; binDir?: string; homeDir?: string } = {}): ShellShortcutSetupResult {
  const env = options.env ?? process.env;
  const rcPath = options.rcPath ?? zshRcPath(env);
  const binDir = options.binDir ?? claudeLauncherBinDir();
  const home = options.homeDir ?? env.HOME?.trim() ?? homedir();
  if (!existsSync(rcPath)) return { state: "already_configured", rcPath, message: "zsh account shortcuts were not installed" };
  const linkStat = lstatSync(rcPath);
  if (linkStat.isSymbolicLink()) {
    return { state: "refused", rcPath, message: "zsh cleanup refused because .zshrc is a symlink" };
  }
  if (!linkStat.isFile()) {
    return { state: "refused", rcPath, message: "zsh cleanup refused because .zshrc is not a regular file" };
  }

  const original = readFileSync(rcPath, "utf8");
  const eol = lineEnding(original);
  const block = ownedBlock(eol, binDir, home);
  if (!original.includes(BLOCK_START) && !original.includes(BLOCK_END)) {
    return { state: "already_configured", rcPath, message: "zsh account shortcuts were not installed" };
  }
  if (!original.includes(block)) {
    return { state: "refused", rcPath, message: "zsh cleanup refused because the frogprogsy marker block was edited" };
  }

  const mode = lstatSync(rcPath).mode & 0o777;
  const originalHash = hash(original);
  // Splice at the block's own offset and drop only the separator blank line setup inserted directly
  // before it, so blank runs elsewhere in the user's rc file are left untouched.
  const at = original.indexOf(block);
  let head = original.slice(0, at);
  let tail = original.slice(at + block.length);
  // Setup wrote a separator blank line before the block and a line terminator after it; both belong to
  // the block, so they are dropped with it.
  if (tail.startsWith(eol)) tail = tail.slice(eol.length);
  if (head.endsWith(`${eol}${eol}`)) head = head.slice(0, -eol.length);
  const next = `${head}${tail}`;
  const tmp = `${rcPath}.frogp.${process.pid}.tmp`;
  let fd: number | undefined;
  try {
    writeFileSync(tmp, next, { encoding: "utf8", mode });
    fd = openSync(tmp, constants.O_RDONLY);
    fsyncSync(fd);
    closeSync(fd);
    fd = undefined;
    const current = readFileSync(rcPath, "utf8");
    if (hash(current) !== originalHash) {
      rmSync(tmp, { force: true });
      return { state: "refused", rcPath, message: "zsh cleanup stopped because .zshrc changed" };
    }
    renameSync(tmp, rcPath);
  } catch (error) {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
    try { rmSync(tmp, { force: true }); } catch { /* best effort */ }
    throw error;
  }
  return { state: "configured", rcPath, message: "zsh account shortcuts removed" };
}

function pathExportLine(binDir: string, home: string): string {
  return `export PATH="$PATH:${shortcutPathSpelling(binDir, home)}"`;
}

export function zshManualPathLine(binDir = claudeLauncherBinDir(), home = process.env.HOME?.trim() || homedir()): string {
  return pathExportLine(binDir, home);
}

/**
 * Ask once, after the first successfully-created account shortcut, whether zsh should expose it.
 * Non-TTY and non-zsh environments never write files; they print a copyable line instead.
 * Never throws — account creation has already succeeded and shell setup must not roll it back.
 */
export async function maybeConfigureAccountShortcuts(): Promise<void> {
  try {
    const marker = join(getConfigDir(), ".shell-shortcuts-prompted");
    if (existsSync(marker)) return;
    if (!process.stdin.isTTY || !process.stdout.isTTY) {
      console.log(`   To use account shortcuts in a terminal, add: ${zshManualPathLine()}`);
      return;
    }
    if (process.env.SHELL && !process.env.SHELL.endsWith("/zsh")) {
      console.log(`   Automatic setup currently supports zsh. Add this line to your shell: ${zshManualPathLine()}`);
      return;
    }

    ensureConfigDirForWrite("write shell shortcut prompt marker");
    writeFileSync(marker, new Date().toISOString(), { encoding: "utf8", mode: 0o600 });
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    let yes = false;
    try {
      const answer = (await rl.question("\n계정별 Claude 명령을 터미널에서 바로 사용하도록 설정할까요? [Y/n] ")).trim().toLowerCase();
      yes = answer === "" || answer === "y" || answer === "yes";
    } finally {
      rl.close();
    }
    if (!yes) {
      console.log(`   Manual setup: ${zshManualPathLine()}`);
      return;
    }
    const result = configureZshAccountShortcuts();
    const stream = result.state === "refused" ? console.error : console.log;
    stream(`   ${result.message}`);
    if (result.state === "refused") console.log(`   Manual setup: ${zshManualPathLine()}`);
  } catch (error) {
    console.error(`   Shell setup skipped: ${error instanceof Error ? error.message : String(error)}`);
    console.log(`   Manual setup: ${zshManualPathLine()}`);
  }
}
