import { createHash } from "node:crypto";
import { createInterface } from "node:readline/promises";
import {
  closeSync,
  constants,
  existsSync,
  fsyncSync,
  fstatSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import type { Stats } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { claudeLauncherBinDir, claudeLauncherFileName } from "./claude-launchers";
import { ensureConfigDirForWrite, getConfigDir } from "./config";

const BLOCK_START = "# >>> frogprogsy account shortcuts >>>";
const BLOCK_END = "# <<< frogprogsy account shortcuts <<<";
const MANAGED_MARKER = "Generated by frogprogsy";

export type ShellShortcutSetupState = "configured" | "already_configured" | "refused";

export interface ShellShortcutSetupResult {
  state: ShellShortcutSetupState;
  rcPath: string;
  message: string;
  warning?: string;
}

function zshRcPath(env: NodeJS.ProcessEnv = process.env): string {
  const zdotdir = env.ZDOTDIR?.trim();
  return join(zdotdir || env.HOME?.trim() || homedir(), ".zshrc");
}

function lineEnding(content: string): "\n" | "\r\n" {
  return content.includes("\r\n") ? "\r\n" : "\n";
}

function hash(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function containsPathEntry(line: string, path: string): boolean {
  let from = 0;
  while (from < line.length) {
    const index = line.indexOf(path, from);
    if (index === -1) return false;
    const before = index === 0 ? undefined : line[index - 1];
    const afterIndex = index + path.length;
    const after = afterIndex === line.length ? undefined : line[afterIndex];
    const leftBoundary = before === undefined || ":=\"' \t".includes(before);
    const rightBoundary = after === undefined || ":\"' \t;".includes(after);
    if (leftBoundary && rightBoundary) return true;
    from = index + path.length;
  }
  return false;
}

function containsShortcutPath(content: string, binDir: string): boolean {
  return content.split(/\r?\n/).some(line => {
    const assignment = line.match(/^\s*(?:export[ \t]+)?PATH=(.*)$/);
    if (!assignment) return false;
    const normalized = assignment[1].replaceAll("${HOME}", "$HOME");
    return containsPathEntry(normalized, "$HOME/.frogprogsy/bin") || containsPathEntry(normalized, binDir);
  });
}

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function defaultShortcutBinDir(env: NodeJS.ProcessEnv): string {
  return join(env.HOME?.trim() || homedir(), ".frogprogsy", "bin");
}

function shortcutPathLine(binDir: string, env: NodeJS.ProcessEnv): string {
  return binDir === defaultShortcutBinDir(env)
    ? 'export PATH="$PATH:$HOME/.frogprogsy/bin"'
    : `export PATH="$PATH":${shellSingleQuote(binDir)}`;
}

function ownedBlock(eol: string, binDir: string, env: NodeJS.ProcessEnv): string {
  return [
    BLOCK_START,
    shortcutPathLine(binDir, env),
    BLOCK_END,
  ].join(eol);
}

export function zshAccountShortcutsSupported(env: NodeJS.ProcessEnv = process.env): boolean {
  return process.platform !== "win32" && env.SHELL?.endsWith("/zsh") === true;
}

function assertNoManagedPlainClaude(binDir: string): void {
  for (const target of [
    join(binDir, claudeLauncherFileName("claude")),
    join(binDir, "claude"),
    join(binDir, "claude.cmd"),
  ]) {
    if (!existsSync(target)) continue;
    try {
      if (readFileSync(target, "utf8").includes(MANAGED_MARKER)) {
        throw new Error("shell setup refused: a frogprogsy-owned plain claude launcher still exists; run frogp refresh first");
      }
    } catch (error) {
      if (error instanceof Error && error.message.startsWith("shell setup refused:")) throw error;
      throw new Error("shell setup refused: the managed launcher directory could not be inspected");
    }
  }
}

function errorCode(error: unknown): string | undefined {
  if (!error || typeof error !== "object" || !("code" in error)) return undefined;
  return typeof error.code === "string" ? error.code : undefined;
}

function appendRcWithoutReplacing(options: {
  rcPath: string;
  original: string;
  next: string;
  mode: number;
  expectedDev?: number;
  expectedIno?: number;
  beforeAppend?: () => void;
}): boolean {
  const noFollow = constants.O_NOFOLLOW ?? 0;
  const existed = options.expectedDev !== undefined && options.expectedIno !== undefined;
  const flags = existed
    ? constants.O_RDWR | constants.O_APPEND | noFollow
    : constants.O_WRONLY | constants.O_APPEND | constants.O_CREAT | constants.O_EXCL | noFollow;
  let fd: number | undefined;
  try {
    fd = openSync(options.rcPath, flags, options.mode);
    const opened = fstatSync(fd);
    if (!opened.isFile()) return false;
    if (existed && (opened.dev !== options.expectedDev || opened.ino !== options.expectedIno)) return false;

    options.beforeAppend?.();
    let currentPath: Stats;
    try {
      currentPath = lstatSync(options.rcPath);
    } catch {
      return false;
    }
    if (!currentPath.isFile() || currentPath.isSymbolicLink()) return false;
    if (currentPath.dev !== opened.dev || currentPath.ino !== opened.ino) return false;
    if (hash(readFileSync(options.rcPath, "utf8")) !== hash(options.original)) return false;

    writeFileSync(fd, options.next.slice(options.original.length), { encoding: "utf8" });
    fsyncSync(fd);

    let publishedPath: Stats;
    try {
      publishedPath = lstatSync(options.rcPath);
    } catch {
      return false;
    }
    return publishedPath.isFile()
      && !publishedPath.isSymbolicLink()
      && publishedPath.dev === opened.dev
      && publishedPath.ino === opened.ino
      && readFileSync(options.rcPath, "utf8") === options.next;
  } catch (error) {
    if (["EEXIST", "ELOOP", "ENOENT"].includes(errorCode(error) ?? "")) return false;
    throw error;
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

/**
 * Append the account-shortcut directory to zsh PATH without touching user-owned shell configuration.
 *
 * Safety boundary:
 * - only one exact marked block is owned;
 * - symlink rc files are refused rather than replaced;
 * - mode and line endings are preserved;
 * - an existing regular file is opened without following symlinks and appended in place;
 * - file identity and content are revalidated immediately before append and identity is checked again after it;
 * - a missing rc file is created exclusively, without a staging or replacement rename;
 */
export function configureZshAccountShortcuts(options: {
  env?: NodeJS.ProcessEnv;
  rcPath?: string;
  binDir?: string;
  /** Test seam after the append fd opens but before identity/content revalidation. */
  beforeAppend?: () => void;
} = {}): ShellShortcutSetupResult {
  const env = options.env ?? process.env;
  const rcPath = options.rcPath ?? zshRcPath(env);
  const binDir = options.binDir ?? claudeLauncherBinDir();
  assertNoManagedPlainClaude(binDir);

  let original = "";
  let mode = 0o600;
  let expectedDev: number | undefined;
  let expectedIno: number | undefined;
  if (existsSync(rcPath)) {
    const linkStat = lstatSync(rcPath);
    if (linkStat.isSymbolicLink()) {
      return { state: "refused", rcPath, message: "zsh setup refused because .zshrc is a symlink; use the printed manual PATH line instead" };
    }
    if (!linkStat.isFile()) {
      return { state: "refused", rcPath, message: "zsh setup refused because .zshrc is not a regular file" };
    }
    mode = linkStat.mode & 0o777;
    expectedDev = linkStat.dev;
    expectedIno = linkStat.ino;
    original = readFileSync(rcPath, "utf8");
  }

  if (original.includes(BLOCK_START) || original.includes(BLOCK_END)) {
    const exact = original.includes(ownedBlock(lineEnding(original), binDir, env));
    return exact
      ? { state: "already_configured", rcPath, message: "zsh account shortcuts are already configured" }
      : { state: "refused", rcPath, message: "zsh setup refused because the frogprogsy marker block was edited" };
  }
  if (containsShortcutPath(original, binDir)) {
    return { state: "already_configured", rcPath, message: "the account-shortcut directory is already present in .zshrc" };
  }

  const eol = lineEnding(original);
  const prefix = original.length === 0 || original.endsWith("\n") ? original : `${original}${eol}`;
  const next = `${prefix}${prefix.length > 0 ? eol : ""}${ownedBlock(eol, binDir, env)}${eol}`;
  mkdirSync(dirname(rcPath), { recursive: true, mode: 0o700 });
  const published = appendRcWithoutReplacing({
    rcPath,
    original,
    next,
    mode,
    expectedDev,
    expectedIno,
    beforeAppend: options.beforeAppend,
  });
  if (!published) {
    return { state: "refused", rcPath, message: "zsh setup stopped because .zshrc changed before the PATH block could be appended" };
  }

  const warning = (lstatSync(rcPath).mode & 0o777) !== mode
    ? "zsh account shortcuts were configured, but .zshrc permissions changed; review that file's permissions"
    : undefined;
  return {
    state: "configured",
    rcPath,
    message: "zsh account shortcuts configured; open a new terminal to use them",
    ...(warning ? { warning } : {}),
  };
}

export function removeZshAccountShortcuts(options: { env?: NodeJS.ProcessEnv; rcPath?: string; binDir?: string } = {}): ShellShortcutSetupResult {
  const env = options.env ?? process.env;
  const rcPath = options.rcPath ?? zshRcPath(env);
  const binDir = options.binDir ?? claudeLauncherBinDir();
  if (!existsSync(rcPath)) return { state: "already_configured", rcPath, message: "zsh account shortcuts were not installed" };
  const pathStat = lstatSync(rcPath);
  if (pathStat.isSymbolicLink() || !pathStat.isFile()) {
    return { state: "refused", rcPath, message: "zsh cleanup refused because .zshrc is not a regular file" };
  }

  const original = readFileSync(rcPath, "utf8");
  const block = ownedBlock(lineEnding(original), binDir, env);
  if (!original.includes(BLOCK_START) && !original.includes(BLOCK_END)) {
    return { state: "already_configured", rcPath, message: "zsh account shortcuts were not installed" };
  }
  if (!original.includes(block)) {
    return { state: "refused", rcPath, message: "zsh cleanup refused because the frogprogsy marker block was edited; remove it manually" };
  }
  return {
    state: "refused",
    rcPath,
    message: "zsh cleanup does not rewrite shell configuration automatically; remove the exact frogprogsy marker block manually",
  };
}

export function zshManualPathLine(options: { env?: NodeJS.ProcessEnv; binDir?: string } = {}): string {
  const env = options.env ?? process.env;
  return shortcutPathLine(options.binDir ?? claudeLauncherBinDir(), env);
}

function powerShellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function shellManualPathLine(options: { env?: NodeJS.ProcessEnv; binDir?: string } = {}): string {
  const env = options.env ?? process.env;
  const binDir = options.binDir ?? claudeLauncherBinDir();
  const shell = env.SHELL?.trim().toLowerCase() ?? "";
  if (process.platform === "win32" || /(?:^|\/)(?:pwsh|powershell(?:\.exe)?)$/.test(shell)) {
    return `$env:Path += [IO.Path]::PathSeparator + ${powerShellSingleQuote(binDir)}`;
  }
  if (/(?:^|\/)fish$/.test(shell)) {
    return `fish_add_path --append ${shellSingleQuote(binDir)}`;
  }
  if (/(?:^|\/)t?csh$/.test(shell)) {
    return `setenv PATH "$PATH":${shellSingleQuote(binDir)}`;
  }
  return shortcutPathLine(binDir, env);
}

/**
 * Ask once, after the first successfully-created account shortcut, whether zsh should expose it.
 * Non-TTY and non-zsh environments never write files; they print a copyable line instead.
 * Never throws — account creation has already succeeded and shell setup must not roll it back.
 */
export async function maybeConfigureAccountShortcuts(): Promise<void> {
  try {
    const marker = join(getConfigDir(), ".shell-shortcuts-prompted");
    if (existsSync(marker)) return;
    if (!process.stdin.isTTY || !process.stdout.isTTY) {
      console.log(`   To use account shortcuts in a terminal, add: ${shellManualPathLine()}`);
      return;
    }
    if (!zshAccountShortcutsSupported(process.env)) {
      console.log(`   Automatic setup currently supports zsh on POSIX. Add this line to your shell configuration: ${shellManualPathLine()}`);
      return;
    }

    ensureConfigDirForWrite("write shell shortcut prompt marker");
    writeFileSync(marker, new Date().toISOString(), { encoding: "utf8", mode: 0o600 });
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    let yes = false;
    try {
      const answer = (await rl.question("\nSet up account-specific Claude commands in your terminal? [Y/n] ")).trim().toLowerCase();
      yes = answer === "" || answer === "y" || answer === "yes";
    } finally {
      rl.close();
    }
    if (!yes) {
      console.log(`   Manual setup: ${shellManualPathLine()}`);
      return;
    }
    const result = configureZshAccountShortcuts();
    const stream = result.state === "refused" ? console.error : console.log;
    stream(`   ${result.message}`);
    if (result.state === "refused") console.log(`   Manual setup: ${shellManualPathLine()}`);
  } catch (error) {
    console.error(`   Shell setup skipped: ${error instanceof Error ? error.message : String(error)}`);
    console.log(`   Manual setup: ${shellManualPathLine()}`);
  }
}
